### ISSUE TITLE
Funnels

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1006]
- *Pink Promise* applies.

That's really all you need.

**Comment by iamwhoiamhahaha** [comment]
> BlueNovember
Funnel is fun. Optimal save of a 5 seems to be a 4 clue, followed by [x] on all incidental cards. As 4 will reveal all 5s in hand 
https://hanab.live/replay/853515#54

**Comment by iamwhoiamhahaha** [comment]
> Pink Promise applies.

I don't think we are supposed to play **Funnels** with Pink conventions. Pink-Ones conventions, i.e. [Play Clues on 1's with Number 2, Number 3, or Number 4](https://hanabi.github.io/docs/variant-specific/pink-ones#play-clues-on-1s-with-number-2-number-3-or-number-4) seem better. Note that 4 is a *Save Clue* instead of a *Play Clue*. Alternatively, 5 should be a *Play Clue*.

**Comment by Zamiell** [comment]
> Optimal save of a 5 seems to be a 4 clue,

in my games we used number 1 and number 2 to do a *Trash Chop Move* on 5's

(obviously you won't be able to do this in all situations but it seems much better)

**Comment by ReaverSe3** [comment]
Pink Promise

When a card is focused by a rank clue, the number must match the true identity of the card.

No 5 tech

No 5 pull, 5 number discharge in this variant.

Number 5 clue

Number 5 Clue triggers double ignition. Must clue the person with the 2nd blind-play
if it is not the case,  it triggers ejection on recipient.

Negative 5 save

if number 4 clue reveals 5 on chop, it is treated as 5 save.

4 Chop Move

if number 4 clue reveals 5 on off chop, it indicates 4 Chop Move.
- Cards to the right of the rightmost 5 are Chop Moved
- Cards to the left of the rightmost 5 are treated as unclued.

Number 4 clue
if 4 Clue doesn't reveal any 5's, apply normal or pink conventions.
But non-focused card are treated as unclued.

**Comment by argothiel** [comment]
What's a funnel?

**Comment by Zamiell** [comment]
<https://github.com/Hanabi-Live/hanabi-live/blob/main/docs/VARIANTS.md#funnels>

**Comment by argothiel** [comment]
Thanks!

**Comment by Zamiell** [comment]
what do other people think about reaver's conventions

**Comment by argothiel** [comment]
I prefer incorporating existing conventions (regular 5 Tech) instead of new ones, like here:
https://hackmd.io/aQLjqp2cS96o_LA--hKuTw

**Comment by Zamiell** [comment]
do you want to propose something more specific than linking a big doc

**Comment by argothiel** [comment]
It's not my document, somebody linked it to me. Unfortunately, I don't see how it could be more specific than what's in this document:

### Color clues
Color clues do not change from H-group.

### 4 Clues
If any new 5’s are revealed (with a negative), the clue is standard 5 clue (5 save, 5cm, 5 tech). Mark all (newly touched) 4’s as “unclued”. Otherwise, the 4 is a regular clue on just the chop 4. Mark all other (newly touched) 4’s as “unclued”.

### 5 Clues
If it can be, it is a double ignition (standard DI rules, favor DI on Bob, etc).
The double ignition clue must be on the last player with a playable on finesse. Otherwise, it reverts to a no-info ejection (possibly unnecessary).
Otherwise, it is a no-positive-information ejection on Roger (the receiver of the clue). See [special moves](https://hanabi.github.io/docs/variant-specific/no-positive-clues/#special-move-summary).
If the ejection on roger was unnecessary and cannot be a 5, it is a double ejection (Bob and either Roger or Cathy, whoever has the last playable on ejection).

### Brown Variants
In brown, brown is play chop, 4 is single cm.
In null, 4 is single save, 5 is kick.

### Pink Variants
Save pink 5 with rank 2. Like normal 2 saves, all touched cards are clued.

**Comment by Zamiell** [comment]
who is roger

**Comment by argothiel** [comment]
Roger is the receiver of the clue.

**Comment by Zamiell** [comment]
Don't introduce non canonical characters lol

**Comment by argothiel** [comment]
It's already a fan canon, present in several convention sets. ;)

**Comment by Zamiell** [comment]
I'm not a big fan of fan fiction =p

**Comment by Zamiell** [comment]
Does anybody else have an opinion on the 4 clues + 5 clues conventions that argo posted?

**Comment by Stuurrm** [comment]
The 4 and 5 clues do not work with brown, muddy rainbow or null suit.

With white and light-pink some problems arise if you need to save a critical 4 and they have a 5 that is more than 1 away from chop. But that is pretty unlikely.

Without those special suits they work well.

**Comment by Stuurrm** [comment]
Well to be more precise with brown or muddy rainbow you could be doing better stuff but they still function as well.

**Comment by ReaverSe3** [comment]
I like signal shifts part of algo's link. It seems better than my convenitons.
but Idk how to copy a chart on here

**Comment by Zamiell** [comment]
which members of h-group are playing the most funnels in 2023? i need to know which conventions have consensus, since a few different ones were posted in this thread over the course of the year, and i would like to close out the issue.

**Comment by Stuurrm** [comment]
All in all funnels is a pretty unpopular variant. There has been some bursts of games where I have played more of it but mostly **maximum** of 1-3 games a month. (Shame though, I quite like the variant.)

idk what other people have been playing with (if they have) but I have been consistantly playing with pink conventions but a 4 clue CMs 1s and a 5 clue twice. Mark all cards as untouched but if any 5s were revealed self cm then as by the self cm convention. (There is not a specific thread for chimneys but basically I have played it the same way but 2s for once and 1s for twice).

On top of those CMs I have also usually played with an expanded reaction table for what to do when your cm is a bit wierd. For example if you chop moved 1 good card and 1 bad card but honestly those are not required and you can just play with bcme and chop move ignition.

**Comment by Zamiell** [comment]
> I have been consistently playing with pink conventions but a 4 clue CMs 1s and a 5 clue twice. Mark all cards as untouched but if any 5s were revealed self cm then as by the self cm convention. (There is not a specific thread for chimneys but basically I have played it the same way but 2s for once and 1s for twice).

can you do a PR for that please?
