### ISSUE TITLE
New Dawn

### ISSUE THREAD

**Issue by vEnhance** [hanabi/hanabi.github.io#1039]
The original Dawn never got a PR, so let's try again? xD This is a subset of the full Dawn setup in the KPP doc, trying to keep things not too complicated.

## Definition

- **Dawn** lasts for the first full two rounds of each game. This means Dawn lasts for 6 turns in 3-player games, 8 turns in 4-player, and 10 turns in 5-player.
- Dawn is turned off in 6-player games.  
- During Dawn, a play clue which requires **at least 2 blind plays from Bob** has a different meaning than it would during the rest of the game. We refer to these as **Dawn Responses**.

## Disabled conventions

To make room for Dawn Responses:

- 3 bluffs are disabled, except for self-bluffs.
- 4 charm is disabled.
- 5 color ejection is disabled.
- Unknown trash discharge, unknown dupe discharge, and unknown trash charm are disabled.

## Dawn Responses

When Alice gives a clue to a card that would require 2 blind plays from Bob, the following responses are demanded instead.

- 3 -> Ejection, unless the clue could be a Self-Bluff (which would then take precedence).
- 4 -> Discharge, unless the clue could be a Double Bluff (which would then take precedence).
- 5 -> Charm; this replaces the 5 color ejection.
- Unknown trash -> Blast, in 5 players only; this replaces the unknown trash discharge.

**Comment by Zamiell** [comment]
Currently, we expect players to keep track of two specific states:
- _Early Game_ --> _Mid-Game_ - For clue requirements and 5 Stalls
- _Low-Score Phase_ --> _Normal-Score Phase_ - For 5 Pulls to work

Both of these state tracking things are annoying and make playing Hanabi with us much harder. We hesitantly allow them because they tend to provide a lot of value.

The worst thing about Dawn is that it expands the state tracking from 2 things to 3 things:

- _Dawn_ --> _Normal_ - Clue interpretations change.

I don't think it is healthy to continue to add in more state tracking to the convention framework, even if the result is more "optimal" or adds a lot of value.

**Comment by pianoblook** [comment]
My opinion is mostly unchanged from the conclusion back in #589:

- It is really freakin' good. New Dawn is even better than OG-Dawn, plus somewhat more intuitive.
- That said, it's a huge change to commit to for the whole community. I'd feel very uncomfortable making such a big change without a **lot** of community support.

**Comment by Krycke** [comment]
I guess this is when those experimental/alternative additional convention sets would be great. They can be added in a staging area for people to easily read and choose to addon or not. ie "let's play lvl 25 + dawn". And when more and more of the community uses the staged convention, it can be included in the normal set.

**Comment by vEnhance** [comment]
Sounds like we're not ready to add dawn into mainline conventions yet. Cool.
