### ISSUE TITLE
Sudoku

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1094]
## Rank Explosion (RE) - Created by ReaverSe and Kyle

- This convention only applies on the very first turn of the game.
- If Alice gives a rank clue, it is a normal play clue on the focused card, and also conveys an additional meaning.
- The additional meaning is for the final two players at the table to blind-play. (The final two players does not include the person who received the rank clue.)
- The two blind-playing players should blind-play the slot number corresponding to the rank clue that was given.
- For example, in a 4-player game:
  - It is the first turn and nothing is played on the stacks.
  - Alice clues Donald number 2, touching a red 2 on slot 1.
  - Bob blind-plays slot 2. It is a blue 3 and successfully plays on the stacks.
  - Cathy blind-plays slot 2. It is a green 4 and successfully plays on the stacks.
  - Donald plays the red 2 that was originally clued.
- In a 3-player game:
  - The clued player always blind-plays his _Finesse Position_. (On their next turn, they can play the focus of the rank clue.)
  - The non-clued player always blind-plays the slot number corresponding to the rank clue.
- For example, in a 3-player game:
  - It is the first turn and nothing is played on the stacks.
  - Alice clues Cathy number 2, touching a red 2 on slot 1.
  - Bob blind-plays slot 2. It is a blue 3 and successfully plays on the stacks.
  - Cathy blind-plays _Finesse Position_ (slot 1). It is a green 4 and successfully plays on the stacks.
  - On her next turn, Cathy can play the clued card as a red 2, yellow 2, or a purple 2.

<br>

## Safety Blind Play (SBP) - Created by str8tsnacler

- This convention only applies on the very first turn of the game.
- If Alice plays slot 1, Bob chop moves.
- If Alice plays slot 2, Cathy chop moves.
- If Alice plays slot 3:
  - In a 3-player game --> Bob chop moves twice.
  - In a 4-player game --> Donald chop moves.
  - In a 5-player game --> Donald chop moves.
- If Alice plays slot 4:
  - In a 3-player game --> Cathy chop moves twice.
  - In a 4-player game --> Bob chop moves twice.
  - In a 5-player game --> Emily chop moves.
- If Alice plays slot 5:
  - In a 3-player game --> Bob chop moves three times.

<br>

## Last Color Ejection (LCE) - Created by spring

- The _5 Color Ejection_ (5CE) convention is turned off in Sudoku variants.
- However, you can still perform the equivalent move by giving a color clue to the last card in a stack.
- LCE is inherently worse than 5CE, because 5CE is always on a critical card, and LCE is not necessarily on a critical card. However, since the required efficiency of Sudoku is low, we still prefer LCE over a _Finesse_ that requires two-or-more-blind-plays from Bob.

**Comment by unsoftcapped3** [comment]
for the rank explosion, there should also be a section that says in a 5p game if the non-blind-playing player who didn't receive the rank clue sees that it is impossible for the final 2 players to both play that slot, then the non-blind-playing player should play that slot instead of the first of the final 2 players (example: https://hanab.live/game/193#3. newduke sees that Ramanujan and spring cannot both blind play from slot 2, so he plays slot 2 instead of Ramanujan doing it)

**Comment by kesslermaximilian** [comment]
+1. Also, I suppose you mean https://hanab.live/replay/1000095#2. If you want to post games, make sure you use a `/replay` link, since these contain the game id and are stable. What you had is a link to a running table and these change after a game or review finishes.

**Comment by unsoftcapped3** [comment]
from yagami_black: "a 1 for 1 clue on turn 1 is a double ignition on bob and cathy"

**Comment by unsoftcapped3** [comment]
from spring: "3 bluffs are disabled in this variant" (as in the 3rd card of a suit)

**Comment by iamwhoiamhahaha** [comment]
I just realize that it might not be working in a 3 player game. For example, you see a red 4 and blue 5 on slot 1. And you play a red 5. (Interesting blue 4 works here)
I think *Sudoku Positional Blind Play* only works in a 4 or more player game.

**Comment by unsoftcapped3** [comment]
for rank explosion, should cluing 5 on a 4 or 5 player game trigger a double ignition in addition to getting the 5 played?

**Comment by iamwhoiamhahaha** [comment]
Sudoku Positional Blind Play Information - Created by IAMJEFF
- This convention only applies on the very first turn of the game.
- This convention only applies to a 3 player game.
- Alice is allowed to blind-play her slot 1 on the very first turn. It is safe to do it because all cards are playable at the moment. We agree that it means nothing else.
- However, what if Alice blind-plays a card from other slots? In this situation, she is trying to communicate something extra.
- We agree that two cards on the specific slot that Alice blind-plays shares identical information, i.e., either same rank or same color. (We can decide that if they should chop move it.)
- For example, in a 3 player Sudoku game:
  - Alice blind-plays her slot 2 on the first turn. It is a red 1 and it successfully plays.
  - Bob sees that Cathy has a green 3 on slot 2. Then he knows that the card on his slot 2 is either a 3 or a green card.
  - Cathy sees that Bob has a blue 3 on slot 2. Then she marks her slot 2 with either a 3 or a blue card.

**Comment by iamwhoiamhahaha** [comment]
> ## Safety Blind Play (SBP) - Created by str8tsnacler
> - This convention only applies on the very first turn of the game.
> - If Alice plays slot 1, Bob chop moves.
> - ...

I don't think it's a good idea to chop move cards in a sudoku game. You don't usually know which cards are more valuable on the first turn. 
On the other hand, I also don't think that it's a good idea to blind-play a random card on turn 1. It's a 1-for-0 move, which is decent I know. But sometimes, you'll be ruining some other better lines you can perform other than playing. For example, you see r345 somewhere and you blind-play a r1. And both r2s are on the bottom. Which is quite bad.
In my opinion, randomly blind-playing a card on turn 1 is not that good. It's overrated. However, if we can abuse the ability to randomly blind-play a card on the very first turn in this variant. That'll be awesome. Not just a 1-for-0, but more. Which is the reason I invented the conventions above.

**Comment by Zamiell** [comment]
which members of h-group are playing the most sudoku in 2023? i need to know which conventions have consensus, and i would like to close out the issue.

**Comment by purple-joe** [comment]
Can we add rank explosion to the doc? Seems like most people play with that. Last color ejection is also good.

These are the two conventions that seem to be used the most.

**Comment by Zamiell** [comment]
ill add those 2, and then close this issue, thanks
