### ISSUE TITLE
Move UDD to level 16

### ISSUE THREAD

**Issue by unsoftcapped3** [hanabi/hanabi.github.io#1118]
since zamiel doesn't believe that udd should be level 16, I'm making a poll here

**Comment by EhDrone** [comment]
Can you add why you think it should be in level 16?

 I saw in the other thread you said “people use it”, but there can be many reason why that happens. One could be it belongs there, which is a doc issue. Another could be people are playing out of level and introducing it too early for players which is a teacher issue.

**Comment by David707x** [comment]
It's quite regular someone will perform UDD in a level 16 game and a player will not understand it as they didn't read I in level 16. Alot of players think UDD is lv16. It's very similar to UTD and no harder to understand. It is just UTD with a dupe instead of trash.

**Comment by EhDrone** [comment]
Could be fine - though I am curious how often a UDD is attempted and failed for other reasons even in Level 16. For example at level 10, it's quite regular that someone will perform a bluff. That doesn't mean we should move bluffs up a level, it means that players should respect their teammates abilities and play in-level even if it sometimes means missing a perfect score.

That being said, UDD is indeed rooted in the concept of a UTD - so I am not saying I am against moving UDD to be included with UTD in level 16, just looking for additional convincing beyond "people do it", because that is a poor reason often times.

**Comment by David707x** [comment]
Oh I absolutely agree we should play in level and even a quick glance at the levels shows bluffs are level 11. However, part of the issue here is everyone seems to think UDD is level 16 until told otherwise, they aren't intentionally playing out of level.

**Comment by EhDrone** [comment]
> everyone seems to think UDD is level 16 until told otherwise
That can't be true. UDD is never introduced at level 16, while someone may logically deduce that "if I touch both copies of something one is trash!" I honestly would say it is unlikely to come up naturally from someone playing at level 16. Meaning that people don't even know its a thing at level 16 until someone else introduces it to them. It is almost **always** introduced by a higher level player who either did one in-game (out of level) and caused an issue, thereby introducing it to 2/3/4/5 other players - or upon review someone brought up "By the way a cool higher level convention is UDD which would have been great in this spot"

**Comment by David707x** [comment]
ok that was a bit of an exaggeration, but in several reviews of Level 16-21 games when discussed several players will say "I thought it was Lv16".

**Comment by Stuurrm** [comment]
I will say that because UDD is a fair bit more complicated that UTD I do not believe level 16 would be the best place for it. People are still learning the ropes of discharges at that level.

On the other hand the place of it isn’t really in advanced because as the introduction to them tells us they are supposed to be rarely used conventions while UDD is extremely common.

Where I would place it is in level 21. People have at that point learned discharges and would probably be ready for UDD. Though to be fair that level is already pretty packed.

An another alternative would be level 24 which is less packed as a level.

**Comment by kesslermaximilian** [comment]
After some thought, I tend to agree with sSturm. Not only because there are some cases where cluing dupes does not cause a discharge. Also the implication of order chop moves done with *known * dupes in hand can be pretty confusing when first playing with UDD, especially since the order is not left-to right but focus / not focus.

I don't have a strong preference on what level to place it in, but I agree that it should at least be moved out of the extras, but presumably not level 16 due to mentioned complications.

**Comment by Zamiell** [comment]
i dont like putting it in a separate level since it is so similar to UTD.
for now i'll move it to level 16
