### ISSUE TITLE
Add to End Game Strategies

### ISSUE THREAD

**Issue by benzloeb** [hanabi/hanabi.github.io#1119]
This idea is inspired by the "100 prisoners problem", and can make some endgames more likely to win. 
The idea is that if there are 2 cards left to play, you know that one must be in your hand due to elimination, but you have no clue to inform the last player where their playable card is, you play from the same slot they should. (This also requires that no other player can do a Positional discard or misplay) 

For example in a 2 player game: 
Only r5 and b5 are left to play. No cards in deck left, players are on their final turns
X X X r5 X
X X X b5 X
Alice plays 4th slot to indicate Bob should play 4th slot. Since neither of them knew where their 5's were, normally this endgame would be a 1/25 to win should they both guess. By adding this strategy, they can win 1/5th of these endgames. 

This strategy has come up a number of times for me in clue starved because clues are so limited.

**Comment by EhDrone** [comment]
This is one of those things that is how everyone plays, but is such an infrequent edge case there's been (to my understanding) no reason to put it in the doc. 

We already have positional discard and blind play - and they are basically the exact thing at play here. The difference being the two playable cards are in Alice and Bob/Cathy's hand. So if Alice has no clue, she obviously cannot positional discard - as she knows she has a playable in her hand. So she bombs her appropriate slot to get Bob/Cathy to blind play. And only one should... because if there is a playable in her hand, then by definition only one of Bob or Cathy has a playable (assuming remaining cards are critical).

**Comment by argothiel** [comment]
For me, it's a type of a Positional Misplay. You are not allowed not use the Positional Discard, because you might be discarding a valuable card. So you're attempting to do a misplay. It's like with any other type of a misplay: it doesn't matter if the card successfully plays, it should still be read as (an attempted) misplay, given you didn't know what you were playing.
