### ISSUE TITLE
Interaction between 2-Saves and Permission to Discard in guiding situations

### ISSUE THREAD

**Issue by purple-joe** [hanabi/hanabi.github.io#1122]
- In situations where Alice gave a clue that forced Bob to blind-play, we agree that Cathy does not have PTD if there is a mutually (for Alice and Cathy) visible 2-Save to give that (from Alice’s point of view) was legal when Alice gave a clue.
- As a consequence, if Cathy has nothing better to do, she is allowed (and expected) to save the visible 2, even if one of the following is the case:
    - the other copy of the 2 is visible in Alice’s hand.
    - the other copy of the 2 was drawn by Bob and the clue is now a Bad Touch (this does not trigger a Discharge).
- This would mean that Bob cannot always assume that his 2 is a unique copy on the board, unless he sees a better clue Cathy could have given.
- Note that Cathy does not need to save Bob’s 2 on chop. For example, if Cathy sees the other copy of the 2 in Alice’s hand, she is allowed to give some other clue that kills Bob’s copy, which would trigger Elimination Notes for Alice.
- Of course, this rule also applies to Donald in case Alice gave a clue that made both Bob and Cathy blind-play.

(credit for this convention is not to me)
This convention should be added to the doc because a league game was lost due to this exact reason: https://hanab.live/replay/1001986#1

**Comment by unsoftcapped3** [comment]
Bob should not have played y3 in this case. From his perspective, Cathy might not save Donald's 2 if he has the other copy in his own hand, therefore there is a chance Cathy could discard and so he has to save the 5

**Comment by unsoftcapped3** [comment]
in the game you linked the y3 was already clued so it's not a blind play and he doesn't have to play it right away (bob can even just discard y1 to shout cm the y5)

**Comment by EhDrone** [comment]
"I lost a league game" is a bad reason to introduce additional complexity. Part of guiding principle is the understanding that information is asynchronous, such as an expected 2 save may not actually be a viable clue to give if Alice is holding the other copy off-chop. The things to consider are:
1) How often does this scenario come up and cause a game to be lost?
2) How much overhead / complexity is added by needing to consider this scenario in situations where it isn't present vs ones where it is?
3) How many mistakes are caused by this additional overhead vs mistakes caused by a poor line being chosen?

In my experience, it happens rarely (though it does happen) that a 2 save is expected by Alice, but not given by Bob because Alice is holding the copy. It is rarer that this scenario happens and causes a game to be lose by immediately discarding a critical or playable card (even if playable, another copy exists).

**Comment by kesslermaximilian** [comment]
A few points I would like to add to the discussion here:

@unsoftcapped3: I think it is definitely *not* the case that Bob should not have blind-played. This is exactly what guiding principle is about, from Bob's perspective, it could be that his Chop is a 5 that Cathy will save.

@EhDrone: I agree that we are talking small risks here and this rarely comes up to actually lose games. The thing I rather want to point out is that you now have a few ways out of this:
- Agree that sometimes you get unlucky and accept the loss (so you're betting on something like 1/30 not to happen here)
- Choose a different line not relying on the 2-save. While this is certainly sometimes possible, it definitely restricts you in what you can do. In particular, notice that now you are worse than in case one in 29/30 cases (where you would not actually have needed to save Bob because you don't draw p2), so if this is the preferred choice, lines not relying on the 2-save have to have little to no downside compared to risking the 1/30 of drawing p2.
- Agree to have the 2-save regardless. I particularly like this because it takes away any gambling aspect, because you *know* that Cathy does not discard. The point here is that in  most cases this does not change the way we play anyway, because maybe there is simply no 2 in Bobs hand. And even if, I think the downside of missing a negative color on that 2 (that is not global information anyway) is rather little.

I think lots of this discussion is actually similar to 5-stalls in the early game. 5 stalls are not great clues because they are efficient or something, they are great because they often give us *Safety* to craft lines where a certain player does not discard.
The same concept can be applied to 2-Saves to give more certainty when crafting lines.

That being said, I do agree that this is just a niche case of a convention and most players are probably happy to accept a 1/30 or other downsides circumventing the problem (for example, shouting at y5 by discarding in above example), and it might not be what we want in regular H because it's just one more exception.

As some context, we came across this in the League games but also when playing Max-Lvl NoVar, so the use case is really when it comes to optimizing the last few percents of a game.

In hard variants, all this discussion is probably irrelevant, because you are very happy to accept the 1/30 chance.

**Comment by unsoftcapped3** [comment]
again, in the game purplejoe linked, there is no blind play involved. Alice gave a prompt for y3 in Bob's hand to Donald, who will not misplay the y4 as y3 because y3 is already clued. This isn't a blind play, so Alice is not forcing Bob to play y3 this turn, which means Bob should save Cathy's 5

**Comment by unsoftcapped3** [comment]
(that was responding to your response to my comment)

**Comment by kesslermaximilian** [comment]
Ah yes, in this particular instance I agree. I thought you were referring to the general situation of the convention, so my argument was meant for a hypothetical situation where Bob is just finessed for y3 and the rest is the same.

**Comment by EhDrone** [comment]
In your hypothetical where Alice finesses Bob - it is an expert level of experience to know that a 2 save is not a reliable early-game clue. Alice could have the other copy, Bob could draw the other copy (like happens here). If Alice is choosing a line that risks Cathy discard a critical, then she is gambling. I don't think the additional overhead to analyze PTD which is already complicated makes sense, when from an expert perspective avoiding BDR and being risk averse is a natural sense and development in play. 

(Side note: It is really hard to use this hypothetical where Draku is being finessed in this game, because turn 2 is a UTD using a yellow 1 - and Draku's hand never changes before the proposed finesse occurs, so that finesse will have been available since the start of the game)

To keep it overall simpler, I at the moment am still in favor of this being a guide principle mistake where Alice chose a line to gamble instead of a safe line. The best clue in any given situation is not defined by how many cards it picks up, the best clue is analyzed per turn based on a number of factors. Finessing Bob and risking a 5 die is a bad clue that is more likely to work than not, but the 'not work' side is still there. In this game, there are 5 clues left in the bank, str8 could have chosen to give the 5 save, Draku could give a 2 save to Ramanujan, and then Ramanujan can give a 2 save to aspiring (All from str8's perspective). What would actually happen would be Draku would play y3 for free, Ramanujan would clue yellow to aspiring or str8, and everything is fine. 

I'll add here, I am often highly in favor of being cautious with early game PTD - and I agree in general that Cathy should look for PTD from both Alice and Bob before discarding, because Alice may be expecting Cathy save a 5 on Bob's chop in exchange for giving a good clue, only to have Cathy be super aggressive and discard because - while they do technically have PTD from Bob, discarding is still not a good choice when you can stall the early game a bit.

**Comment by Zamiell** [comment]
sounds like the consensus is to keep the doc the way it is, please correct me if i am wrong
