### ISSUE TITLE
New Convention: Globally Known Dupe Shout

### ISSUE THREAD

**Issue by purple-joe** [hanabi/hanabi.github.io#1123]
- If two copies of the same playable card are globally known in two different players’ hands, and either player discards the dupe instead of playing it, this triggers a Shout Discard Chop Move on the next player.
- This convention can also be used to Trash Order Chop Move if a player has additional trash cards in hand.

*this convention only applies for globally known dupes, and does not apply in sarcastic discard situations.

(credit to str8tsknacker)

**Comment by Zamiell** [comment]
looks like this hasn't gotten much discussion, so i will close it.

afaik this is not a convention already because it is too restrictive.
by not prescribing any special behavior, it allows the best player to always be the one to perform the discard and generate a clue, leading to the best possible line.
with this convention turned on, now we might not be able to take the best possible line, or might be forced to chop move a card when we don't necessarily want to
