### ISSUE TITLE
Delete Echo Scream Discard Chop Move (+ Maybe Delete Generation Discard)

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1138]
## Echo Scream Discard Chop Move Discussion

In general, my experience has been that the _Echo Scream Discard Chop Move_ is a terrible convention. (I invented it, so I take the blame, as per usual.)

Why is that? Well, in practice, disambiguating an _Echo Scream Discard Chop Move_ from a more-ordinary _Generation Discard_ is extremely difficult. Even with the best players in the world, the chances of everyone being completely synchronized after a _Echo Scream Discard Chop Move_ seems pitifully low. 

Part of the issue is that _Shout Discards_ did not exist when the _Echo Scream Discard Chop Move_ was invented, which adds an additional layer of complexity to consider. See [this question](https://discord.com/channels/140016142600241152/1179342435835457586) for a completely undefined situation in which there is no correct answer, which would likely lead to a lost game (since async on chop moved cards is terrible).

Even without the _Shout Discard_ complexity, the base move itself involves too much forward thinking. It's kind of like a multi-step math problem where if you make one tiny mistake on line 2, the mistake propagates forward and you end up getting the wrong answer on line 10. Another problem is that the move is asymmetric, such that it often involves retroactive-reasoning to compute what occurred. (Retroactive-reasoning is the worst kind of reasoning, leading to lost games.)

What would it look like if this move was deleted? If that was done, then discarding with a known play / a known trash would always cause the next person to be _Chop Moved_, and that's it. (With the exception of Generation Discards.) Then, we would "waste" additional clues to clue all of the other players, since the additional cards are no longer automatically _Chop Moved_. That seems like a fine price to me to pay in return for 100% certainty that everyone is fully synchronized.

Can someone link some games where _Echo Scream Discard Chop Moves_ happened, successful or otherwise? I am curious to play them out in a hypothetical to see if the "extra clue price" is enough to sway the game one way or the other.

<br>

## Generation Discard Discussion

When considering this issue, it also strikes me that the _Generation Discards_ are also asymmetric + must be retroactively computed. While not as terrible as _Echo Scream Discard Chop Moves_, _Generation Discards_ are ALSO a terrible convention and a common source of mistakes. Imagine the situation where:

- Both Bob and Cathy have critical cards on chop.
- Alice discards with a playable in-hand.
- Bob knows that it is a _Generation Discard_ for Cathy.
- But from Cathy's perspective, this is just a _Scream Discard_ for Bob.

This is terrible and you have to be a rocket scientist to disentangle this crap. It's interesting to also consider what things would look like if _Generation Discards_ were deleted as well, as a further streamlining to the conventions.

In that world, discarding with a known play / a known trash would ALWAYS cause the next person to be _Chop Moved_, with NO EXCEPTIONS. This would be **fully symmetric**, which is a fantastic property.

### Upside - Critical Cards get Automatically Chop Moved

The previous example shows the extreme upside of this arrangement. Bob would be automatically _Chop Moved_ (symmetrically). Then Bob would use the clue to save Cathy (symmetric).

### Downside - Trash Cards get Erroneously Chop Moved

The downside is the much-more-common case where Bob does not have a critical card, and instead has trash. In this situation, we get a trash card chop moved. However, this is generally fine, as it can stay chop moved until the end of the game. The other downside is if a critical card is next to the trash card, now the team has to save the critical card one round sooner, which is annoying.

### Neutral - Free CM on Useful Cards

Less commonly, the chop moved card will be neither critical nor trash. In other words, a useful one-away or two-away from playable card that can be used in the future. Getting free chop moves on these kinds of cards is good in some situations and bad in other situations, so this is more neutral on net.

### Conclusion

While deleting _Generating Discards_ is more radical than deleting _Echo Scream Discard Chop Move_, I believe it might be beneficial on-net, as it would remove an entire class of mistake.

**Comment by Zamiell** [comment]
### Example of Current Echo Scream

- The team has 0 clues.
- Alice discards with a known-play, brining the clue count to 1.
- Bob sees that Cathy has a critical. But Bob has a known play.
- Thus, Bob _Chop Moves_ and plays his card.
- Cathy _Chop Moves_ and discards her new, safe chop. (She could also clue, since she has a clue available.)

### Example of Deleted Echo Scream

(Same card configuration as previous example.)

- The team has 0 clues.
- Alice discards with a known-play, brining the clue count to 1.
- Bob sees that Cathy has a critical, so this is a _Generation Discard_.
- Bob clues Cathy's chop.
- Cathy discards her new, safe chop. (She cannot clue, since there are 0 clues available now.)

### Example of Deleted Echo Scream + Deleted Generation Discard

(Same card configuration as previous example.)

- The team has 0 clues.
- Alice discards with a known-play, brining the clue count to 1.
- Bob _Chop Moves_, since this is a _Scream Discard_.
- Bob clues Cathy's chop.
- Cathy discards her new, safe chop. (She cannot clue, since there are 0 clues available now.)

**Comment by David707x** [comment]
The way I'd personally want to clean this up is as follows:
 - Generational is ONLY legal when the next player can NOT scream, because they have no known playable cards
 - If you discard with a known play when the next player has a known play, it's always an echo scream that cm's the next two players.

**Comment by Egroegw** [comment]
Generally, I support the simplest option so long as there isn't too much of a performance hit. Here, we have conventions that both involve chop and async (i.e. potentially dangerous) and as Zamiell said, desync involving chop (and wrong focus) is often game-losing. 

I don't think chop moving trash is that bad, if we can remove an entire class of potential mistakes. Part of chop moving cards is to preserve them to reduce the risk of bottom deck losses, not necessarily so that they get played/blind-played. 

I think both Echo Screams and Generation Discards should be deleted.

**Comment by argothiel** [comment]
Echo Scream Discards are of similar complexity as any hat conventions. What is not possible to figure out are the Echo Shout Discards (as you can shout for any useful cards) and those should be removed.

**Comment by Egroegw** [comment]
If we want more people to join H-group, convention-wise 
- simpler is better
- less dangerous is better. 

Echo Screams, echo shouts, and generation discards are all complex and game-losing if someone errs ("very dangerous").

@argothiel Thanks for reminding me about echo shouts.

**Comment by Stuurrm** [comment]
Personally I would not like echos or generations to go away but I could be on board in removing echo shout discards.

**Comment by pianoblook** [comment]
I've never had trouble teaching Echo Screams in reviews; I feel like it's actually quite intuitive, and makes for a great lesson in how teams can really learn a lot from each other's seemingly disconnected actions. Like yeah it's 'complicated', but the reasoning is vitally important and (at least most of the time) understandable after a minute of reflection.

Also correct me if I'm wrong, but I wasn't really aware there was such a thing as an 'Echo *Shout*', since opting to discard kt instead of a play is far less shocking than an actual _Scream_. So if anything, perhaps you could just add a little section that says something like this very rough draft:

**"he Echo Shout Discard [Illegal]**
- Unlike Screams, Shout Discards can **not** cause _Echo Chop Moves_. This is because discarding known trash is infinitely less severe than intentionally discarding an unknown card, thus risking game loss.
- Thus, Alice opting to discard _kt_ instead of playing is always either a single _Shout CM_ or a (safe form of) _Generation Discard_.

^ Sorry if I'm a bit rusty here, but I'm pretty sure that sums up how I thought the conventions worked already. Like, to do an actual _Echo Scream_, Alice would first have to, well, Scream.

**Comment by hakha3** [comment]
Ive noticed in Zamiel's example there is point that

- Cathy also Chop Moves and discards her new, safe chop. (She could also clue, since she has a clue available.)

While in document regarding Echo scream discard it says

- Similar to a normal Scream Discard, all of the players who are Chop Moved are not allowed to discard on their next turn.

And I prefer Zamiel's option as I dont think there is much point to prevent Cathy from discarding when Bob could save extra cards.  (And also prefer echos and generations to stay)

**Comment by pianoblook** [comment]
I just realized, I bet this used to be clearer back when 'Whisper Discards' had a separate name than Screams - this specific situation may have just gotten lost in the shuffle.

**Comment by Zamiell** [comment]
I removed this line from the doc:

>  _Shout Discards_ can also turn into _Echo Shout Discards_, but only if the team is completely out of clues and it can be seen to be a "last-resort" move.

and added this:

### The Echo Shout Discard (Illegal)

- Unlike _Scream Discards_, _Shout Discards_ can not cause _Echo Chop Moves_. This is because discarding known trash is much less severe than intentionally discarding an unknown card (which would risk a game loss).
- Thus, a player discarding known trash card instead of playing is always either a single _Shout Discard Chop Move_ or a _Generation Discard_.
