### ISSUE TITLE
Change Stale 1's so that a chop 1 is good

### ISSUE THREAD

**Issue by David707x** [hanabi/hanabi.github.io#1145]
A game played at Level 16, but applicable to max level:
https://hanab.live/replay/1074700#13

Early game has ended and I clue 1s to sangik1saha. I argue that logically, the chop 1 is 'good' and the other is 'kt' due to the following two points:
Early game has ended, so clearly they aren't both good
If the chop 1 is bad, I can let it discard, then clue 1.

However, Level 12 stale 1's says: 'by convention, she knows that the oldest (right-most) 1 is bad, because that would be the one that she would ordinarily play first.'

If we play by this convention as written, it forces NewtS to bad touch the 1s before early game ends and forces a fix.

I'd like to see a convention change along the lines of:
'by convention, she knows that the oldest (right-most) 1 is bad, unless the oldest one is on chop, because that would be the one that she would ordinarily play first. If the oldest one is on chop, it is promised good as the team could let her discard it if it was bad.

**Comment by Zamiell** [comment]
as per the discussion on discord, i am against

**Comment by pianoblook** [comment]
> If we play by this convention as written, it forces NewtS to bad touch the 1s before early game ends and forces a fix.

The game you linked is perfect evidence for why we should encourage Newt to clue instead of discarding. The team is fine on clues, Newt sees trash on david's chop, and should be suspicious their chop is a 4. 

Any convention that encourages people to discard more aggressively than they already do would be a huge step backwards in the meta.
