### ISSUE TITLE
Early Saves / Potentially Delete LPC

### ISSUE THREAD

**Issue by Egroegw** [hanabi/hanabi.github.io#1150]
I was going to comment in #1132, but now it's closed and I'd like to discuss Loaded Play Clues and the Always Loaded Principle more generally.

Save clues are inherently worse than play clues. That's why we emphasize giving play clues over save clues in H-group. For example, the later you can save a 2 on chop the better, because in the meantime someone might draw the 1 of the same suit or the other copy of that 2.

The only reasons to give _Early Saves_ is to give the team more flexibility in choosing lines (_Discard Modulation_) and part of that flexibility comes from being able to extend the early game.

However, we have two almost identical concepts, Loaded Play Clues and the Always Loaded Principle, because in some variants we think _Early Saves_ to extend the early game are worth it, and in other variants we don't. 

Can we simplify things and have one principle which works both for hard (high-efficiency) variants and for variants where all clues to chop look like saves?

| Can early save... | Loaded Play Clues | Always Loaded Principle |
|--------|--------|--------|
| Early game | Yes | Only with a number 5 clue |
| Non-early game, low score |  Only with a number 5 clue | Only with a number 5 clue | 
| Non-early game, normal score | Never (!) | Only with a number 5 clue |
| During DDA | Yes | Unclear (!) |

**Comment by Zamiell** [comment]
the table is a bit more complicated than that, I think you should flesh it out with two more columns:
1) for normal/hard variants (since ALP applies to both kinds of variants, but LPC only applies to hard variants)
2) for suit type (since LPC applies to both suit types while ALP only applies to non-basic suits)

**Comment by Egroegw** [comment]
| Can early save... | Easy variant, no specials suits | Hard variant, no special suits | Easy variant, special suits | Hard variant, special suits
|--------|--------|--------|--------|--------|
| Early game | Yes | Yes | Only with a number 5 clue | Only with a number 5 clue* | 
| Non-early game, low score | Yes | Only with a number 5 clue | Only with a number 5 clue | Only with a number 5 clue |
| Non-early game, normal score | Yes | Never | Only with a number 5 clue | Never* |
| During DDA | Yes | Yes | Unclear | |

- Special suits mean games where any clue to chop looks like a save clue. (White isn't a special suit under this definition.)
- I assume that in "Hard variant, special suits" we take the more restrictive/play-clue-heavy out of "Easy variant, no specials suits" and "Hard variant, no special suits"

**Comment by Zamiell** [comment]
- Previously @pianoblook has been in favor of deleting LPC altogether, see: #1034
- If that were accomplished, then ALP would be unaffected, but we would not have the overlap that gw is mentioning in the OP.
- So then I think the most actionable thing to discuss is if we should delete LPC.

Pros of keeping LPC:

- Widely used convention for many years, will cause .
- Arguably useful in real games. The most common situation is e.g. early 2 save to give a 2-for-1 or 3-for-1 with tempo, which can allow extra efficiency when the color could would be 1-for-1.

Pros of deleting LPC:

- Confusing, prone to mistakes. Deleting it removes a lot of complexity, making games more straightforward (i.e. less exceptions to worry about).
- Increases discard modulation + reduces bottom deck risk.
  - Historically we have not cared much about this much since BDR game losses are less frequent than losing on efficiency.

Other points:

- LPC is confusing in that it is a convention which turns up the tempo dial, but only for hard variants. By definition, hard variants do not need more tempo, they need more efficiency. So LPC makes hard variants "easier", but in a weird-and-sort-of-orthogonal way that is counterintuitive.

**Comment by Egroegw** [comment]
What about deleting the Always Loaded Principle, keeping Loaded Play Clues in both hard variants and variants with special suits? Or keeping only LPC for both cases?

I think your Pros and Cons of deleting LPC assume that we wouldn't use the ALP instead in hard variants.

**Comment by Zamiell** [comment]
> keeping Loaded Play Clues in both hard variants and variants with special suits?

I don't think anyone wants LPC to be turned on in e.g. `White (6 Suit)`. It seems clearly suboptimal, which is why I proposed the other way around.

**Comment by David707x** [comment]
You say LPC only gives tempo, but it allows finesses on what would otherwise be an early save, so it gives efficiency too.

**Comment by Egroegw** [comment]
If you squint, the ALP and LPC differ only in whether early saves in the early game are allowed. Would it be useful to have one "convention" for both hard variants and special-suited variants, regardless of what we called it?

(Also, we can early 5-save in the "Non-early game, normal score" in an "Easy variant with special suits", but not in a "hard variant without special suits". We should probably fix this difference.)

**Comment by David707x** [comment]
Yes they should definitely be unified into one thing

**Comment by pianoblook** [comment]
I don't have much new to add - my stance is still very much anti-LPC in basically all contexts. But if it were up to me I'd also turn on 3 saves, and probably 4 saves in some cases.

Any convention that proposes to sacrifice discard quality (of Alice's chop, in this case) for tempo or efficiency needs a really strong case in my book. 'Simplicity' and 'clarity' are often two such examples of good justification, but I just don't see LPCs / ALPs making a good case, personally.

**Comment by Egroegw** [comment]
In hindsight, I should have titled this issue "Early Saves", because we're really just discussing when they should be allowed. (Currently we allow them all the time, only after middle game, or never, depending on the variant.) What if they were allowed only at certain pace? With enough clues?

@pianoblook I hope you don't mind if I take your position as supporting Early Saves any time. In that case, a playable brown card on chop will always require multiple clues to get: do you think that's a big loss?

**Comment by David707x** [comment]
I understand that on an efficiency 1.00 variant it's important to minimize BDR, but when personally when I am playing a variant that is solidly into 'hard' my concerns are far more about good clues and I'm more likely to discard if I can't see a good clue. I'd very much question that early saves are a useful tool in games that start with pace <= ~3.

**Comment by Zamiell** [comment]
> I hope you don't mind if I take your position as supporting Early Saves any time. In that case, a playable brown card on chop will always require multiple clues to get: do you think that's a big loss?

His position is to delete LPC, not delete ALP. Thus, by using ALP, a playable brown card on chop will require either 1 or 2 clues, depending on the presence of other playable cards in the hand (using ALP).

**Comment by pianoblook** [comment]
yeah Brown is a great exception, since they're a proven pain in the ass to differentiate. Variant-specific LPCs are totally fine in my book.

In general it's a common trap to get overly concerned over maximizing efficiency. Obviously there are going to be cases, certain 5p CS boards e.g., where you deem it best to risk a discard over a 1-for-1 2-save or w/e, but the same could be said about a play clue. And besides, if you're loaded in a 4p+ game it means your chop can likely be Discharged or Ejected anyway; point is, there are plenty of clever ways to get tempo&efficiency that don't rely on neutering the power of early game.

**Comment by Zamiell** [comment]
another data point:

![image](https://github.com/hanabi/hanabi.github.io/assets/5511220/263e15b4-e5af-4df2-870e-c3244c7a84d5)

in conclusion:

- it is difficult and/or impossible to unify LPC and ALP because they are used in different situations (e.g. white 6 suit has ALP on and LPC off, and e.g. black & brown 6 suit has ALP on and LPC on)
- there doesn't seem to be enough consensus to delete LPC
