### ISSUE TITLE
Convention Rework: Bring Back 1's Dupe Bluff

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#1158]
At some point the Rank 1's Dupe Bluff got changed to a Discharge, but I argue this is bad both logically and strategically.

1) Logically: slot 1 is all that's required to demonstrate the 1s clue is abnormal. The clued player will know exactly what happened after their first discard. This move is literally not covered under our logic of "Unknown Trash Discharge", which ~~always~~ otherwise only works because of Bob's realization that a slot 1 blind-play is _not sufficient_ to properly fix the signal.

2) Strategically:
a) Forcing rank and color to both get the same response is just unnecessarily hamstringing us. It was always lovely to have the choice of color for UDD, rank for Dupe Bluff.
b) Letting the 1s be temporarily marked as kt allows for TOCMs.
c) This arrangement would allow us to reinstate the _Junk Discharge_, which imo was pretty useful. As it stands now, it's pretty funny that Junk Charm is still a convention but Junk Discharge needed to get deleted. 
d) In general, we agree that getting slot 1 blind-plays tend to be more valuable than slot 3.

All in all, the whole thing is just inconsistent and bad.

**Comment by Zamiell** [comment]
- the *Bad Touch Finesse For 1s* was changed to UTD precisely because it made things more consistent - bad touches now always make slot 3 play.
- you are arguing that the core UTD algorithm of "only play 3 if slot 1 won't work" is violated when applied to the 1's bad touch finesse situation, which is true.
- however, instead of saying that it makes things "more inconsistent", it is more correct to say that it makes things "more consistent on one axis and less consistent on another axis".
- which axis is more important? my experience has been that less overall mistakes occur in pickup games with the current configuration, which i personally value higher than number of strategic options on hand.

> Forcing rank and color to both get the same response

currently, we can use both rank and color for both UTD and UDD.
thus, the argument of "i am unnecessarily hamstringed" seems surprising.
would you make the same argument for the normal case of UTD/UDD?
meaning that you think that its optimal to have two separate behaviors assigned to touching trash/dupes depending on rank/color?
i suspect no, which makes me not care as much about the 1's case, since I find value in the (current) symmetry

**Comment by argothiel** [comment]
If we allow it for 1s, why not allow it for other ranks, whenever the Trash Bluff on that number would be possible?

**Comment by pianoblook** [comment]
> If we allow it for 1s, why not allow it for other ranks, whenever the Trash Bluff on that number would be possible?

Well sometimes that just wouldn't work logically, since Cathy would just assume the focus was a good, 1-away card.

But if you mean in situations where all of that rank is playable  - e.g. a 3s clue when all the 2s are down - then yes I agree, slot 1 would be enough, and will resolve itself as soon as one copy gets discarded.

Stuff like that used to be a thing, too: #62  #140

**Comment by Zamiell** [comment]
yes, those moves predated UDD, and then they were deleted after UDD was implemented

**Comment by Zamiell** [comment]
i think the main takeaway of this issue is that different players find different things more intuitive.
i am reminded of this: <https://github.com/hanabi/hanabi.github.io/blob/main/misc/convention-styles.md>

**Comment by Zamiell** [comment]
looks like there is not enough support yet to undo the UDD changes
