### ISSUE TITLE
Clarification on Special Fives

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1164]
### The Pink Play Clue Lie (on 5's) (Illegal)

- This convention only applies to pink-fives & omni-fives
- First, see the section on the [_Pink Play Clue Lie_](pink.mdx#the-pink-play-clue-lie-ppcl-with-a-mismatched-play-clue-that-touches-other-cards).
- Even though it is not possible to clue number 5 in some special-fives variants, [_Pink Promise_](pink.mdx#pink-promise) still applies to the rank clues given. In other words, players are not expected to account for the possibility of a playable 5 when they receive a non-5 rank clue.
- Subsequently, if a player lies about the identity of a 5 with a _Pink Play Clue Lie_, it risks losing the game, since the receiving player might perform a _Gentleman's Discard_ (or be otherwise confused about the identity of the card in such a way that causes a cascading failure).
- For this reason, these kind of clues are only typically given as a last resort. (Color clues should be given instead in order to get a 5 to play.)
- In addition to _Pink Promise_ applying to rank clues on playable cards, it also applies to rank clues used on trash cards. In other words, a number 1 clue that indicates either a _Trash Chop Move_ or a play clue on a 5 would indicate the former.

### Rank Play Clues on 5s

- This convention only applies to light-pink-fives.
- Pink Promise does not apply to rank clues that could represent a playable 5. Thus, when players receive a rank _Play Clue_, they have to account for the possibility of it being the true rank and the possibility of it being a playable 5.
- For example, in a 3-player game:
  - Red 2 and blue 4 are played on the stacks.
  - Alice clues number 3 to Bob, touching a single card on slot 1.
  - Bob knows that this must be a _Play Clue_. Bob marks the card as either the red 3 or the blue 5.
 
(afaik this is the way that we have already been playing historically)

**Comment by gw12346** [comment]
Given that this is the way H-group already plays, I support this addition. 

However, what should we do with light-pink-fives, which can only be clued with a "false" rank?

- One way out might be to never clue fives until they can can be reclued after being incidentially touched, bluffed/ejected, or they reach chop (at which point they can be pseudo-2-saved).
- Another might be to say that since we can use a 2-clue to save 5s on chop, we should also be able to use a 2-clue to play clue a 5.
- Yet another would be to consider that one of the reasons behind having Pink Promise (i.e. without it, pink cards can never be told apart because all pink cards respond to the exact same clues) applies less to light-pink-fives, because as soon as you know a card is pink, you know it's a 5.

**Comment by Zamiell** [comment]
> what should we do with light-pink-fives, which can only be clued with a "false" rank?

all 3 of the variants i listed can only be clued with a false rank, right?

**Comment by gw12346** [comment]
Yes, but pink-fives and omni-fives can also be play clued with color.

**Comment by Zamiell** [comment]
oh, i see. so it is indeed a problem only for light-pink 5s.

iirc for light-pink 5s the convention doesn't apply, so i will edit the OP

**Comment by Zamiell** [comment]
edited it now

**Comment by gw12346** [comment]
Support.

Do we need to split the pink/light-pink/omni fives section into two then?

**Comment by Zamiell** [comment]
if this issue passes, yes

**Comment by David707x** [comment]
support
