### ISSUE TITLE
Move Charms (level 24) to level 16 (ejections/discharges) and Blaze Discards/Hesitation Blind-Plays to level 21 (advanced moves)

### ISSUE THREAD

**Issue by gw12346** [hanabi/hanabi.github.io#1184]
Charms could then be taught at the same time as other types of blind-plays.

**Comment by pianoblook** [comment]
It feels a bit rushed to introduce 4 Charms just one level after double bluffs.  Plus, bunching the E's and D's into one level is already a pretty big jump in complexity. Personally I like them being at a high level; 24 seems fine.

Blaze discards I would agree could probably move lower, since they always seem pretty intuitive to folks, and I've often seen lower level players do them cleanly. 

Hesitations are cursed af anyway so I wouldn't want to move those lower.

**Comment by Zamiell** [comment]
sounds like we should keep it the way it is for now
