### ISSUE TITLE
Changing NIDBs to NIDIs

### ISSUE THREAD

**Issue by gw12346** [hanabi/hanabi.github.io#1190]
> [11:50] \<Kyle>  I think if someone submitted a PR to change NIDB to NIDI, it might go through
> [11:50] \<newsun>  Most double bluffs could just be ignitions

During the post-game discussion of https://hanab.live/replay/1133180#36, we briefly discussed changing NIDBs to NIDIs. Thoughts?

**Comment by iamwhoiamhahaha** [comment]
I've already played in that way. So I approve it

**Comment by Stuurrm** [comment]
I believe by current conventions the clue given in the game is a legal single bluff. An extremely stupid one but legal nonetheless.

The problem with turning them into double ignitions are when it is a real finesse and when there is not enough information on the card. The example the doc gives about “The No-Information Double Finesse” would not work after this. Cathy would not wait for r2 but would ignite instead.


There exist other cases where this would interfere with finesses. Especially since the first ignition of double ignitions no longer have to be on Bob. All in all, the reason they are double bluffs and not ignitions is from where they come from. The blind playing players believe they are playing into a finesse and only after they blind play the truth is revealed.

**Comment by iamwhoiamhahaha** [comment]
I personally would call it an *Unnecessary No Info Bluff* rather than an *NIDI*. But *UNIB* works similarly to an *NIDI*, it's probably fine to call it an *NIDI*.

**Comment by Zamiell** [comment]
agree with Sturm, i think minimizing the complexity is optimal
