### ISSUE TITLE
Priority between Lower and Unknown playables

### ISSUE THREAD

**Issue by benzloeb** [hanabi/hanabi.github.io#1200]
This is a continuation of some of the discussion here:
[https://github.com/hanabi/hanabi.github.io/pull/1198#issuecomment-2073002529](https://github.com/hanabi/hanabi.github.io/pull/1198#issuecomment-2073002529)

Example: 
Stacks: b1, g1
Alice has known r1 and a playable nonred 2 in hand. 

Under the current conventions, Alice is supposed to play r1 because it is the lower card. I believe that we should change the priority order such that unknown cards have priority over lower cards. Here are the reasons why. 

1. Better synchronization of information. When Alice plays the 2, she learns which card we still need between g2 and b2. As long as she holds an unknown 2, she is only able to give certain finesses, severely hurting her ability to give clues. 
2. With the current priority rules, she can only make priority bluffs by playing out of order. With my proposed rules, she can make priority bluffs, finesses, or load clues. 

The only downside I see is approaching the endgame, it becomes more beneficial to have lower numbered cards in play, but that is the reason that in the endgame priority rules are "turned off".

**Comment by EhDrone** [comment]
To clarify one key points - Alice is not 'supposed' to play either card in this scenario currently. There is an explicit note in priority that playing an unknown card never causes priority. In the scenario above, Alice has the CHOICE to play red 1 or the unknown 2, and NEITHER will trigger priority because all the options for the 2 have lower priority under current conventions.

Note that if Cathy has b3/g3 clued in hand, then the 2 DOES have priority because both of the potential 2s would have prio over the red 1, and so playing the red 1 DOES still cause priority.

**Comment by EhDrone** [comment]
By the way just to add here - your example doesn't exactly track anyway because the 1, per the priority chart, has priority over every 2 so playing that red 1 would never cause priority regardless of how we change the specific 'Unknown Card' definition. The scenario you are actually looking for is when 'Left-most' vs 'Unknown' comes into play. In order for that to be the case, just use the example that triggered this:

Alice has a known red 2 and another card clued with a play clue as just '2'.
Stacks: r1, b1, y1.

In this scenario, all 2s have the same priority - so if all 2s were fully known, we would play left-most. However in this case, the right-most 2 is 'unknown', it could be blue 2 or yellow 2.

**Comment by EhDrone** [comment]
Then that's an additional misunderstanding of priority - the conventions intention is specifically your example:
Alice has a known red 1 in hand, and a play clue on a 2. Stacks are b1 / y1 / g1

Alice can play the unknown 2 before the red 1 and it will not cause priority.

**Comment by benzloeb** [comment]
What I don't understand is why these rules for priority is so lax? Priority only has value/power if it is followed strictly. I think the only play that should not cause priority plays is playing a card that not everyone knew was known to be playable.

**Comment by Zamiell** [comment]
re: expanding priority - strongly against for all the same reasons that i have been since the convention was invented

> Priority only has value/power if it is followed strictly

a common misconception about the h-group convention framework is that we optimize it for win rate / "value".
this is not the case!
we deliberately make the conventions have LESS value in order to minimize complexity, because it is not fun for people to have to follow strict rules all the time.
additionally, doing this kind of thing leads to lost games when people make a small, subtle mistake.
you DONT want to design a convention set that is strict, you want to design it that leaves room for flexibility so that players can make "good enough" moves without everything turning to shit at the slightest mistake

**Comment by benzloeb** [comment]
> they should be free to play the red 2 to allow us to get red 3 played THIS TURN

This is why a load clue exists. Priority is on the unknown 2, Alice plays r2 because she sees that we dont want to lose 3. She can play r2 to load clue. If she sees another r3 on the chop, she could even play the unknown 2 and not cause priority so that we lose r3 and make someone write elimination notes. 

I just don't see a situation on average that playing a known card is better than an unknown card.

**Comment by EhDrone** [comment]
Another example I gave in the original thread where a load clue doesn't apply:

Alice has known red 2, and unknown 2. Stacks are r1, b1, y1. The unknown 2 can be blue 2 or yellow 2. Alice looks around, and doesn't see useful blue or yellow cards that are not 5s. Alice looks around and does see a red 4 in someone's hand. In this case, playing either blue 2 or yellow 2 are meaningless - neither even potentially lead into anyones hand. However the red 2 could lead into the red 4 being played sooner if red 3 is drawn. Sure the unknown 2 could draw its equivalent 3, but is still less valuable because only the red 3 leads into another card currently present. 

In this specific scenario, I maintain that the value of knowing which 2 is the unknown 2 adds no value really to the game overall, but getting possible tempo on the red suit when you might otherwise risk losing or maybe drawing blockers to bad touch the red 4 has inherent value.

Is your argument that even in this case, where the unknown 2 has no existing benefit to be played other than its unknown, it is still better to play the unknown 2 over the red 2, which could allow additional tempo on r3 and therefore r4?

**Comment by EhDrone** [comment]
Clue starved has an inherently high required efficiency, of which can necessitate additional context and sensitivity. Even with that being said - it sounds like your group may have been using priority somewhat wrong anyway (with respect to prio from a known 1 playing before an unknown '2'). If this type of prio is commonly causing clue starved games to be lost, it could certainly open space for variant specific conventions, but clue starved behavior is not an ideal use case for changing conventions in other variants, which the conventions are primarily written for (No Variant, Rainbow).

**Comment by benzloeb** [comment]
We have been playing with unknown having higher priority than lower cards for a long time now, originally due to a misreading of the conventions. I do believe our way is more efficient, but that efficiency is certainly not needed in No Variant. I have a lot of changes that I would add to the clue starved specific conventions. Some of these changes are ones we've played with throughout the entire league.

**Comment by argothiel** [comment]
> Is your argument that even in this case, where the unknown 2 has no existing benefit to be played other than its unknown, it is still better to play the unknown 2 over the red 2, which could allow additional tempo on r3 and therefore r4?

With the current doc, if no-one has r3, then playing r2 would cause a prio play. That's because playing an unknown card has a higher priority than the known one (if they have the same rank).

**Comment by EhDrone** [comment]
For any that missed some of the original discussion - argo what you stated is not true. If you look at the flow-chart specifically made to identify priority when one or more of the cards is unknown, it clearly shows that it is not the case unless the unknown card has priority over the known card in all cases:
https://raw.githubusercontent.com/hanabi/hanabi.github.io/main/static/img/flowcharts/priority-unknown-flowchart.png

Hence why I created the PR to update the doc to properly reflect what the convention is for.

**Comment by pianoblook** [comment]
I haven't read through every corner of this discussion, but just wanted to chime in to say that blind-playing in response to Alice choosing to play a 2 in this sort of situation is just a wild way to play Hanabi, and I hope is not at all conventional.

**Comment by Zamiell** [comment]
> I hope is not at all conventional

it is not conventional, thus this propositional issue

**Comment by argothiel** [comment]
> If you look at the flow-chart specifically made to identify priority when one or more of the cards is unknown, it clearly shows that it is not the case unless the unknown card has priority over the known card in all cases

But this flowchart has been created in 2019, before explicitly including the "Unknown card" in the priority table:
https://github.com/hanabi/hanabi.github.io/commit/aca79606a1367071cff07a8ebeb56cbacfe7b036

If playing a known card over an unknown card (neither leading to anyone's hand, neither is a 5, and both are the same rank) does not trigger a priority, then why the "Unknown card" has been explicitly included in the priority table at all?

![image](https://github.com/hanabi/hanabi.github.io/assets/13932353/8237496d-e55f-4a9e-bad4-1d897463d665)

**Comment by EhDrone** [comment]
This section was written during the whole doc overhaul and is supposed to summarize the flowchart essentially into a chart for people to reference. It unfortunately missed capturing the nuance of the Unknown Card priority that required the analysis of what the unknown card can be - hence the PR that is submitted to rectify that gap

**Comment by argothiel** [comment]
Okay, I've read the entire discussion now (sorry it's that late). I believe that if an unknown card has a priority over a known one only if it potentially meats conditions 1-5, then it should be removed from the priority table at all and have its own mentioning separately. It's not that the card is unknown which triggers priority, and it's not that "gaining information about your own hand" triggers priority, it's that the card potentially meets one of the higher importance conditions.

By the way, I've been playing with unknown > known till now, for the exact reason which is in the doc: "Gaining information about your own hand is valuable".

**Comment by iamwhoiamhahaha** [comment]
To clarify, I added the 6th bullet point to address the issue that arises when two cards with the same rank are present, with the known card on the left and the unknown card on the right. Playing the unknown card does not trigger a priority in this scenario. The situation involving a known card and an unknown card with a higher rank remains undefined, I believe. In my experience, players often hesitate to play the unknown card with a higher rank, fearing they might accidentally trigger a priority. As a bold player myself, I would personally interpret it as a priority because I typically trust that the player possesses enough context or information (such as seeing the cards in my hand) to know which card they are playing. However, I also acknowledge that there are situations where playing an unknown card with a higher rank holds more value than playing a known card with a lower rank, and in such cases, it should not trigger a priority.

**Comment by iamwhoiamhahaha** [comment]
> it should be removed from the priority table entirely and have its own mentioning separately

Yeah having a separate section for unknown cards would provide clarity and ensure that their handling is distinct from the priority table. It would help in addressing concerns and avoiding ambiguity during gameplay.

**Comment by argothiel** [comment]
So, what we're trying to say here is that "Priority Finesse/Bluff" only applies for conditions 1-5, and not for the condition 7. I say after creating a separate section for unknown cards, let's drop all the the contradictory (and false) statements like "Playing an unknown card never triggers a priority" from the rest of the level.

**Comment by EhDrone** [comment]
> I would personally interpret it as a priority because I typically trust that the player possesses enough context or information (such as seeing the cards in my hand) to know which card they are playing.

While I appreciate how deep you get in games JEFF, I hesitate to think a read / move you personally would do should be codified as conventional. I know you often make bold and sometimes incredible reads, but always assuming a player played an unknown 3 over a known 2 and playing prio because you assume they see something in your hand that makes it known just seems way too prone to mistakes unless everyone in the game is named IAMJEFF as well. 

> "Playing an unknown card never triggers a priority"

This is still a valid statement, I am not entirely sure where you think it is not true outside of JEFF stating he personally would play from it. If a player has a known yellow 2, and an unknown 3 (with, say, red 2 blue 2 on stacks), playing that 3 is never a priority bluff (or in this case a 'known' priority bluff). As we've said in many cases, context can override conventions at any time, but defining and dictating the context as to when an unknown card *should* cause a priority is way too nuanced for anyone to consistently and accurately analyze. JEFF has on occasion blind played finesse because "X clue was given on turn 1 instead of Y clue" and been right, but I would predict he has been wrong a number of times in that attempt as well - but the high from hitting is so good those ones stick around. I would be highly hesitant to say everyone should start playing like JEFF does because - again - he is incredibly adept at reading into situations and often being right which is an incredibly difficult skill I would not want to rely on everyone on my team having to the degree that JEFF does.

> To clarify, I added the 6th bullet point to address the issue that arises when two cards with the same rank are present, with the known card on the left and the unknown card on the right. Playing the unknown card does not trigger a priority in this scenario.

I feel like this is missing the mark of the discussion? The whole thread is not about playing the unknown card over the known card but the exact opposite - playing a known card over an unknown card as demonstrated in the examples shared throughout. The flow-chart clearly states the criteria for when playing a known card causes prio over an unknown card (playing the unknown will never cause a prio conventionally regardless of what it is).

**Comment by argothiel** [comment]
> I am not entirely sure where you think it is not true
> playing the unknown will never cause a prio conventionally regardless of what it is

Because the Trust Finesse/the Trust Bluff invalidates this statement.

If a player has a known card leading to someone else's hand, but plays an unknown card (which for sure doesn't lead to any clued card) over that, this causes a Finesse/Bluff.
If a player has a known card leading to their own hand, but plays an unknown card (which for sure doesn't lead to any clued card) over that, this causes a Finesse/Bluff.
If a player has a known 5, but plays an unknown card (which for sure doesn't lead to any clued card) over that, this causes a Finesse/Bluff (?)
If a player has a known lower rank card, but plays an unknown card (which for sure doesn't lead to any clued card) over that, this causes a Finesse/Bluff (?) -> that's how Jeff plays, I believe.

**Comment by EhDrone** [comment]
You a re right - the trust finesse is the defined "context can overwrite convention" section. Its basically what JEFF is saying just not to his extreme - he just always assumes the player knows what the unknown card is. The example in the doc would be different if y3 is sitting on Cathy's finesse, because Bob can see that Alice may trying to play yellow 2 to allow y3 to be finessed. Note that 'really dumb' is subjective, and I would argue in-game probably always that Alice playing the blue 2 in the Trust Finesse example is not "really dumb" if Cathy is holding yellow 3 on finesse. I would also claim that a lot of people would play their unknown '2' if they see the potential connecting cards in others' hands regardless.

You gave a bunch of scenarios, but the key point in all of them is:

> plays an unknown card (which for sure doesn't lead to any clued card) over it, this causes a Finesse/Bluff (?)

I would amend it to: plays an unknown card (which for sure doesn't lead to any possible efficiency or tempo benefit) over it, this causes a Finesse/Bluff.

The reason for the modification of your phrase is my "y3 on finesse" example above, which could extend to multiple other scenarios where maybe the team is low on clues and y3 is on Cathy's chop - or maybe y3 is sitting behind a critical card in Cathy's chop and there is some risk we will be in a bad spot if we don't get it played now.

In either case - this is a total side discussion from what this is all about regarding an unknown card playing vs a known card in the general sense.

**Comment by iamwhoiamhahaha** [comment]
> I feel like this is missing the mark of the discussion?

Oh, I was trying to point out why the 6th bullet point was established. It is mainly to address the situation when *"playing an unknown card (rightmost) over playing a known card with the **same** rank (leftmost)"*. In this specific situation, it does **not** trigger a priority.
It is not designed to address situations involving cards of different ranks. Personally, I would interpret a priority if the player plays a card with a higher rank. However, I believe it is undefined, and I think it's valuable to play an unknown card with a higher rank sometimes. This is why I mentioned there should be a separate section for unknown cards.

**Comment by Zamiell** [comment]
i updated the doc today with a new section of "Priority with Unknown Cards (Clarification)", which accurately represents how we have historically played.
you can review it to see if you agree with it.

since about half of the people in this thread seem to be against expanding priority to include more priority finesses, i will close this issue for now.

**Comment by NZadeh** [comment]
> i updated the doc today with a new section of "Priority with Unknown Cards (Clarification)", which accurately represents how we have historically played.

I see the doc now says:

""" https://hanabi.github.io/level-20/#priority-with-unknown-cards-clarification
In the above priority table, "unknown card" is listed below most things. However, it is important to understand that playing an unknown card does not trigger a Priority Prompt / Priority Finesse inherently by being unknown. In order for those moves to trigger, all possible cards in the unknown superposition must have priority over the card that was not played.
"""

I'm not sure I follow the clarification. It seems like the section is to clarify when playing an unknown card could cause a priority finesse:

"""
...  However, it is important to understand that playing an unknown card does not trigger a Priority Prompt / Priority Finesse inherently by being unknown. In order for those moves to trigger, ...
"""

However, the examples go on to discuss playing a globally known card over the unknown card.

The examples also seem to suggest that a known r2 playing over an m1/b3 would not cause a priority finesse [1]; which I don't think is the conventional interpretation?

[1] because not all cards in the superposition have priority over r2.
