### ISSUE TITLE
The Priority with Unknown Cards section remains confusing and inaccurate

### ISSUE THREAD

**Issue by english5040** [hanabi/hanabi.github.io#1212]
Alice didn't even play an unknown card in the example, so the description of this section doesn't even make sense. In addition the example is inaccurate because unknown cards have priority over leftmost (criterion 6) if they're tied in all criteria above 6.

**Comment by english5040** [comment]
making a pr

**Comment by Zamiell** [comment]
should i close this now?

**Comment by Zamiell** [comment]
also i removed [this flowchart](https://raw.githubusercontent.com/hanabi/hanabi.github.io/main/static/img/flowcharts/priority-unknown-flowchart.png) from the doc just now since it fails to capture the following scenario:

- Alice has a globally known red 4 clued in her hand.
- Alice has a `blue 2, green 2`  clued in her hand.
- Bob has a globally known red 5 clued in his hand.

Here, Alice is expected to play the red 4 into the red 5. Thus, the rule of "playing unknown cards never cause a Priority Finesse" doesn't actually apply here. I don't really feel like updating the flowchart, so I'll delete it for now, if someone wants to recreate it then go for it.

**Comment by Zamiell** [comment]
(the situation i sketch in my previous comment above is actually just a repeat of the example that is already in the doc under Trust Finesse).

for reference the deleted flowchart is here: https://github.com/hanabi/hanabi.github.io/blob/3b312e95131c1c130fd885d3e31982b131cddfc1/static/img/flowcharts/priority-unknown-flowchart.png

**Comment by english5040** [comment]
yeah I'm closing it. I'll make another issue if I want to discuss adding "unknown identity" as a part of the table.

I am of the opinion that priority was so confusing, we should just stick with the current convention, hopefully the PR'd priority table should really cut down on confusion

**Comment by Zamiell** [comment]
> I am of the opinion that priority was so confusing

yes priority is basically the worst convention that we have, whoever invented it is an idiot
