### ISSUE TITLE
Convention Proposal: The Junk Blast

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#399]
**EDITED 2/23/21 to make this a _BLAST_, now that #487 has been proposed & accepted**

~Just like the Safety Charm, this is another Charm that fits nicely under the category of "direct play clue that very intentionally suck".~

### The Junk ~Charm~ Blast

- If a player can cleanly touch a playable card without violating _Good Touch_, it would be very strange if they choose to clue it in such a way that picks up extra _Unknown Trash_. When this happens, they must be sending an extra message to the team.
- ~In some cases, this should be treated as a [Weak Form Trash Finesse](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-trash-finesse-weak-form), even if it's done in reverse~
- ~But, what if the next player sees that they would need to have **two or more blind-plays** in order to correctly clarify the intentional Bad Touch?~
- ~If so, this must be calling for an immediate blind-play of some kind...~
- The only _Finesse Position_ that would not be misconstrued as something else must be a ~_Charm_~ ***Blast***
> ~Note how this stays consistent with the idea of _Signal Shifting_: an Ejection would contradict 5CE (Play --> Save), a Discharge would look like a UTD (Play --> Trash), so a Charm correctly keeps the focus as a Play Clue (Play  --> Play)~

<img width="1136" alt="Screen Shot 2020-10-30 at 10 14 45 AM" src="https://user-images.githubusercontent.com/32303453/97715603-fc966d00-1a98-11eb-9994-280eb9869d8b.png">

(Hypothetical) Example:

- pianoblook's red clue is a true Play Clue on r2, but he also has intentionally picked up _Unknown Trash_
- fishcat realizes it would be absurd for this to trigger a _Weak Form Trash Finesse_ on r3, r4, and r5
- fishcat needs to blind-play a card that would not confuse ADrone
- slot 1 would make it look like a _Bluff_ on r3.. Slot 2 looks like a _5CE_ on r5. Slot 3 looks like _UTD_ on r1. ~Slot 4~ Slot 5 uniquely works, and lets ADrone know his ancillary card(s) are garbage.

**Comment by Zamiell** [comment]
seems fine

**Comment by pianoblook** [comment]
What are your thoughts on allowing this with 1s? Normally if someone blind-plays in response to a 1s clue, it promises those cards as trash. 

That seems cool in some situations, but I could definitely see it leading to bombs when there should be enough context that the older 1(s) are clearly stale and someone misinterprets it as a Charm.

**Comment by florian-5f3759df** [comment]
Currently that case is kind of covered by [The Bad Touch Finesse (For 1's)](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-bad-touch-finesse-for-1s). If this is introduced, I would be happy with removing that part and just include 1 clues as a possibility of this charm. With the warning that it almost never works, since we expect a bunch of context reads on 1s (like stale 1s, or sometimes the other 1s are possibly already gotten without that being globally known, etc). But the bad touch finesse for 1s is even more rare, because it conflicts with the implied bad touch of trash bluffs, so at least this charm is applicable for a few more turns.

**Comment by Zamiell** [comment]
conflicts with https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#trash-touch-elimination

**Comment by pianoblook** [comment]
> When this occurs and there is exactly one "missing" card, players should write an Elimination Note in their hand for the missing card. This is called Trash Touch Elimination.

Yeah this def shouldn't work if there's just one 'missing' card left, and it's therefore safe to assume that it must just be known trash based on one's own hand. 

I figured this would only be allowed when 2+ (untouched/blind) cards of that type remain. I suppose this would still conflict with exactly a "_Reverse Bad Touch Finesse (Weak Form)_", but does that ever actually happen? The Charm interpretation allows for the blind-play to resolve immediately + to be able to get any unrelated card

**Comment by Zamiell** [comment]
https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-trash-finesse-weak-form

> does that ever actually happen

yes, we do trash finesses occasionally

**Comment by Zamiell** [comment]
we don't do weak form trash finesse very often but then again i don't foresee myself doing a junk charm very often either

**Comment by pianoblook** [comment]
Sounds like this is in direct conflict with the existing Reverse Weak Form Trash Finesse. This feels simpler, as it doesn't rely on a round of async information, but I'm happy to close this

**Comment by Zamiell** [comment]
im happy to delete weak form trash finesse, but it would be nice for someone to demonstrate 3+ examples of this working in a real game, as a protection against:
1) this being added to the convention docs
2) noone doing the move for 1-2 years
3) this being deleted from the conventions doc to remove complexity / total moves
that cycle just wastes everybody's time

**Comment by pianoblook** [comment]
Just for sake of discussion, here's my final pitch for why this seems more intuitive. Admittedly these two points are most prominent in 3player specifically:

1. It feels pretty strange to do a RWFTF with color on Bob, because in most cases why not just (a) clue bob's card directly or (b) let bob bluff the 2 and then bluff the 3
2. Especially in 3p, it's kind of awkward desync for a round (e.g. Alice can't clue Cathy the next round because it would muddy the interpretation of the follow-up blindplay)

**Comment by pianoblook** [comment]
Yeah I'll try to find some examples, of both this and Weak Form. They both seem cool, and I genuinely don't know which is more useful. My gut says one of the two following things would seem cleanest(using the red example from above):

1. limit JC to cases in which the r2 is on Finesse Position (because if Alice is actually trying to get r2+r3, it would usually be much simpler to just get the pair with finesses: either with a direct play clue on r3 or with two separate bluffs)
2. limit WFTF to 'forward' instances (as in, the connecting r3 downstream of the clued player; so like red is clued to Bob, r2 plays, and r3 immediately plays and thus resolves the situation). This makes sense to me because in the reverse case, in most situations you'd probably be just as well off giving a normal play clue to the r2 and then bluffing the r3 from Bob on the next go around.

**Comment by Zamiell** [comment]
to clarify, my conception of this proposal is that all WFTF are deleted.
having it be WFTF half the time and junk charm the other half of the time sounds terrible.

so the algorithm is:
- 1 card left --> trash toush elim
- 2+ cards left --> always junk charm

the downside here is that bad players will think that a junk charm is happening whenever we need to dupe a card.
so it only applies when you have free choice between rank and color, and one option would dupe a card and the other does not

**Comment by pianoblook** [comment]
Yeah, I think that condition applies for WFTF too though right? either of these should only trigger if there was free choice and therefore the badtouch is intentional

**Comment by Zamiell** [comment]
yes. the (small) difference is that no-one knows that WTFT exists, and when i announce junk charm, everyone will know that it exists = )

**Comment by Jayhui-q** [comment]
I really like extending this notion of "direct play clue that very intentionally suck" -> charm! I wonder if this is codified if it can be extended to saves that intentionally bad touch unknown trash.

However, I personally am a little hesitant about this convention. Codifying this makes me worry about moments where intentionally touching trash can be wise. In particular, for moving finesse positions, focus, or when a clue clarifies the trash, rather than through blind-plays. 

For example, in the below, I (from fishcat) personally would strongly consider giving 2 to Piano even though red could avoid the bad touch because it puts y1 on finesse, and will be cleared up when a blue save is given to Piano (either by ADrone or fishcat, and protects the critical for another turn with known trash.)

This applies in other scenarios, such as if b5 was on s3, and a blue 5CE could now be done. Or if there was a green 4 in hand and neither a 4 or blue could cleanly save b4. 

The value of such a decision could also be asymmetric (looks like a "sucky" clue to ADrone only) such as a 5CE instance or a finesse that uses ADrone's hand. The potential asymmetry of it worries me the most because it may be possible that you can't just context your way to see how "sucky" the bad touch was.

![image](https://user-images.githubusercontent.com/55895573/102724988-16a23e00-42d9-11eb-8675-b36a78adbb37.png)

**Comment by alyvan** [comment]
The biggest advantage I see is most likely to be used in 3P where there is usually 1 round of desync with WFTF that would be eliminated in that the charm would resolve immediately. To Jerry’s point, this only works if it is universally, unequivocally a suboptimal clue with no potential for a good explanation for why the bad touch was valuable. I’ve never encountered a WFTF situation, so I’m inclined to say ratifying the charm holds little risk with eliminating valuable clue opportunities around WFTF.

**Comment by pianoblook** [comment]
Neat in-game example I just spotted: all three options are available! (normal reverse finesse, RWFTF, Junk Charm)

But there's only one clue left, so this would be a good example of when the immediate resolution of JC is an obvious benefit


h="1189" alt="Screen Shot 2020-12-20 at 8 36 15 PM" src="https://user-images.githubusercontent.com/32303453/102730630-4cf4b300-4303-11eb-8cb5-e79ee7df49f3.png">

**Comment by pianoblook** [comment]
Uploading as a counter-example: even though *teeeechnically* you could say this should be a Reverse Charm (and it would work here, by chance), I think that is a lot less intuitive.

The whole point of why Bob would need to Charm (if we do decide on going with an immediate blind-play being called for) is that playing slot 1 would ruin the initial Signal. Once the focus is successfully played, though, (or at least given the free opportunity to play), then I see zero reason as to why this should be assumed as a Charm and not just a blind-play (WFTF). 

So actually in this example as Cathy I would discard and trust that Donald would blind-play his finesse as a true 3

<img width="1190" alt="Screen Shot 2020-12-20 at 8 55 37 PM" src="https://user-images.githubusercontent.com/32303453/102732063-a828a480-4307-11eb-8a2e-27d228b7c387.png">

**Comment by pianoblook** [comment]
> Codifying this makes me worry about moments where intentionally touching trash can be wise. In particular, for moving finesse positions, focus, or when a clue clarifies the trash, rather than through blind-plays.

yep, that would definitely be a tradeoff. Personally I think it's a worthwhile tradeoff though: for one thing, it's efficient which is always a big plus :P (both of these - JC + WFTF - are inherent 2 for 1). 

Also, although I agree that the existence of either of these conventions could 'stomp' on some nice longer-term line you would hope to be able to construct, I bet I could find a decently equivalent number of hypotheticals in which the addition to this sort of tool might actually *help* set up other long-term benefits as well!

**Comment by Jayhui-q** [comment]
Interesting. At least to me, once a clue is given to clarify the trash, it's clear that it wasn't a WFTF. In the example above, the clue-giver has a chance to clarify and demonstrate why unknown trash was included. If we have the Junk Charm, ADrone has to decide what to do first before fishcat can clarify. 

I tend to agree with your bet though (especially with the 2 stipulations you put above about 1. JC if the focus is on finesse, 2. WFTF forward). A bunch of examples of where my above cases would be poor is if Piano would've seen a great clue to give but doesn't know if he could be duping himself -- it would be of huge value to resolve immediately (and fishcat doesn't know about this amazing clue).

I personally don’t think this decision tree is too complicated, as it would just mean that you can't junk charm out of position. Otherwise, it's a WFTF.

**Comment by pianoblook** [comment]
I think that immediacy (whether from an instant _Charm_ or forward _WF Finesse_) is actually a big benefit when it comes to all this, which follows directly from the [Lie Principle](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#8-lie-principle). Honestly a Reverse WFTF feels more like a borderline _Lie_ more than a _Fib_, since it takes a whole round to fully resolve.

Your example of the subsequent fill-in clue that fixes the known trash is great. Yeah, like then how does Cathy interpret the blind-play next round, after the subsequent clue? Or like you said, *should* Bob even still have to blind-play? Needing to worry about all those extra contextual considerations feels like a big brain-drain and evidence of a dangerous convention.

**Comment by pianoblook** [comment]
Closing this: I've settled that piper's trash Charm idea - which directly conflicts with this one - is going to be much more beneficial overall.

**Comment by Zamiell** [comment]
link it

**Comment by pianoblook** [comment]
@Zamiell I'm reopening this proposal as a _Blast_

Everything should be edited above to reflect. Now that Weak Form Trash Finesse is out & UTC is in, this still works cleanly as a _Blast_.


Basically, 
Slot 1 = Bluff
Slot 2 = Eject
Slot 3 = UTD (w/ good touch)
Slot 4 = UTC (both trash)
Slot 5 = unique

**Comment by Zamiell** [comment]
1) situations in which you can unambiguously use *Free Choice* to intentionally dupe cards with no other complicating factors seems to be rare
2) blasts do not seem very useful outside of brown variants

post many examples to convince me otherwise

**Comment by Zamiell** [comment]
also this probably belongs in a new issue
