### ISSUE TITLE
The Cursed Finesse

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#437]
Everyone is attuned to looking out for double+ finesses to perform, so I think it's safe to assume that it's not a very common mistake to accidentally make it a hard 3-bluff instead when both choices are available.

This is a very similar concept to the [Inverted Priority Finesse](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#inverted-priority-finesse), so I borrowed a lot of the language here

I also suspect there might be other examples of *Cursed Bluffs*, I'll keep my eyes out. 

### The Cursed Bluff ###
- If a player performs a *Bluff* when they could have instead freely initiated a true *Double* and/or *Layered Finesse* by cluing the same card in a different manner, they must be trying to communicate something extra.
- They are instead performing a *Cursed Bluff*. The following player is also being called to blind-play.
- After this extra blind-play occurs, the presence of the original *Double* (or *Layered*) *Finesse* is now known to everyone on the team. Thus, the normal *Finesse* is preserved and should be played into on the next go-around of the table.
- Note that this only should occur if there was *Free Choice* in the initial clue. If cluing rank good-touched additional cards or cluing color would have bad-touched card(s), then no extra blind-plays should occur.

***Example 1: Hard 3-Bluff***
> Turn 1, 4 player
> Bob's hand is [g1 g2 r3 b4]
> Donald's hand is [b5 p2 y1 g3]
- Alice clues '3' to Donald's g3
- Bob blind-plays g1, but now just assumes this was a normal *Hard 3 Bluff*
- Normally this would just be a *Hard 3 Bluff*, but Cathy knows this is very strange: she sees that Alice could have cleanly clued the g3 with color in order to make it a true *Double Finesse*.
- Therefore, Cathy blind-plays.
- Bob and Donald now realize this must have been *Cursed*: Donald marks his 3 as exactly g3, and Bob marks his slot 2 for a finesse on g2.

***Example 2: Color-Choice Bluff***
> Turn 1, 4 player
> Bob's hand is y1 g1 r3 b4
> Donald's hand is [b5 p3 y1 g2]
- Alice clues 'green' to a g2 in Donald's hand
- Bob blind-plays y1, but now just assumes this was a normal *Single Bluff*
- Cathy sees that Alice could have cleanly given rank to Donald's 2 instead, as a *Clandestine Finesse*
- Therefore, Cathy blind-plays
- Bob and Donald now realize this must have been *Cursed*: Donald marks his green card as exactly g2, and Bob marks his slot 2 for a continued *Finesse* on g1

**Comment by pianoblook** [comment]
I'll troll around for examples. Here's one from a current game (just pretend the 1 clue was the correct 'yellow' clue instead)

<img width="1190" alt="Screen Shot 2020-12-16 at 2 00 44 PM" src="https://user-images.githubusercontent.com/32303453/102394109-4256b880-3fa7-11eb-8f9e-ffcb297d59f9.png">

**Comment by iamwhoiamhahaha** [comment]
seems fine. but the problem of this convention is if bob defers playing into the bluff and performs a finesse on cathy then he won't know he's cursed

**Comment by pianoblook** [comment]
Huh I guess this is actually a "Finesse" as well at its core - the extra blind-plays make it specifically *NOT* a Bluff, lol

I suggest we merge this and the second half of #438

**Comment by pianoblook** [comment]
<img width="1190" alt="Screen Shot 2020-12-20 at 1 20 44 PM" src="https://user-images.githubusercontent.com/32303453/102721047-39772700-42c6-11eb-975b-e1c422204367.png">

> frosty clues p, getting a single bluff
> sweety sees this could have cleanly been a clandestine, and therefore plays as well
> katian might think this is perhaps a p4 double bluff, but no: if it was indeed p4, sweety would not have blind-played immediately, since they should have assumed they have p2+3 as a true finesse

**Comment by pianoblook** [comment]
T1 from this game ([(https://hanab.live/replay/385374#1)]). 
- In-game they opened with 2 to oruc as a true Clandestine
-O pening with blue instead would now be a _Cursed Bluff_: Helena would have no reason to keep blind-playing after the first blind-play doesn't match
- therefore eljavi would blind-play too

<img width="1259" alt="Screen Shot 2020-12-28 at 5 28 09 PM" src="https://user-images.githubusercontent.com/32303453/103246595-0ff77480-4932-11eb-8d26-5dc5f5f7f523.png">

**Comment by Zamiell** [comment]
no 6-player examples

**Comment by Jayhui-q** [comment]
I'm a little hesitant on this convention --
In your example, with p2 clued as the cursed bluff, 

Should sweety still blind-play if there's a p1 someone else's hand (not on finesse)? I see some value that could be lost with this convention, regarding the distribution of the connecting cards.

That is, I do see value in intentionally declining a 3-for-1 finesse for a 4/5-for-2 later on.

For example, in the previously mentioned example, Sweety's hand has a y5 on slot 1 and p1 on slot 2 (for a future 5 pull option).

> Note that this only should occur if there was Free Choice in the initial clue. If cluing rank good-touched additional cards or cluing color would have bad-touched card(s), then no extra blind-plays should occur.

Good addendum here. Makes it so bad touch 3 doubles and bad touch 4 doubles don't conflict.

**Comment by Zamiell** [comment]
is this independent of #438? if #438 was closed, should this be closed too?

**Comment by pianoblook** [comment]
> is this independent of #438? if #438 was closed, should this be closed too?

I believe these are actually quite different. That version was 
- The Cursed 'Finesse' version operated off of assuming Bob should play into the clue *only because* of a very weird marginal read that Alice chose rank over color. For the record, I agree that seems too rare and unintuitive of a convention. Bob just wouldn't blind-play at all except for if this convention existed, which feels...easily missed.

- This version, though, is just initiating a normal *Bluff* on Bob, but that then Cathy can see is an obvious passed up opportunity to do a true _Clandestine_ / _Layered_ finesse. 

The resulting 'extra' blind-play from Cathy is therefore a demonstration to Bob that his initial blind-play, which just looked like a normal *Bluff*, should actually be promised as a true finesse.

I think this version feels a lot more natural and easy to notice. I think the first few lines of this proposal lays out why:

> It's not a very common mistake to accidentally [perform a single bluff when the opportunity for a clean Layered or Clandestine finesse was possible] [...] 

> This is a very similar concept to the Inverted Priority Finesse [which also totally relies teammates trusting that it's an uncommon enough mistake to *decline* to do a free priority finesse when it's available]

**Comment by Zamiell** [comment]
k seems fine

**Comment by Jayhui-q** [comment]
> I believe these are actually quite different.

Agreed. The rank vs. color choice on a particular card is substantially different for the cursed finesse proposal vs. the cursed bluff proposal. 

This convention is a lot more clearly and symmetrically suboptimal, so as to trigger a blind-play, though as I mentioned above, I see some cases where it is not. It also is not as easily confused with other conventions (I'm not sure if this one does at all, just haven't found any conflicts with this one yet).

**Comment by Zamiell** [comment]
submit a pr for this too

**Comment by Zamiell** [comment]
### The Cursed Finesse

- Commonly, players can use a *Double Finesse* or a *Clandestine Finesse* to "get" multiple cards from the next player. This works because the first blind-play "matches" the clued card.
- However, what if a player intentionally performs a *Bluff* where other players can see that it was actually possible to perform a *Double Finesse* or a *Clandestine Finesse*?
- In this situation, if the cluer is not making a mistake, they are trying to send a deeper message - they want an extra person to blind-play.
- This is called a *Cursed Finesse* because it requires the situation to be "cured". By performing a *Cure Blind-Play*, the move is transformed from a *Bluff* into a real *Finesse*.
- For example, in a 4-player game:
  - It is the first turn and nothing is played on the stacks.
  - Bob's hand is as follows, from left to right: `red 1, blue 1, green 3, green 3`
  - Donald's hand is as follows, from left to right: `blue 2, green 4, green 4, yellow 4`
  - Thus, Alice has a *Free Choice* between cluing blue to Donald and number 2 to Donald. If Alice chooses blue, then it will cause a *Bluff* (as a 2-for-1). If Alice chooses number 2, it will cause a *Clandestine Finesse* (as a 3-for-1).
  - Alice clues blue to Donald, touching a single blue 2.
  - Bob tries to blind-play the blue 1 from his *Finesse Position*. Instead, it is a red 1 and it successfully plays. Bob now knows that he was *Bluffed*.
  - Cathy sees that Alice could have done a *Clandestine Finesse* instead of a *Bluff*. Thus, Cathy knows that this must be a *Cursed Finesse*. Cathy blind-plays her *Finesse Position* (as a *Cure Blind-Play*). It is a red 2 and it successfully plays.
  - Bob and Donald both gasp in surprise when Cathy blind-plays:
    - From Bob's perspective, the focus of the clue is a *one-away-from-playable* card, so this cannot be a *Double Bluff*.
    - From Donald's perspective, this cannot be a normal *Finesse* or a *Double Bluff*, because Cathy would have done nothing, waiting for Bob to play the blue 1 (as a *Finesse*)
    - From both Bob and Donald's perspective, Bob's red 1 did not match Donald's blue card, so this cannot be a *Pestilent Double Bluff*.
  - Therefore, the team knows that this must have been a *Cursed Finesse*. Bob will now continue to blind-play until he finds his promised blue 1.
- *Cursed Finesses* can only occur if there is a *Free Choice* during the initial clue.
