### ISSUE TITLE
The Prophetic Finesse & The Prophetic Discharge

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#441]
Inspired by the 'Cursed' idea, and attempted [here](https://hanab.live/replay/373394#1) for science. The screenshot below has the duped b1 edited out for clarity - I'll be on the lookout for better examples!

**The Prophetic Trash Bluff**
> (Potentially only early game or even the first turn/round of the game - let's discuss!)
- If a player gives the game with a 1 clue that touches only a single 1 - *instead* of cleanly touching a different hand which holds that same 1 on *Finesse Position* - this must be communicating something extra 
- In this case, the next player should blind-play their own *Finesse Position* as a preemptive (*Prophetic*) *Trash Bluff*.
- Another player will now know that, for this to have occurred, they must hold the duplicated card on their own *Finesse Position*, and should start blind-playing (as it may very well be layered)
- [addendum] The clued player should treat this as an _Unnecessary_ form of _Trash Clue_, and act accordingly (with either a _CM_ or _Push_.)

<img width="1188" alt="Screen Shot 2020-12-17 at 1 57 48 PM" src="https://user-images.githubusercontent.com/32303453/102531134-da1fd980-406f-11eb-956c-582787b2f9b1.png">

**The Prophetic Trash Discharge**
- This works similarly to the *PTB* above, but if color is chosen instead
- Remember both of these only work if a *single* card is clued!
- In this instance, the next player can see that blind-playing their first finesse would lead to confusion and potential desync. 
- Instead, they should *Discharge*, which will cleanly lead to everyone understanding what is going on.
- [addendum] The clued player should treat this as an _Unnecessary_ form of _Trash Clue_, and act accordingly (with either a _CM_ or _Push_.)

<img width="1187" alt="Screen Shot 2020-12-17 at 2 19 15 PM" src="https://user-images.githubusercontent.com/32303453/102533028-da6da400-4072-11eb-8f9d-b33035868aa0.png">

**Comment by timotree3** [comment]
Seems like a cool idea. In your example for prophetic trash bluff, it doesn't seem like it's actually that much stronger (or even stronger at all) than a normal bluff on y1, followed by a 1's clue to Jerry (or whatever better clue kimbi finds)

Maybe the prophetic bluff should call for a different slot than slot 1 to make it a more useful tool?

**Comment by pianoblook** [comment]
lol well it was extra science-y here because I wanted to see if y2 would blind-play as a *Push* 😆 

I agree that it's strange to be using a 'trash'-style clue to just get a few cards from finesse positions. So I think that a reasonable addendum would be:
> the clued player should also treat this as an *Unnecessary Trash* move and therefore CM or Push.

^ thoughts? I think that would be much more useful than asking Bob to Eject or something strange like that

**Comment by Jayhui-q** [comment]
I like this convention a lot! 🔥 Would've been a super neat 4-for-1 in our game. I do tend to agree that it should only be done in early game (not sure about first round. Maybe.) Games in mid-game get increasingly complex and a prophetic discharge may be extremely confusing with other clued cards in hand (say Jerry had a clued b4 above and then writes b1 when a discharge occurs), or just with wanting Jerry to discard rather than play (! another reason for early-game). 

Also, agree with the addendum suggested.

Big fan of this, even more-so than the cursed suite.

**Comment by pianoblook** [comment]
in-game Prophetic UTD: 
<img width="1239" alt="Screen Shot 2020-12-21 at 6 59 59 PM" src="https://user-images.githubusercontent.com/32303453/102833315-c7363d80-43be-11eb-882d-addc8f29ed7c.png">

- Green to Christophe is atrocious, since it can be seen as strictly worse than 1s to Lanvin.
- BlueNovember _Discharges_ to signal that this green card is somehow, prophetically, trash
- Lanvin therefore marks their hand for being preemptively _Finessed_ for g1, and should begin blind-playing
- Cristophe should _Chop Move_ their slot 4 card

**Comment by jakestiles** [comment]
This seems neat. Will try to look out for opportunities where it would be good.

**Comment by pianoblook** [comment]
https://hanab.live/replay/27888#1

- 1 to lel0uch
- kimbi blind-plays slot 1 as a _Prophetic Trash Finesse_
- lel takes this as an Unnecessary Trash move, and therefore _Pushes_
- colton blind-plays, finding r1

<img width="902" alt="Screen Shot 2020-12-28 at 11 17 08 PM" src="https://user-images.githubusercontent.com/32303453/103258416-dc810e00-4962-11eb-857c-be4bfdc055ac.png">

**Comment by pianoblook** [comment]
https://hanab.live/replay/386260#1

- piper can open with Green to kimbi (intentionally touching the single card, of note)
- ADrone sees this is a Prophetic UTD
- kimbi pushes
- piano starts into the Layered Finesse for l1

altogether a 4-for-1 with good tempo and distribution

<img width="1240" alt="Screen Shot 2020-12-29 at 10 57 20 PM" src="https://user-images.githubusercontent.com/32303453/103329092-3815cf00-4a29-11eb-87f4-b5253fde8b3a.png">

**Comment by pianoblook** [comment]
- 1 to robb 
- infinity sees this is a _PTF_, so blind-plays
- zetty sees that ruby will blind-play r1, but robb will also _push_ p2
- therefore zett blind-plays too
- ruby blind-plays the (potentially layered) r1

<img width="1248" alt="Screen Shot 2021-01-04 at 4 57 01 PM" src="https://user-images.githubusercontent.com/32303453/103583612-029c3600-4eae-11eb-974b-6a2b4b6413a5.png">

**Comment by iamwhoiamhahaha** [comment]
That's a 4-for-1😲 Spicy 🔥🔥🔥

**Comment by pianoblook** [comment]
Not the most exciting example, but still a 2-for-1 + TCM on a 5.

- 1 to lelouch

<img width="1233" alt="Screen Shot 2021-01-05 at 10 32 32 AM" src="https://user-images.githubusercontent.com/32303453/103665384-5b68de80-4f41-11eb-9d4b-ac3eadfbff00.png">

**Comment by pianoblook** [comment]
Pretty nice tempo with a yellow (to wump) prophetic UTD

<img width="1237" alt="Screen Shot 2021-01-06 at 12 13 14 AM" src="https://user-images.githubusercontent.com/32303453/103731814-074b1200-4fb4-11eb-8b6d-e20a25c14131.png">

**Comment by Jayhui-q** [comment]
In your first example, suppose kimbi had g1 on slot 2, and a Timehoodie had a blue 5 on slot 3. 

Wouldn't this clue have been great for setting up a 5ce? 

There seems like there might be some under-discussed value of simply moving the chop.

I wonder if it should just be prophetic trash bluff if: 
1. color is used on a 1 on chop (not on chop could be because they're protecting a bad chop)
2. another player has a finessable 1 of that matching color. 

This way it's legit so suboptimal (clue looks like the color-2), so as to almost necessitate that something weird is happening.

**Comment by Zamiell** [comment]
this seems good and i appreciate all of the evidence posted

**Comment by Zamiell** [comment]
do you want to do a pr piano

**Comment by Jayhui-q** [comment]
> with either a CM or Push.

Really quickly on this. If the prophetic trash bluff is done on chop, then the recipient player should push?
I actually lean to CM instead of push, just because in early-game, it seems pretty unlikely that the player has a playable push.

**Comment by pianoblook** [comment]
> do you want to do a pr piano

Sure, I can over the weekend

> I actually lean to CM instead of push, just because in early-game, it seems pretty unlikely that the player has a playable push.

There's not anything to CM though: it's on chop! Since all the other cards being gotten are by definition on _Finesse_, this is about as _Unnecessary_ as it comes, and I can't imagine often deciding this would be a worthwhile line to take if it didn't get either a nice _CM_ or _Push_ on the clued player

**Comment by Jayhui-q** [comment]
> There's not anything to CM though: it's on chop!

I mean to the left, similar to a TPE.

> I can't imagine often deciding this would be a worthwhile line to take if it didn't get either a nice CM or Push on the clued player

Agreed. My remark is whether CM makes it more universally executable

Also, one more thought

> In this instance, the next player can see that blind-playing their first finesse would lead to confusion and potential desync.
> Instead, they should Discharge, which will cleanly lead to everyone understanding what is going on.

Interestingly, a single blind-play from finesse is actually sufficient to demonstrate to the team what is going on. 
The clue recipient, say Donald, can see Cathy had the 1 on finesse, and there is actually no other identity of the card that would cause Bob to blind-play. 

If it were b234, Bob would wait for Cathy. If it were b5, Bob would eject.

That in mind, do we actually prefer the discharge slot for one, and the finesse for the other?
What if we preferred discharges for either choice?
Or alternatively, a finesse for either choice?

I am rather compelled by discharge for either choice, on the first reflection. In early-game, (and in particular the first round, which I expect the 1s to have been used for) it is fairly evenly likely between slot 1 and slot 3. 

This gives Alice the choice to give negative color or negative rank, and frankly a discharge + finesse combo may be valuable enough so as to not call for a CM / push. 

Two 1's from finesse is also more likely to be consecutive, and executable with a 4DB or a Pestilent DB or a Bad Touch 3 DB.

**Comment by pianoblook** [comment]
> I mean to the left, similar to a TPE.
This feels super unintuitive to me :/ There's a reason TPE is weird enough to warrant an Ejection haha; it's otherwise just incredibly weird to be intentionally cluing trash on chop.  I don't think I'd ever want to perform this move if it didn't get a blind-play; CMing a card that would have just been safely in front of trash seems pretty low value

> Interestingly, a single blind-play from finesse is actually sufficient to demonstrate to the team what is going on.
> That in mind, do we actually prefer the discharge slot for one, and the finesse for the other?

That is interesting, yeah. Personally I'm a fan of having a way to differentiate slot 1 vs slot 3 blind-plays in this sort of situation: more flexibility, and pretty intuitive either way. Getting a Discharge off of a 1 rank clue seems *very* weird too. I'll defer to @Zamiell / others on this though - thoughts?

**Comment by Jayhui-q** [comment]
> I don't think I'd ever want to perform this move if it didn't get a blind-play

This line is interesting. Is the non-consecutive 2-for-1 just not a valuable choice in your view? 
I guess the logic might be we would prefer bluff + bluff + picking up a good card along the way as a 5-for-2.

I do think the non-consecutive 2-for-1 might be intrinsically more valuable on its own if it gets slot 3 as compared to slot 1, and not necessitate a cm/push read.

> CMing a card that would have just been safely in front of trash seems pretty low value

Sounds good. Agreed. 

> Getting a Discharge off of a 1 rank clue seems very weird too

Haha totally! I wonder if that makes it ultra-clear that this move is being done 😂

**Comment by Zamiell** [comment]
i think that it is "sufficient" for slot 1 to play in theory, but not in practice.
often times players will blind play without waiting for potentially matching cards because they have other contextual clues.
when you design a convention you want to minimize vectors for mistakes.
hard-requiring that donald sees that bob would wait for cathy sounds like a recipe for disaster

**Comment by Jayhui-q** [comment]
> hard-requiring that donald sees that bob would wait for cathy sounds like a recipe for disaster

Agreed. I don't think color should call for a finesse.

I'm curious about the discharge + finesse option for both rank and color. 
I believe our rationale for "this move is not good enough without a push/cm" is because both are coming from finesse. 

1 rank -> discharge allows you to perform this even when the player holds that same color. It seems to me that getting a 2-for-1 from those different slots might be worth it to not include a cm/push component. The additional cm/push component, I think, actually makes this move less useable.

**Comment by Jayhui-q** [comment]
I've thought about this more, and I think discharge is the best way to approach this for rank.
Here's why:
1. It is valuable enough, in my perspective, so as to not warrant a cm/push, especially given the dearth of discharge tools in the low score phase. 

While cm/push makes it more efficient, a) if the 1 is on chop, there must be a good push (which is almost never the case if it is anything but a 1 or 2), or b) there is an extra variable of "is this a valuable cm." These two make the move rarer, in my view.

And, as above, you can now use a blue 1 for this even if the recipient player has another blue card.

**And most importantly,**

2. It allows you to unambiguously do this move when the clue recipient comes before the player with 1 on finesse, and/or there are cards already played.

In all of the bluff examples provided above, there are notably no cards played on the stacks, or the player who has the card on finesse comes before the clue recipient.

Here is an ambiguous example:
- Suppose b1 is played.
- It is Alice's turn.
- Alice clues Cathy's g1 with a 1 clue. 
- Donald has a g1 on finesse.
- Bob plays slot 1, as prescribed by the above prophetic trash bluff.
- It is now Cathy's turn. She has no idea if the 1 she is holding was a trash bluff, or if it was prophetic. Cathy stomps on the move by cluing Donald's 1 or bluffing it out with Alice's hand. 
- The team is now desynced. 

The beauty of the prophetic suite and having a discharge universally is that a single-card 1 clue should **never** cause a discharge **unless** it is prophetic. It can never be confused with a trash bluff.

**Comment by pianoblook** [comment]
Unfortunately I still don't see a rank 1 "UTD" being very well-aligned with the rest of Hyphen-ated. 

There are plenty of ["Call Out"](https://github.com/Zamiell/hanabi-conventions/blob/master/misc/Bluff_Types.md#call-out-bluffs) bluffs that simply default to slot 1 because it's simplest, not because it's necessarily more theoretically justified. For example, we could just as easily decide a _Pestilent_ reaction should actually be an Ejection/Discharge from Cathy, but slot 1 "is all that's required".

Now tbf that same argument could be used to say that the color form could technically just as easily work as a Bluff instead of a UTD. Sure, but the same could be said about other niche situations where a Discharge response wouldn't be necessary. e.g. there's no reason an Ejection wouldn't work for Unknown Trash if the 5 is already seen elsewhere; or no reason to 5CE if a double bluff would be sufficient to mark it as a 5. 

Point is, there's value in having easy to remember patterns that can be learned and trusted. To me, a 1s clue very cleanly reads as, "aha this 1 is actually going to be trash; I'm therefore probably being asked to respond in the same way as very other trash bluff that exists".

**Comment by Jayhui-q** [comment]
> Unfortunately I still don't see a rank 1 "UTD" being very well-aligned with the rest of Hyphen-ated.
> I'm therefore probably being asked to respond in the same way as every other trash bluff that exists

Interesting, I hadn't thought of it that way! Though, it is certainly possible that slot 1 from Bob is not "all that's required." The second point I made above speaks to it.

>  For example, we could just as easily decide a Pestilent reaction should actually be an Ejection/Discharge from Cathy, but slot 1 "is all that's required".

Agreed. But, there are much fewer useful reasons to getting 2 1s off of finesse.

______

**Either way,** I made the remarks above because they are my opinions on how to make this tool optimal and not an unused convention. If you think otherwise even in light of the points I made above, I would definitely just proceed.

At the end of the day, I'm just one player, and I am delighted to see creative convention innovation.

**Comment by pianoblook** [comment]
Huh, just realized something...Does this only apply to 1s? Or could we open this to any card as the game progresses 🤔

**Comment by Jayhui-q** [comment]
> Huh, just realized something...Does this only apply to 1s? Or could we open this to any card as the game progresses 🤔

Yes, I think it should only apply to 1s, unless we want to add a lot of stipulations to it. 

This is because
1) It is more likely to be in a scenario where we want Bob to discard instead of being the one to play b2 
2) It is more likely that we are shifting the focus of Donald's chop 
3) It is more likely that Bob has something else to do

How much more likely would be a great question. I'm not sure. It is just a hunch that it is not worth it. But the beauty of it being only on 1s in early-game is that there is so little reason to construct a starting line that intentionally does not use someone's finesse position.

Perhaps we would consider its extension to other ranks after a few months of having the convention on only 1s.

**Comment by Zamiell** [comment]
### The Prophetic Finesse (for 1's)

- In most games, players will avoid giving a number 1 clue to a single playable 1 that is not on *Finesse Position* if a different player has the same 1 on *Finesse Position*. This is because it is usually better to *Finesse* it or to let someone else *Finesse* it.
- If a player does this anyway, and doing so was clearly bad, they must be communicating something extra.
- In this situation, the next player should treat the clue as if were a *Trash Finesse*.
- This is different from a *Trash Finesse* because a second blind-play is needed to prove that the card is not actually trash. The in-between player is promised to have the matching 1 on *Finesse Position*. The in-between blind-play is called a *Prophetic Blind-Play* to distinguish it from a normal blind-play.
- Furthermore, once the *Prophetic Finesse* has resolved, the clued player should **always** treat this as an *Unnecessary* move (e.g. as an *Unnecessary Trash Chop Move* or an *Unnecessary Trash Push*).
- For example, in a 4-player game:
  - Red 1 is played on the stacks.
  - Alice clues number 1 to Donald, touching a single blue 1 on slot 3.
  - Bob sees that Cathy has a blue 1 on her *Finesse Position*. Thus, Alice's clue is strange - she should have probably clued Cathy's blue 1, or allowed someone to *Finesse* Cathy's blue 1.
  - Bob knows that Alice must be intending for a *Prophetic Finesse*. Bob blind-plays his *Finesse Position*. It is a green 1 and it successfully plays.
  - Cathy sees that from Donald's perspective, a *Trash Finesse* has just occurred. Donald will mark the blue 1 (playable) as a red 1 (trash), and will discard it. This is bad, so Cathy knows that something else is expected of her.
  - Cathy knows that this a *Prophetic Finesse* and that she is promised to have a blue 1 on her *Finesse Position*. Cathy blind-plays her *Finesse Position* (as a *Prophetic Blind-Play*). It is a blue 1 and it successfully plays.
  - Donald knows that since a number 1 clue touched a single 1 and caused two blind-plays, this must be a *Prophetic Finesse*. Donald marks his touched 1 as trash. He also *Chop Moves* his slot 4 card because of the *Unnecessary* part of the move.
- *Prophetic Finesses* can only be triggered by touching **exactly one 1**. (However, they can be triggered with either a color clue or a number clue.)
- *Prophetic Finesses* can also be given in situations that cannot be mistaken for *Trash Finesses*.
- For example, in a 4-player game:
  - It is the first turn of the game and nothing is played on the stacks.
  - Alice clues number 1 to Donald, touching a single blue 1 on slot 3.
  - Just like in the previous example, Bob sees that this is a *Prophetic Finesse* (because Cathy has a blue 1 on her *Finesse Position*). Bob blind-plays his *Finesse Position*. It is a green 1 and it successfully plays.
  - Cathy sees that from Donald's perspective:
    - It will not look like a *Trash Finesse*, because no 1's were played at the time of the clue.
    - It will not look like a *Bad Touch Finesse (for 1's)*, since only a single 1 was clued.
  - Therefore, as soon Bob blind-plays, both Cathy and Donald can understand that it is a *Prophetic Finesse*.
  - Just like in the previous example, Cathy blind-plays the blue 1, and Donald marks his 1 as trash and *Chop Moves* his slot 4 card.

**Comment by Zamiell** [comment]
### The Prophetic Discharge

- First, see the section on the [Prophetic Finesse](special_finesses.md#the-prophetic-finesse-for-1s).
- *Prophetic Finesses* can only be given with a number 1 clue.
- If a player tries to use a color clue to initiate a *Prophetic Finesse*, they instead intend for the next player to blind-play their *Third Finesse Position* (like an *Unknown Trash Discharge*).
- Other than that, everything else works like a *Prophetic Finesse* (e.g. one of the in-between players is promised to have the matching card on their *Finesse Position*).
- Unlike the *Prophetic Finesse*, the clued player should **only** treat this as *Unnecessary* move if the *Discharged* card could have been cleanly clued.

**Comment by Zamiell** [comment]
if these edits seem fine to you, then i will close

**Comment by Zamiell** [comment]
wru bot

**Comment by Zamiell** [comment]
oh because i changed the repo name
