### ISSUE TITLE
Ignitions & unnecessary moves out of position in endgame

### ISSUE THREAD

**Issue by florian-5f3759df** [hanabi/hanabi.github.io#456]
In endgames of harder variants, it's a common situation that Alice has nothing to do, Bob already has a known clued card to play, and both Cathy and Donald have just drawn something playable. I propose to explicitly modify the ignition & unnecessary conventions to allow a bit more flexibility in who blind plays. (I think some people already play kind of like the version 1 below sometimes, please confirm in comments if that's you.)

**Version 1 (weak form):** Alice should be able to perform the ignition so that Bob can just play his known card, and it should be clear to the team that it's good enough if it's only on Cathy and Donald. This is something we already do in games when it's clear from context, but maybe we can just add a line that this is explicitly allowed and Bob shouldn't bomb. This also holds for e.g. an unnecessary trash push on Donald, that lets Cathy play. The modification would be: if a player already has a globally known play and they see that someone behind them can exhibit the extra play, it's not on them.

**Version 2 (strong form):** Redefine ignitions and unnecessary bonus blind plays in endgame as occurring on _anyone_, so basically on the last player/players that can show it. So if Bob and Donald have a card on finesse, Alice can give an ignition, Bob plays, Cathy just gives some unrelated clue or discards, and Donald plays. The modification then is: if a player can see that someone after them can exhibit the blind play, they assume it's not on them. Like an ambiguous finesse, but now just on 'any card on finesse position'. This type of efficiency gain is part of the power of hat guessing, but still seems pretty intuitive.

Strong form can be basically summarized as: ignition is like a positional bomb of slot 1, unnecessary pushes/pulls are like a positional discard of slot 1.

The good part about version 2 is that it's more versatile in higher player-count endgames, i.e., it works well in board states like the one mentioned, leaving Cathy free to do something useful. The bad part is that it's lower tempo in some situations where Alice could ignite Bob and Cathy, and then Donald can bluff Emily, and that more delay between clue and blind-play increases chances of desync (which is less of a problem if you only allow a known play in between as in version 1).

**Comment by Jayhui-q** [comment]
Agreed! This is something that we have come to contextually as well. I tend to play with the first version you mention. 
I've found that it is really helpful for "unnecessariness" to resolve immediately so that we aren't slow on who actually plays. 

The way we have thought about it is:
* The default assumption is that the unnecessary blind-play component is done by the first person who can react
* In end-game, if and only if you are already occupied with a card that does not match any of the finesses on the table and you see that the very next player has a playable finesse, you may pass it to them.

Totally agree with the weak form. The strong form I think can be game-losing at times and might be better as a contextual read. Are we really gunning for Donald to play? If so, then maybe Cathy should read Alice's clue as so.

**Comment by Zamiell** [comment]
we already play with the weak form (as you mentioned).
I added this to the doc:

```
#### Skipping Bluff Seat

- Rarely, if Bob has a playable card, a *Double Ignition* can skip over Bob and affect Cathy and Donald.
```

the strong form has problems:
1) ambiguous ignitions are possible (and semi-common)
2) uncommonly, players need to defer blind playing to give a clue to allow a winning line

**Comment by florian-5f3759df** [comment]
Agreed, the strong one is more of a double-edged sword: It could be good in some situations, e.g. in a 1-clue situation where Alice trash pushes Bob to get a bonus card on Donald, with Cathy discarding in the middle, but other times it's worse. I thought it might be worth it, but not 100% sure, so if common intuition falls the other way then I'll trust that.

Thanks for adding it to the doc. What's the opinion on allowing it for endgame unnecessary trash blind plays as well? I guess it's a bit more overhead, since we'd have to specify endgame, so more chance of people forgetting. (Or not specify endgame, but that has other disadvantages; it's meant mostly as redistribution tactic that lets Bob empty his hand when that's urgent.)

**Comment by Zamiell** [comment]
> What's the opinion on allowing it for endgame unnecessary trash blind plays as well?

are you referring to the "unnecessary" blind-play component of an unnecessary trash finesse?
in both
1) this scenario and
2)the scenario where a storm form OOP DI is needed
players will already allow for it to happen if they
a) see that it is necessary to win the game, or
b) see that it is winning if they allow it to happen

both a and b are exceptional circumstances, and will work without any additional doc modifications, so they probably don't need to be mentioned in the doc

**Comment by Zamiell** [comment]
- If the known trash clue cannot be any of these 3 things, then it communicates a *Double Ignition*, meaning that two players on the team need to blind-play their *Finesse Position* card as any playable card.
- In most circumstances, *Double Ignition* should be clear. This is because the two players with a playable card will each see that the clue giver should have clued the other playable card directly (instead of touching trash).
- Sometimes, three players on the team will have playable cards on *Finesse Position*. In this case, similar to how an *Ambiguous Finesse* works, a *Double Ignition* will "get" the cards from the final two players. (Bob will do nothing because he sees that the *Double Ignition* is on Cathy and Donald.)
