### ISSUE TITLE
Odd/Even Positional Discards and Misplays

### ISSUE THREAD

**Issue by Jayhui-q** [hanabi/hanabi.github.io#469]
Positional discards and positional plays are powerful tools to get cards in the end-game, but I was thinking we could extend these conventions to allow for getting more cards than 2 that all lie on the same slot, especially in 4 or more player games.

An example is:
- No strikes/bombs have been incurred 
- Alice sees all of the remaining useful cards
- Bob, Cathy, and Donald all have unclued playable cards on slot 2.
- Alice bombs slot 2 to get two cards played (the current conventional maximum)
- Due to ambiguity, Cathy and Donald are the two players who play. 

The proposed extension is that positional discards and positional misplays actually correspond to the odd/even parity of how many unknown playable cards are on that slot. 

Namely, a positional discard not on chop signals that there are an _odd_ number of cards to be played from that slot, while a positional misplay signals that there are an _even_ number of cards to be played from that slot.

That is, in the above example, Alice would discard slot 2. Bob sees that there are two directly playable cards in Cathy and Donald's hand and scratches his head. Why didn't Alice bomb for two when there was a strike available? _Because there are three playables._ 

Off of chop, a discard gets 1/3/5 plays from that slot, a misplay gets 2/4 plays. 

This could also be extended to chop as well, but swapping the parity. 

A discard signals 0/2/4 plays from that slot, and a misplay gets 1/3/5.

**Comment by Zamiell** [comment]
does it get fucked if 2 people have y4 on different slots?

**Comment by Zamiell** [comment]
historically, we have not encoded information like this into clues because it feels like cheating.
e.g. if we wanted to win all the time, then we would play hat guessing

**Comment by pianoblook** [comment]
The logic behind this seems pretty clever and understandable, so it doesn't feel very Hatlike in that regard.

Another way to phrase this, if I'm getting it right, is that if Bob sees that Alice could have performed a _Positional Bomb_ but instead chose to do the strictly worse _Positional Discard_, it must mean something extra. Love it!

Though it does seem extremely rare, lol. And the possibility of dupes does seem kind of awkward, haha.

**Comment by Jayhui-q** [comment]
> historically, we have not encoded information like this into clues because it feels like cheating.

Interesting! To me, this seems like the shadow extension of positional discards, rather than something hat-like. 

> does it get fucked if 2 people have y4 on different slots?
I'm not sure what this question means -- each slot is considered independent of another, so if Bob had y4 on slot 2 and Cathy had y4 on slot 3, Alice would just pick the slot that Donald has to bomb/discard for.
  
Maybe you meant that there are dupes on the same slot. In which case, 
surprisingly, no, as long as each player counts duplicates together as 1.

For example, in a 5 player game:
- Alice can see everything useful, and a non-losing strike is available
- y3 and b4 are on the stacks
- Cathy and Donald have y4 on slot 2. Emily has b5 on slot 2.
- Alice positional bombs to get y4 and b5 (even) 
- Bob and Cathy, seeing 2 playable (y4 and b5), delay. Donald and Emily play.

If it were Cathy and Emily who have y4, then Cathy would delay and Donald and Emily would play. 
If it were Donald and Emily who have y4, then Cathy would play, Donald would delay, and Emily would play. 

Suppose instead that Alice discarded.
Bob can see only two unique playable cards, and will blind-play, knowing that three are being called for. 
Cathy Donald and Emily will resolve it just like above.

**Comment by Jayhui-q** [comment]
> Another way to phrase this, if I'm getting it right, is that if Bob sees that Alice could have performed a Positional Bomb but instead chose to do the strictly worse Positional Discard, it must mean something extra. Love it!

Exactly right! And this extends straightforwardly to higher numbers of cards playable such as 3/4/5. 

The interesting one to me is the one about the chop. How can you get two cards played from chop when it is clear the team is in deep need of plays? Discard!

**Comment by pianoblook** [comment]
> The interesting one to me is the one about the chop. How can you get two cards played from chop when it is clear the team is in deep need of plays? Discard!

Funnily enough, my prescription has been to just discard as normal and force Bob to therefore positional bomb for Cathy

funnily enough, that natural 'weird' discard - encouraging a bomb from Bob - is actually just one specific instance of this broader principle: Bob can think "well that was strange - Alice should have _Bombed_ chop to get a single card (from Cathy's chop), but the fact that she didn't must mean something **extra**"

**Comment by Zamiell** [comment]
the convention seems good but im still on the fence to adding it to the doc, since

1) it might increase situations in which players make end-game mistakes
2) entries in the doc are supposed to be for "semi-common" things and this borders on being rare

do any other players want to chime in

**Comment by Zamiell** [comment]
### The Shallow Discard

- At the end of the game, it is normal for players to use a *Positional Discard* to get 1 card to blind-play, and to use a *Positional Misplay* to get 2 cards to blind-play.
- If a player does a *Positional Discard* to only get 1 card when they could have performed a *Positional Misplay* instead, then this is quite strange. If they are not making a mistake, they must be trying to send an additional message.
- In this situation, they intend for it to promise 3 blind-plays instead of 1.
- This is called a *Shallow Discard* because from Bob's perspective, Alice could have performed a deeper move.
- For example, in a 4-player game:
  - The team has 0 strikes.
  - It is the *End-Game* and Alice sees all of the remaining useful cards. Thus, she can *Positionally Discard* or *Positionally Misplay* any card that she wants in her hand.
  - Alice sees that Bob, Cathy, and Donald all have playable cards on slot 2.
  - Alice blind-discards her slot 2 card as a *Shallow Discard*.
  - From Bob's perspective, he sees that Cathy and Donald have a playable card on slot 2. Thus, Bob expected Alice to perform a *Positional Misplay* or her slot 2 card.
  - When Bob sees that Alice performed a *Positional Discard* instead of a *Positional Misplay*, he knows that she must be intending for 3 blind-plays to happen (instead of 1) as a *Shallow Discard*.
  - Bob blind-plays his slot 2 card (to match Alice's slot 2 discard). It successfully plays.
  - Cathy and Donald are both in a similar situation to Bob. (They expected Alice to perform a *Shallow Discard*.)
  - Thus, they both know that this is a *Shallow Misplay*, and blind-play their slot 2 cards (to match Alice's slot 2 discard).

### The Shadow Misplay

- First, see the section on the *[Shallow Discard](#the-shallow-discard)*.
- In a 5-player game, it possible to perform a *Shallow Misplay*, causing 4 people to blind-play from the same slot. (This works for the same reasons that a *Shallow Discard* works.)
- For example, in a 5-player game:
  - The team has 0 strikes.
  - It is the *End-Game* and Alice sees all of the remaining useful cards. Thus, she can *Positionally Discard* or *Positionally Misplay* any card that she wants in her hand.
  - Alice sees that Bob, Cathy, Donald, and Emily all have playable cards on slot 2.
  - Alice blind-plays her slot 2 card as a *Shallow Misplay*.
  - From Bob's perspective, he sees that Cathy, Donald, and Emily have a playable card on slot 2. Thus, Bob expected Alice to perform a *Shallow Discard* or her slot 2 card.
  - When Bob sees that Alice performed a *Positional Misplay* instead of a *Shallow Discard*, he knows that she must be intending for 4 blind-plays to happen (instead of 2) as a *Shallow Misplay*.
  - Bob blind-plays his slot 2 card (to match Alice's slot 2 discard). It successfully plays.
  - Cathy, Donald, and Emily are all in a similar situation to Bob. (They expected Alice to perform a *Shallow Discard*.)
  - Thus, they all know that this is a *Shallow Misplay*, and blind-play their slot 2 cards (to match Alice's slot 2 discard).

**Comment by Jayhui-q** [comment]
I love the naming you gave this! 

Some small notes:
- The second to last bullet on shallow discard says "They expected Alice to perform a Shallow Discard" when I believe it should say "... perform a Positional Misplay". The same goes for the last bullet (.. both know that this is a shallow discard.)
- A small note may be useful to clarify what happens when the discard/misplay is on the chop. My proposal was that it works in the same way just 1 less. (misplay -> 1, 3), (discard -> 2,4). The note might be something like:

`In some specific situations, a Shallow Discard can be performed on chop. The Shallow Discard on chop calls for 2 plays rather than 3, because the deeper move of a positional misplay would only promise 1 card to play.`

**Comment by Zamiell** [comment]
> The second to last bullet on shallow discard says "They expected Alice to perform a Shallow Discard" when I believe it should say "... perform a Positional Misplay". The same goes for the last bullet (.. both know that this is a shallow discard.)

fixed

**Comment by Zamiell** [comment]
> In some specific situations, a Shallow Discard can be performed on chop. The Shallow Discard on chop calls for 2 plays rather than 3, because the deeper move of a positional misplay would only promise 1 card to play.

ok:

> - In some specific situations, a *Positional Discard* from chop would not work, because it would just look like a normal discard. In these situations, a *Positional Misplay* would only get 1 blind-play (instead of 2) and a *Shallow Discard* would only get 2 blind-plays (instead of 3).
