### ISSUE TITLE
Delete Prism Color Finesses (Two-Away-From-Playable)

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#473]
That would mean that you could e.g. bluff prism 1 with a green clue.

**Comment by hakha3** [comment]
does this mean I can bluff i1 with color to i3?

**Comment by Zamiell** [comment]
yes

**Comment by Zamiell** [comment]
probably not

**Comment by hakha3** [comment]
so it would be mostly, that clue receiver should assume some bluff instead of finesse on prism, but other players should act accordignly?

**Comment by Zamiell** [comment]
yeah i think that makes the most sense

**Comment by timotree3** [comment]
What do you think of this way of thinking about it?

- Alice clues green to Donald as a play clue on the prism 3
- Bob blind-plays prism 1 from *Finesse Position*
- Now Cathy has to decide whether this is a *Double Finesse* or a *3 Bluff*.
  - In No Variant, a clue only matches a blind-play if the next card in the suit would be touched that clue, so the fact that prism 2 is not touched by green clues suggests that it's a *3 Bluff*
  - However, in No Variant, the way to trigger a *Double Finesse* instead of a *3 Bluff* is to choose color instead of rank so that the clue matches, so the fact that Alice chose color suggests that it's a *Double Finesse*
  - Therefore, if Alice could've chosen a rank clue instead of a color clue, Cathy should assume a *Double Finesse*, but if Alice could not choose rank, Cathy should assume a *3 Bluff*

**Comment by Zamiell** [comment]
sounds too complicated

**Comment by Jayhui-q** [comment]
I like this. The conv that rkass, avanderwalde, and I used for the prism comp is exactly what you described. 

> Prism Matching Rule
> When a color clue is given that demands a blind-play, the play “matches” only if it is the very next color of the card played. I.e. yellow matches a prism red 1 play. Green matches a prism yellow 2 play

I think this is pretty intuitive -- "matching" in general, as I understand, is when the card clued could be the card that directly follows after the blind-played card.

**Comment by Zamiell** [comment]
what tim typed out is essentially a *Rank Choice Finesse*, which will probably be deleted soon.
thus, lets go with the simpler formulation where its always a bluff, e.g. you can bluff prism 1 with prism 3

**Comment by Zamiell** [comment]
### Color Finesses (One-Away-From-Playable)

- For the purposes of *Finesses*, prism cards "match" if they are the direct next color.
- For example, in a 3-player game of *Prism (5 Suits)*:
  - Prism 1 is played on the stacks.
  - Alice clues green to Cathy, touching a prism 3 as a *Play Clue*.
  - Bob blind-plays a prism 2 from his *Finesse Position*.
  - Cathy knows that since prism 3 is green, prism 2 matches green. Thus, this must be a *Finesse*.
  - Cathy plays her green as a prism 3.

### Color Bluffs (Two-Away-From-Playable)

- Players can perform a *Bluff* on a prism card with a color, as long as that color represents a prism card that is *two-or-more-away-from-playable*.
- As a consequence of this, you can *Bluff* a prism 1 by cluing a prism 3 (with color).
- For example, in a 3-player game of *Prism (5 Suits)*:
  - Nothing is played on the stacks.
  - Alice clues green to Cathy, touching a prism 3 as a *Play Clue*.
  - Bob blind-plays a prism 1 from his *Finesse Position*.
  - Cathy knows that prism 1 would match yellow, but it does not match green. Thus, this is just a *Bluff*.
  - Cathy marks her green card as either a green 2 (as a normal *Bluff*, a green 3 (as a *3 Bluff*), or a prism 3 (as a *Hard 3 Bluff*).
