### ISSUE TITLE
Unknown Dupe Discharge

### ISSUE THREAD

**Issue by Indego** [hanabi/hanabi.github.io#475]
credits to melwen, @pianoblook and his competition team, jerryY and his competition team, dobi (previously doctorabi).
Thank you for your time, play and feedback! You all make Hanabi awesome. You welcome a newbie like myself with open arms & inspire us all to stay bold!

This issue aims to add another opportunity for discharge using duplicate cards in one hand. Bottom line, UDD should have a clear definition that allows safe play and avoids conflict with existing conventions.

---
## Unknown Dupe Discharge
1. UDD may be triggered when a color clue focuses a duplicate card
2. the next available player discharges to signal "play" → "trash"
    **finesse instead if a duplicate pair of one-away-from-playable is touched**
3. recipient gasps in surprise, realizes an UDD has occurred, then marks the focus trash
4. recipient discards the focus
5. it is promised that another copy was touched with the same clue
- UDD does not apply in the end game
- UDD does not apply if the duplication is unavoidable

**advantages**
- results in instant play
- is at least 2-for-1, up to 5-for-1
- gives team a safe discard, recipient's chop is protected
- when exactly two cards are touched, and no matching cards have been clued, trash order chop move applies - [***example***](https://hanab.live/replay/410153#9)

**context**
when duplicate cards appear in one hand, we currently deal with them by:
1. cause a finesse/ejection/discharge/charm to target one of them
2. wait for all other cards of the same color or rank to be clued
3. wait for one to discard, then use elimination
4. clue directly, then fix

notice that only 1st and 4th apply instantly, and the 4th requires 2 clues. UDD both apply instantly and require only 1 clue.
Unknown-duped-1s was previous proposed by Dr_Kakashi (#271), and was rejected for potential conflict 10 as listed below.

---
## potential conflicts & considerations

1. trash finesse/bluff
    **does not conflict**, as reference currently differentiate them

2. regular finesse/bluff - ***[counter-example](https://hanab.live/replay/411162#25)***
    **exception: finesse instead if a duplicate pair of one-away-from-playable is touched**

3. bad touch finesse/bluff
    **we restrict general form UTD to color, and keep rank for bad touch finesse/bluff**

4. weak form trash finesse - [***counter-example***](https://hanab.live/replay/410017#4) (rz asked in #convention-questions last week) & ***[counter-example](https://hanab.live/replay/411162#25)***
    reverse weak form trash finesses are slower, thus UDD should take precedence over reverse wftf.

5. bubblegum finesse/bluff - ***[example](https://hanab.live/replay/410932#11)*** (notice the clued card looks i4/b3 after discharge)
    **not an issue.** seems to apply rarely, and there are at most two ambiguous possibilities. some of the fun of playing with variants is the added ambiguity.

6. unknown trash push discharge
    **not an issue,** since this occurs rarely outside of late game.

7. **unavoidable bad touch** in tricky variants
    unavoidable violation of good touch principle should not cause blindplay, from UDD or any other existing convention. UDD could be disabled for certain variants, open to discussion.

8. contextual focus inversion
    we believe that context overrides convention in all cases, even conventions as fundamental as chop focus. therefore, it is perfectly reasonable to override UDD.

9. redistribution in late game
    we agree that the UDD does not apply to end game.

10. simply getting the touched card to play
    this is by far the gray area involving the most judgement call with using trash-y conventions. absolutely open to discussing game play scenarios in this category, and hopefully this can get ironed out more here!

**Comment by Indego** [comment]
In response to a scenario raised in #271 
> consider a 3-player game:
> on the first turn of the game, alice clues red to cathy with the following hand: b4, b4, g4, r1, r1
> bob thinks that it is general form UTD convention and bombs a red 5 from slot 3, losing the game

This case is now avoidable by cluing 1 instead of red.

**Comment by florian-5f3759df** [comment]
I like it! I'm both for clarity on UTD vs. Trash Bluff, and the opportunity actually does come up sometimes. I am still a little bit confused at some of the wording. Is a correct summary of the changes that:

1. We can now do UTD when the focused card is not trash but duped within the same clue, overriding the bad touch finesses in some cases.
2. Good touch on a color clue, focused on trash, makes clue that used to be trash bluff now UTD? Say No Variant if r4 is down, Cathy has unclued x x r5 r4, and Alice clues red to Cathy. This used to be a weird case (since it's a trash bluff but breaks good touch), and now is definitely UTD?

I presume that the 'one-away' exception is meant like for 5CE, so actually counting blind-plays of Bob: UTD if either the twice-clued card is already playable (since we'd leave it for bluff / ejection / discharge or just elimination), or if Bob needs to blind-play more than one card. If Alice clues a doubled r3 on Donald, and Bob sees r2 somewhere in finesse position he won't discharge. Or obviously if he sees both r1+r2 on finesse position, and zero blind-plays are needed.

Is that correct, or did you really mean one-away literally?

One minor note: cluing 1 to b4, b4, g4, r1, r1 is often worse than cluing red, since the fix is much more urgent. But I guess that's a price we could consider paying, if people consider it worth it. (Either that, or turn it off at start or 8 clues or DDA + nothing better to do.)

Nice real-game example by Zamiel: https://hanab.live/replay/404355#1

**Comment by pianoblook** [comment]
I support this generally speaking! As discussed previously, the only part I care about is consistency and clarity for Bob. The simplicity ((and immediate resynchronization) of calling for an immediate response from Bob instead of needing to entertain a _Reverse Weak Form Trash Finesse_ is fairly substantial in my opinion.

> One minor note: cluing 1 to b4, b4, g4, r1, r1 is often worse than cluing red, since the fix is much more urgent.
100% agree that in 8-clue/stalling edge-cases like this, players should not assume a UTD is occurring. It would feel very weird for Bob to think he should respond to what otherwise might genuinely be the optimal clue to give at the time.

One other minor thought is that a lot of players currently do this all the time for duplicate unplayed 1s, but players would need to readapt to not assuming they're 1s at all until after they discard. But that's fine imo

Example with rank from this week: https://hanab.live/replay/410997#2

**Comment by mmelwen** [comment]
agree with indego and piano (#3) listed above, restricted to color and I would say that should work

**Comment by Zamiell** [comment]
> This case is now avoidable by cluing 1 instead of red.

cluing 1s sets up a near-certain near-term bomb (as opposed to a uncertain long-term bomb), so we can't hand wave that away

**Comment by Zamiell** [comment]
also someone should come up with an actual name for the proposed convention, because you literally can't perform a utd when you dont touch trash

**Comment by Zamiell** [comment]
> Nice real-game example by Zamiel

in that game:
1) we agreed that fireheart was not promised any particular blue card
2) he only discovers what specific card was duped after discarding the focus of the clue (chop e.g. slot 4)
3) since three cards were touched as part of the clue, he is not promised the location of the duped card, e.g. after discarding it can be on either slot 2 or slot 4

this is symmetric with what indego has proposed, if i am reading what she said correctly

**Comment by Zamiell** [comment]
> cluing 1s sets up a near-certain, near-term bomb (as opposed to a uncertain, long-term bomb), so we can't hand wave that away

in the example game that florian linked, it is clear what zamiel's intent is because:
1) florian sees that zamiel can 2 save valetta and
2) florian would then green to valetta, bluffing the b1

however, this situation does not map on to the hypothetical in 271.
in 271, because of the logic I quoted above, red is the superior clue.
since rank is inferior, it would naturally cause a finesse, (e.g. specifically the *Bad Touch Finesse (For 1s)*)

my main concern is that, now, you are defining an interpretation for red, so that alice has no tools left which with to clue anything.
e.g. cluing 1s gets a bomb on slot 1 and cluing reds gets a bomb on slot 3, so you literally have no choices left that you give the player.

**Comment by Indego** [comment]
> 1. We can now do UTD when the focused card is not trash but duped within the same clue, overriding the bad touch finesses in some cases.

Indeed, as linked, some experienced players have been using this informally.

> 2. Good touch on a color clue, focused on trash, makes clue that used to be trash bluff now UTD?

Some clues, yes.

> Say No Variant if r4 is down, Cathy has unclued x x r5 r4, and Alice clues red to Cathy. This used to be a weird case (since it's a trash bluff but breaks good touch), and now is definitely UTD?

Given it is not the endgame (we can afford to clue r5 after cathy discards), focus inversion does not apply, cluing 5 would be possible (ie. doesn't look like bad chop move ejection), then the proposal suggests Bob to discharge.

Any game play we can find where this would conflict with context? for instance, chop is likely not 5 because Alice stole Cathy's finesse the round prior

> UTD if either the twice-clued card is already playable, or if Bob needs to blind-play more than one card.

Yes, I think this would be a sensible starting point, although we might play more and find one-away restriction to be insufficient. I thought there should be an one-away exception partially for 5ce, as you mentioned. Partially because sometimes you want a finesse RIGHT NOW, and hope that the card the trash would be known as shows up before it bombs.

**Comment by Indego** [comment]
> my main concern is that, now, you are defining an interpretation for red, so that alice has no tools left which with to clue anything.
> cluing 1s sets up a near-certain, near-term bomb (as opposed to a uncertain, long-term bomb)

I see, so bad touch finesse still works in this case because rank is considered the suboptimal clue.
Hmm that makes sense, so we need to judge whether the duplication is known "avoidable". As piano mentioned, the very first clue, 8 clue stall, DDA stall, etc. could bring up situations where duplication may be unavoidable.

I wonder if we should leave the "avoidable" clause as I've revised the original post to use Unknown Dupe Discharge wording. 
I am afraid that the "avoidable" concept introduce too much headspace complexity. Perhaps we can shortlist categories of these scenarios where UDD would not apply to.

Thus far:
- end game
- first turn (first round in 2p)
- 8 clues / DDA stall

sidenote: I presume a similar point of discussion came up when the "unnecessary" component was introduced, rather curious about the story behind that one :D

**Comment by Indego** [comment]
> someone should come up with an actual name for the proposed convention
> probably just a Unknown Dupe Discharge, feel free to suggest something better

Thank you Zam, that works for now, but open to other name suggestions.

**Comment by Indego** [comment]
> 1. we agreed that fireheart was not promised any particular blue card
> 2. he only discovers what specific card was duped after discarding the focus of the clue (chop e.g. slot 4)
> 3. since three cards were touched as part of the clue, he is not promised the location of the duped card, e.g. after discarding it can be on either slot 2 or slot 4

Yes, discard to find out which card was duped, and the slot of another copy is not promised. This allows for 3-for-1 clues like the one Zam gave.

**Comment by Jayhui-q** [comment]
Agree with Piano on sticking only to color, so as to avoid bad touch 3s/4s ideas. 
As such, I like the name that Zamiel noted which is "Bad Touch Color Discharge" personally! (though I don't think it entirely captures UTD cause UTD can be given with a number clue).

Does this discharge only apply if both are in Cathy's hand? I personally have had a lot of success with this idea when both are in the same player's hand with rkass and avanderwalde. 

If not, I wonder what we would say about this turn, then:
https://hanab.live/replay/410183#45

rkass thinks g4 is in his hand and decides to discharge to communicate duplication. 

The duplication-ness of a card can be asymmetric, which I think makes me slightly hesitant on this, but it follows from the same principle.
________

One other thing to think about: is there an unnecessary component to think about for this?

**Comment by Zamiell** [comment]
> Does this discharge only apply if both are in Cathy's hand?

given the replay that you linked, i would say yes

**Comment by Jayhui-q** [comment]
> regular finesse/bluff - counter-example
> exception: finesse instead if a duplicate pair of one-away-from-playable is touched

I'm actually surprisingly worried about this, and it makes me hesitant to be on board, even if the dupe is in the same hand.

Seems like a bad touch color discharge could totally remove some nice double finesse options or pestilence (as it would now be read as a discharge from Bob). We would be forced to wait for Cathy to discard the duplicate (which could move the finesse card away from finesse).

The verdict question imo is, in a general game, are two finesses (either from the same player or different players) more likely than a discharge?

**Comment by Jayhui-q** [comment]
Does the UDD work if the duplicate card focused is playable? My assumption is no (just a desperate play clue, or you could wait for elimination finesse/riding deduction), but I'm not sure what the proposal above prescribes. 

I think the example with Zamiel with b1s only works because the b1 is on finesse (or alternative the b1 could be ejected). Otherwise, you would prefer the bad touch blues if a b2 is on the table.

Another consideration is elimination notes rather than WFTF. I personally like reading into the existence of the other remaining good cards in a game.

I decided to explore some of this and looked at 14 4p games and 14 5p games. (which is not a great sample size but hey)

Out of the 4p games:
- There were 0 cases where a two-or-more-away from playable could be duped for a playable discharge.
- There were 2 cases where a two-or-more away from playable could be duped, and a discharge position exists
- There were 4 cases where a one-or-more away from playable could be duped (which would not cause a discharge, with the exception above), 2 of which had a playable discharge, 1 that did not have a playable discharge, and 1 case that it would be better read as a finesse/bluff
- There were 2 cases where a playable could be duped and had a playable discharge. 

Out of the 5p games:
- 2 instances where a two-away dupe exists, only one of which were a discharge position on the previous player exists, and 0 where it was playable
- 3 instances where a playable could be duped, and 2 of which where a discharge position exists, and 0 where it was playable.

By no means does this prove anything about the likelihood of it, but the point is, I worry about a few things:
1) what is the likelihood that in a game where players have 4 cards in hand, that two of them are dupes, and the previous player has a discharge slot that is playable?
2) that we have confined the discharge above so narrowly that it both doesn't conflict with much, but also means it's rarely useable
3) As you mentioned:

> I am afraid that the "avoidable" concept introduce too much headspace complexity

Same here.

I hate being a downer on what is otherwise a clever and innovative convention, but I am concerned that codifying this eliminates clue options to speed up plays, or when a player sees a clear fix clue to follow that will pick up good cards.

I do like this a lot more for three players:
1) more likely to have dupes in hand
2) less turns to save dupes
3) less likely to ask for a double finesse
4) slow to elimination deduction
5) less likely to WFTF

And most importantly, you can use rank now! For bad touch 3 double bluff, a 3 player game has no Cathy to demonstrate it.

**Comment by Zamiell** [comment]
> Seems like a bad touch color discharge could totally remove some nice double finesse options or pestilence (as it would now be read as a discharge from Bob).
> The verdict question imo is, in a general game, are two finesses (either from the same player or different players) more likely than a discharge?

that is a correct framing of the tradeoff involved

**Comment by Zamiell** [comment]
> Does the UDD work if the duplicate card focused is playable? My assumption is no

indego proposes yes. the only times UDD are turned off are:
- end game
- 8 clues
- DDA

**Comment by Zamiell** [comment]
> I think the example with Zamiel with b1s only works because the b1 is on finesse (or alternative the b1 could be ejected). Otherwise, you would prefer the bad touch blues if a b2 is on the table.

agree

> Another consideration is elimination notes rather than WFTF. I personally like reading into the existence of the other remaining good cards in a game.

agree, generally speaking

> I decided to explore some of this and looked at 14 4p games and 14 5p games

nice work!

> I am concerned that codifying this eliminates clue options to speed up plays, or when a player sees a clear fix clue to follow that will pick up good cards.

that's precisely why this isn't already a convention =p

others seem to think that UDD has general-purpose use, so UDD seems to be winning over edge-case dupe lines.
we can/should bake in an explicit caveat:

```
- There are a lot of good reasons for good players to occasionally violate *Good Touch Principle*, so *Unknown Dupe Discharge* does **not** apply in every situation. If Bob can see a reasonable reason for why Alice would duplicate some cards, then he should relax and prefer a simple duplication (combined with some kind of other follow-up clue) over a complicated *Discharge*.
```

**Comment by Jayhui-q** [comment]
> we can/should bake in an explicit caveat

I like this perspective and approach. The more I reflect on this, the more I believe that this move is extremely context-reliant, much moreso than other moves, and is not / should not be dependent on the qualities of the card focused (is it playable, one-away, two-away, etc.)

Bob plays the game as if the convention doesn't exist, but when an extremely unusual duplication occurs, he knows what Alice meant.

**Comment by Zamiell** [comment]
> Bob plays the game as if the convention doesn't exist, but when an extremely unusual duplication occurs, he knows what Alice meant.

sounds perfect to me

**Comment by Zamiell** [comment]
draft:

### Unknown Dupe Discharge (UDD)

- First, see the section on *[Unknown Trash Discharge](#the-unknown-trash-discharge-1-for-1-form-utd)*.
- Typically, players closely follow *Good Touch Principle*, since duplicating cards is confusing and forces follow-up *Fix Clues*.
- However, there are still plenty of situations where players will intentionally duplicate a card:
  1) The first turn of the game (when there is nothing else to do)
  2) When the team is at 8 clues (and there is nothing else to do)
  3) When a player is in a *Double Discard Situation* (and there is nothing else to do)
  4) When the team is losing and nearing the *End-Game* (and *Tempo* on playable cards is really important)
  5) When the efficiency of getting a big *Finesse* outweighs the disadvantage of potentially having to give a *Fix Clue* later
  6) When a *Phantom Playable Card* is at risk of being discarded and the preceding cards must be gotten as soon as possible
- If a player duplicates a card that does not meet one of these 6 criteria, then they must be trying to send an additional message.
- In this case, they intend for a *Discharge* to communicate the "badness" of the focused card. This is called an *Unknown Dupe Discard* (and works in a very similar way to the *Unknown Trash Discharge*).
- After an *Unknown Dupe Discard*, the focus of the clue can be any unknown duplicated card. The player will only know which specific duplicated card it is after they discard it. Once they discard it, then they can write *Elimination Notes* on the remaining matching cards in their hand.
- For example, in a 3-player game:
  - It is the first turn of the game and nothing is played on the stacks.
  - Alice clues number 5 to Bob as a *5 Save*.
  - Bob clues number 5 to Alice as a *5 Save*.
  - Bob's hand is as follows: `red 2, red 2, red 4, blue 4, blue [5]`
  - Cathy clues red to Bob, touching the red 2 on slot 1, the red 2 on slot 2, and the red 4 on slot 3.
  - Alice knows that Cathy is violating *Good Touch Principle* and duplicating the red 2. There doesn't seem to be a very good reason for this, so this must be an *Unknown Dupe Discharge*.
  - Alice blind-plays her *Third Finesse Position*. It is a blue 1 and it successfully plays on the stacks.
  - Normally, Bob would think that this was an *Unknown Trash Discharge*. However, no red trash cards exist. Thus, this must have been an *Unknown Dupe Discharge*.
  - Bob discards his slot 1 card (the focus of the clue). It is revealed to be a red 2. Now, Bob writes *Elimination Notes* for the red 2 on his slot 2 and his slot 3.
- *Unknown Dupe Discharges* only apply if the two duplicated cards are in the same person's hand.
  - It is explicitly illegal to perform an *Unknown Dupe Discharge* that duplicates a card in someone else's hand. If this happens, the clue must have some other meaning.

**Comment by Jayhui-q** [comment]
Looks good!
> If a player duplicates a card these 6 criteria do not apply, then they must be trying to send an additional message.

I think there may be a 7th to add, which is a bad touch 3 double bluff / bad touch 4 triple bluff. That way, I don't repeat the mistake I made when you gave a bad touch 3 DB to me 😅

**Comment by Zamiell** [comment]
see my edits.

i think that a bad touch double finesse would have precedence over UDD, but not necessarily bad touch double half bluff / bad touch double bluff, since those are more difficult to see from bob's perspective

**Comment by Jayhui-q** [comment]
Nice!

I thought you had intentionally excluded the "color" part of the move in the first draft.  
That is, just like how a 4DB vs. Charm interpretation from Bob depends on the finesse position's identity of Cathy, you can perform a UDD with rank if Cathy's finesse position is strictly unplayable. 

I feel like that makes this move stronger and more applicable?
If we do constrain it to only color, then you can remove the situation criteria 7, because there is no overlap if color is the only option. 

> i think that a bad touch double finesse would have precedence over UDD, but not necessarily bad touch double half bluff / bad touch double bluff, since those are more difficult to see from bob's perspective.

My take is that the bad touch double finesse/bluff moves always take precedence over UDD in 4-player or more games. This is less confusing in my opinion than wedging a discharge between two very similar moves (and my intuition says that the bluff is actually more probable to occur than the finesse). In my view, making the distinction for the precedence would be like: 

Unlikely move (Bad touch double finesse) > very unlikely move (UDD) > likely move (bad touch double bluff).

**Comment by Zamiell** [comment]
> I thought you had intentionally excluded the "color" part of the move in the first draft.

i forgot

> That is, just like how a 4DB vs. Charm interpretation from Bob depends on the finesse position's identity of Cathy, you can perform a UDD with rank if Cathy's finesse position is strictly unplayable. I feel like that makes this move stronger and more applicable?

fine

> If we do constrain it to only color, then you can remove the situation criteria 7, because there is no overlap if color is the only option.

ok

> My take is that the bad touch double finesse/bluff moves always take precedence over UDD in 4-player or more games.

it is a design goal that conventions always work the same regardless of player count

**Comment by Zamiell** [comment]
actually no, i can't remove criteria 7 because you can perform a bad touch double bluff with color

**Comment by Jayhui-q** [comment]
> i forgot

Honestly, I thought the omission was brilliant! I had to reflect again on why we even excluded rank, which is why I followed with the commentary below it.

> fine

As above, I think we are on different pages. The message above this argues for why we might want to consider rank (and not just color) as a tool for UDD. Apologies for moving the goalpost of the initial proposal, but I think if bad touch 3 double bluff is the aforesaid reason we have resisted against rank, and bad touch 3 double bluff has precedence over UDD, then there is no meaningful difference between rank/color in the interpretability of the clue.

The logic is therefore the following: Is the dupe weird (criteria 1-6)? And, is there no way it is a bad touch double/triple finesse/bluff because Cathy's finesse is not playable or one-away-from playable (criterion 7)? If so, discharge. This is consistent regardless of rank or color.

> it is a design goal that conventions always work the same regardless of player count

Excellent. Definitely agree with this and I think the way it has worked so far has been great. In this case, I think the Bad touch double finesse/bluff should take precedence always. 

> actually no, i can't remove criteria 7 because you can perform a bad touch double bluff with color

Fascinating! I was not aware of this at all - All of my previous discussion has been with the notion that rank must be used for a bad touch double/triple finesse/bluff. If color can be used, we may want to slightly revise the current language for Bad Touch Double Bluff for 3's. To me, the language implies that it can only be done with rank. If I were to guess, this is likely why Indego constrained the UDD to color in her initial proposal as well.

**Comment by Zamiell** [comment]
i think you can only do a *Bad Touch Double Bluff* with color if the card has negative 4 and negative 5, so it is an edge case

**Comment by Zamiell** [comment]
i removed the 7th criteria since that probably won't ever happen

**Comment by Jayhui-q** [comment]
> i think you can only do a Bad Touch Double Bluff on a 3 with color if the card has negative 4 and negative 5, so it is an edge case

Ah. Great point. Looks good to me!

**Comment by Zamiell** [comment]
maybe something like:

- r2 is played on the stacks
- alice clues donald red, touching two red 4s
- bob plays b1 as r3
- cathy plays g1 (from the dupe)

**Comment by Jayhui-q** [comment]
> r2 is played on the stacks
alice clues donald red, touching two red 4s
bob plays b1 as r3
cathy plays g1 (from the dupe)

Donald writes red 5, or otherwise some multi suit. This reads as a pestilent double bluff, as red matched red.

**Comment by Zamiell** [comment]
in no variant, cathy would not play g1 and instead write *Trash Touch Elimination Notes* for r5
in multi, cathy would have to play g1 probably

**Comment by Zamiell** [comment]
> I feel like that makes this move stronger and more applicable?

there is tension between making the move stronger and making the move clearer

**Comment by Jayhui-q** [comment]
> there is tension between making the move stronger and making the move clearer

The trade-off in clarity depends on the precedence of bad touch double bluff with color/rank in relation to the UDD. 
If the precedence of bad touch double bluff is higher than the UDD, then there is no difference in clarity. Bob should check Cathy's hand each time and that determines the UDD interpretation regardless of rank or color.

However, given that rank is much more commonly used for a bad touch double bluff (the matching 2 must be down, or there is negative 4 and 5 on the card), I do see a reduction in needed analysis for the move, as bad touch color is almost always a UDD, and Bob is rarely wrong if he forgets to check.

**Comment by Zamiell** [comment]
let's define this more formally.
we define *4 Double Bluff* as having precedence over in *4 Charm*.
thus:
- whenever a 4 is touched as a *Play Clue*
- and bob sees that it is not a *Reverse Finesse*
- there is a *Lookahead Component* for bob in determining the meaning of the clue.

personally i not a fan of *Lookahead Components*.
i think that a *Lookahead Component* is optimal for the 4DB vs 4Charm case, because 4DB is very common + very useful.
but i am unsure if a *Lookahead Component* is optimal in this case.
the difference being 4DB is extremely common and BadTouchDoubleFinesse is extremely rare.

**Comment by Jayhui-q** [comment]
> they are mental overhead that increases the total amount of mistakes and bombs.

Agreed. To be honest, I am not the greatest fan of the 4 Charm (which is ironic). The same _Lookahead Component_ applies to a self-color ejection. Frankly, I think both of these conventions are at odds, and are rare and confusing, especially to new players. I proposed the above with the assumption that we were mostly fans of those components in order to make more advanced tools (for example, making UDD with rank much more interpretable).

As you said, I think the BadTouchDoubleBluff with color is an extremely rare edge case. I think the BadTouchDoubleBluff with rank is more common than the UDD, but I am just one voice and player.

Given the very valid hesitation on lookahead, I have now come full circle on myself. At the cost of losing the color bad touch double bluff, my formal approach, which removes the lookahead, is the following:
- If two cards are duplicated unnecessarily with rank, it is a bad touch double/triple/bluff.
- If two cards are duplicated unnecessarily with color, it is a UDD.

Where I use the word unnecessarily in this context to refer to criteria 1-6 prescribed above.

This would make bad touch double bluff with color expressly illegal (I suppose not when Bob has no discharge position available).

**Comment by Zamiell** [comment]
> Frankly, I think both of these conventions are at odds, and are rare and confusing, especially to players who are learning.

4 charm is used quite commonly.
scdb is not, so it is a candidate for deletion (after x months).
if scdb is deleted, then scb has no lookahead component.

> If two cards are duplicated unnecessarily with rank 2(on chop)/3/4, it is a bad touch single/double/triple bluff/finesse.
If two cards are duplicated unnecessarily with color, it is a UDD.

yup.
as an aside, bad touch finesses are fairly rare, so i am also open to deleting all of them entirely, and expanding UDD to work in all of those cases.
however, that is not very backwards compatible, so we can revisit that in 6 months time

**Comment by Zamiell** [comment]
one thing that needs to be clarified:

> v. When the efficiency of getting a Double Finesse or Triple Finesse outweighs the disadvantage of potentially having to give a Fix Clue later.

bob is unable to determine if he is double finessed or triple finessed.
thus, there needs to be a "two or more blind plays" rule baked into the convention, similar to how it works with 5ce.
(another possibility is that we use a "three or more blind-plays rule", but that seems incorrect)

**Comment by Jayhui-q** [comment]
> as an aside, bad touch finesses are fairly rare, so i am also open to deleting all of them entirely, and expanding UDD to work in all of those cases.

Interesting -- I am likely wrong then about the frequency of bad touch finesses. One thing to think about is because of the color/rank distinction, Alice gets to pick between rank and color and call for different responses (just like 5CE 5ND). So the expansion to rank would especially help in pink, but otherwise is just covering the blocking rank cases. 

> however, that is not very backwards compatible, so we can revisit that in 6 months time

That's a neat perspective! 

> When the efficiency of getting a Double Finesse...

This is a great point. This is only a concern for the bluff seat, which only slightly reduces the issue. What if Bob should always assume a multiple finesse, if possible? The two scenarios you listed would be exactly the ones where Alice could not give the UDD.

>(another possibility is that we use a "three or more blind-plays rule", but that seems incorrect)

Agree, three blind-plays is too much.

One crazy crazy thought is that if we are willing to delete the bad touch finesses with rank, then color is actually better suited for being hyper-clear about finesses. The double / triple finesses on the same player are simply clandestine. In this case rank - > discharge, color -> finesse. It may be best to just ignore this musing though, because I think I have already over-thought this convention.

**Comment by Zamiell** [comment]
- In order for players to determine whether or not a *Double Finesse* or a *Triple Finesse* is happening, they should use the same *two-or-more-blind-plays* rule that applies to *5 Color Ejections*.
- For example, in a 3-player game (similar to the previous example):
  - It is the first turn of the game and nothing is played on the stacks.
  - Alice clues number 5 to Bob as a *5 Save*.
  - Bob clues number 5 to Alice as a *5 Save*.
  - Bob's hand is as follows: `red 3, red 3, red 4, blue 4, blue [5]`
  - Cathy clues red to Bob, touching the red 3 on slot 1, the red 3 on slot 2, and the red 4 on slot 3.
  - Alice knows that Cathy is violating *Good Touch Principle* and duplicating the red 3. One excellent reason to do this would be to get a *Double Finesse* on red 1 + red 2 into the red 3.
  - However, Alice also knows that she is supposed to use the *two-or-more-blind-plays* rule in this situation. Since Alice would have to blind-play two cards into the *Finesse*, a *Finesse* is unlikely. Thus, this must be an *Unknown Dupe Discharge*.
  - Alice blind-plays her *Third Finesse Position*. It is a blue 1 and it successfully plays on the stacks.

**Comment by Zamiell** [comment]
> What if Bob should always assume a multiple finesse, if possible?

that's certainly an option, but it seems nice to have this governed by the same rules as 5CE

**Comment by mmelwen** [comment]
I dont agree with the 2 blind plays rule
![image](https://user-images.githubusercontent.com/66402571/107133324-a59e0080-68ef-11eb-9fc7-dc5503dd137e.png)
https://hanab.live/replay/427414#11

the 2 clue is bad touch finesse so the red clue should be a UDD

**Comment by Zamiell** [comment]
1) the 2 blind plays rule doesn't apply in this screenshot because bob can already determine that it isn't a Double Finesse or a Triple Finesse.
in other words, the rule only applies if it could be a Double Finesse or a Triple Finesse.
2) time should discard slot 3. did you see the draft i posted above? i believe it covers this

**Comment by mmelwen** [comment]
why we discard trash abnormally? (e.g different that the regular order which would be the older first)?

**Comment by Zamiell** [comment]
because if 3 or more cards are touched as part of the UDD, you need to determine which specific card is duplicated
