### ISSUE TITLE
Loaded white play clues

### ISSUE THREAD

**Issue by rkass** [hanabi/hanabi.github.io#478]
Loaded White Play Clues. Only for the White variant. Expands the ability to give loaded play clues to white cards on chop at the cost of limiting the ability to give loaded save clues.

This would've been useful here: https://hanab.live/shared-replay/384380#14

### White Loaded Play Clues

- A rank clue focusing a player's chop should be interpreted as a *White Loaded Play Clue* if the recipient is loaded, the focused card could be white, and at least one of the following is true:
  
  1. The white card of the rank clued is playable.
  2. The white card of the rank clued is critical, or this was a 2 clue.
- The one exception to the above is for saving 5's in *Early Game*. A clue to a 5 on chop in *Early Game* is not interpreted as a *White Loaded Play Clue* even if the 5 may be white.
- For example, in a 3-player game (*White Loaded Play Clue*):
  - White 2 is on the stacks, green 3 is in the trash.
  - Bob has a clued playable 1 in his hand.
  - Alice clues Bob 3 to Bob's chop.
  - Bob notices that white 3 is playable and that he is loaded, so Bob determines that this is a *White Loaded Play Clue*. Bob writes white 3 on his recently clued card and plays it correctly
- For example, in a 3-player game (*White Loaded Play Clue*):
  - White 1 is on the stacks, white 3 and green 3 are in the trash.
  - Bob has a clued playable 1 in his hand.
  - Alice clues Bob 3 to Bob's chop.
  - Bob notices that white 3 is in the trash, which means that this clue could be a save on a white card (criterion i). Bob determines that this is a *White Loaded Play Clue* and writes white 3 on his recently clued card.
  - Bob doesn't see white 2 on Cathy's finesse, so writes white 2 on his own finesse and plays it correctly
- For example, in a 3-player game (Not a *White Loaded Play Clue*):
  - White 1 is on the stacks, green 3 is in the trash.
  - Bob has a clued playable 1 in his hand.
  - Alice clues Bob 3 to Bob's chop.
  - Bob notices that there is no white 3 in the trash and white 2 is not playable. Bob determines that this is not a *White Loaded Play Clue* and writes green 3 on his recently clued card.

**Comment by Zamiell** [comment]
seems fine

**Comment by Jayhui-q** [comment]
I'm biased because we've played with this, but I like it. 
The way I think about it is that it's a similar line of intuition as the 5 compromise, but that a number clue that could be a save to a loaded player is read as the white card if the matching white card is playable. 

I'm super on board with example 1. Big big fan of that component. 

I think there's some extra complexity that I'm hesitant on regarding if it's not _directly playable_, such as this condition:
> The white card of the rank clued is critical
Or what is noted in the second example.

The application of it would also mean:
w4, b4 in trash. w1 on stacks, Bob is loaded. 
Alice clues Bob's chop with a 4 clue. Bob thinks it could be b4, but knows that w4 is also a possible identity. It satisfies the above conditions and he assumes it's white, thinking it's a w23 finesse.

I feel like it still works, and makes this concept super powerful for white loaded finesses and bluffs, but it is a bit more rigid, especially for players who haven't ever seen it (maybe they wanted to save b4 in advance for a later save clue!). Would definitely like to hear others' thoughts on it.

**Comment by Zamiell** [comment]
I think it is simpler / less confusing to remove the critical criterion.
thus, you can better summarize the convention by saying:
"if it could be a white card, and Bob is loaded, then it is always a *White Loaded Play Clue*"

**Comment by Jayhui-q** [comment]
> "If it could be a white card, and Bob is loaded, then it is always a White Loaded Play Clue, except if it is a number 5 clue during the Low Score Phase."

Agreed. The "critical" criterion just reinforces that Bob is thinking about the white suit as a possible identity of the clue's focus. The way you worded it is exactly the easiest way to sum it up.

**Comment by Zamiell** [comment]
### The White Loaded Play Clue

- *Loaded Play Clues* are "turned on" for white cards.
- Normally, *Loaded Play Clues* are "turned off" in the *Early Game*. However, note that *Loaded Play Clues* **always** apply to white cards, even in the *Early Game*.
- This means that if a player is *Loaded*, and a *Chop-Focused* card *could* be white, then they will always assume that it is a *White Loaded Play Clue*.
- For example, in a 3-player game:
  - White 2 is played on the stacks. Blue 3 is in the trash.
  - Bob has a globally-known playable red 1 in his hand.
  - Alice clues number 3 to Bob, touching a 3 on Bob's chop.
  - Normally, Bob would interpret this as an *Early Save* on the blue 3.
  - However, Bob knows that white 3 is currently playable and that he is *Loaded*. Thus, this must be a *White Loaded Play Clue* on a white 3.
- As an exception, *White Loaded Play Clues* do not apply to number 5 clues in the *Low Score Phase*.

### The White Loaded Self-Finesse

- Since players will always assume *White Loaded Play Clues*, you can also use them to perform *Self-Finesses*.
- For example, in a 3-player game:
  - White 1 is played on the stacks. White 3 and blue 3 are in the trash.
  - Bob has a globally-known playable red 1 in his hand.
  - Alice clues number 3 to Bob, touching a 3 on Bob's chop.
  - Normally, Bob would interpret this as an *Early Save* on either the blue 3 or the white 3.
  - However, Bob knows that he is *Loaded* and that this 3 could be a white 3. Thus, this must be a *White Loaded Play Clue* on a white 3.
  - Bob does not see any white 2's, so he knows that he must have the white 2 as a *Self-Finesse*. Bob blind plays his *Finesse Position*. It is a white 2 and it successfully plays.
- For example, in a 3-player game:
  - It is the first turn and nothing is played on the stacks.
  - Alice clues Cathy red, touching a red 1 as a *Play Clue*.
  - Bob clues Cathy number 2, touching a 2 on her chop.
  - Normally, Cathy would interpret this as an *Early 2 Save* on any 2 in the game.
  - However, Cathy knows that he is *Loaded* and that the 2 could be a white 2. Thus, this must be a *White Loaded Play Clue* on a white 2.
  - Bob does not see any white 1's, so he knows that he must have the white 1 as a *Self-Finesse*. Bob blind plays his *Finesse Position*. It is a white 1 and it successfully plays.

**Comment by rkass** [comment]
> I think it is simpler / less confusing to remove the critical criterion.
> thus, you can better summarize the convention by saying:
> "If it could be a white card, and Bob is loaded, then it is always a _White Loaded Play Clue_, except if it is a number 5 clue during the _Low Score Phase_."

Agreed

**Comment by rkass** [comment]
> > I think it is simpler / less confusing to remove the critical criterion.
> > thus, you can better summarize the convention by saying:
> > "If it could be a white card, and Bob is loaded, then it is always a _White Loaded Play Clue_, except if it is a number 5 clue during the _Low Score Phase_."
> 
> Agreed

Actually I'm not sure if this is clearer. `If it could be a white card` can be interpreted as `given that we play with *White Loaded Play Clues*, could this be a white card`. Which makes me think that even if the target is a non-critical w4, as written in @Zamiell 's revisions, the recipient would think that this is a finesse to w4.

The example below is what I'm referring to above. I don't think this should be a White Loaded Play Clue. I think it should be an Early Save on b4. Under the original text this wouldn't play because it can't be a playable or critical white card.

in a 3-player game:
White 1 is played on the stacks. Blue 4 is in the trash.
Bob has a globally-known playable red 1 in his hand.
Alice clues number 4 to Bob, touching a 4 on Bob's chop.
Normally, Bob would interpret this as an Early Save on the Blue 4.
However, Bob knows that he is Loaded and that this 4 could be a white 4. Thus, this must be a White Loaded Play Clue on a white 4.
Bob does not see any white 2's or white 3's, so he knows that he must have the white 2 and white 3 as a Self-Finesse. Bob blind plays his Finesse Position. It is a white 3 and it successfully plays.

**Comment by Zamiell** [comment]
in the example you provided, i am pretty fine with that being a finesse.
i submit that we don't really need to do early saves that bad, especially if it comes at the cost of adding another exception to the rules

**Comment by rkass** [comment]
> in the example you provided, i am pretty fine with that being a finesse.
> i submit that we don't really need to do early saves that bad, especially if it comes at the cost of adding another exception to the rules

Good with me, let's include that example then to be explicit about it, since stipulating that white 3 is in the trash in the first example muddies the point.

**Comment by Zamiell** [comment]
- For example, in a 3-player game:
  - White 1 is played on the stacks. Blue 3 is in the trash.
  - Bob has a globally-known playable red 1 in his hand.
  - Alice clues number 3 to Bob, touching a 3 on Bob's chop.
  - Normally, Bob would interpret this as an *Early Save* on the blue 3.
  - However, Bob knows that he is *Loaded* and that this 3 could be a white 3. Thus, this must be a *White Loaded Play Clue* on a white 3.
  - Bob does not see any white 2's, so he knows that he must have the white 2 as a *Self-Finesse*. Bob blind plays his *Finesse Position*. It is a white 2 and it successfully plays.

**Comment by Zamiell** [comment]
i changed the example to not have white 3 in the trash
