### ISSUE TITLE
Unknown Trash Charm (UTC)

### ISSUE THREAD

**Issue by piper0** [hanabi/hanabi.github.io#487]
# Unknown Trash Charm (UTC)

- When multiple cards are newly touched with an _Unknown Trash Discharge_, only the focus of the clue is considered to be trash. This means that _Good Touch Principle_ applies to the non-focused cards.

- Therefore, if the non-focused cards touched by such a clue are _also_ trash, a discharge would incorrectly signal that the non-focused cards are useful.

- If Alice is not making a mistake, she must be trying to communicate something different. This should signal a charm on the very next player.

- Since the _Fourth Finesse Position_ card was played instead of the _Third Finesse Position_ card, the player who received the clue will know that _all_ newly touched cards are trash.

Note that unnecessary usage of the UTC has the same extra effect as unnecessary usage of the UTD.

## Example 1

[![image](https://user-images.githubusercontent.com/67833391/107101147-37601d80-67cb-11eb-8363-6bf70041f87e.png)](https://hanab.live/replay/396406#40)

A discharge would promise piper that the t1 is useful, so Kimbi must charm. Note that this is a necessary usage of the move, so piper does not chop move.

## Example 2

[![image](https://user-images.githubusercontent.com/67833391/107101392-0207ff80-67cc-11eb-9f33-1558d5346c08.png)](https://hanab.live/replay/337908#46)

Context: There was a bit of known desync from an earlier trash bluff, and it was unclear to pianoblook if b5 was cm'd. The UTC was therefore necessary from piper's perspective.

**Comment by Zamiell** [comment]
i dont understand example 2

**Comment by piper0** [comment]
If Kimbi discharges in response, y1 will be promised to be useful, so she has to charm.

piper performed an unnecessary trash bluff earlier in the game to cm b5, but pianoblook couldn't know it was unnecessary. He therefore didn't know if cluing blue would correctly focus the b5. He also didn't know if cluing 5 would look like a save clue or a play clue. So he UTC'd it.

**Comment by Zamiell** [comment]
isnt this the same move that piano already posted a while back

**Comment by piper0** [comment]
Do you know the name or the issue ID? I'm not sure what you're talking about.

**Comment by Zamiell** [comment]
not 100% sure, i'll let piano respond

**Comment by piper0** [comment]
You may be thinking of the _Junk Charm_. In the _Junk Charm_, the focused card is playable, but an extra trash card is unnecessarily touched. Bob charms in response to communicate that the focus is good, but the extra card is trash. Pianoblook has changed this to a _Junk Blast_ to make room for the UTC, which we've found to be much more common and useful (despite how sweet _Junk Charms/Blasts_ are).

**Comment by Zamiell** [comment]
> In the Junk Charm, the focused card is playable, but an extra trash card is unnecessarily touched.

isn't that the exact same thing as example 1 in this thread

**Comment by Zamiell** [comment]
oh i see, in this one everything is trash

**Comment by Zamiell** [comment]
this much obsession with trash can't be healthy

**Comment by Zamiell** [comment]
a disadvantage to *Unknown Dupe Discharge* is that sometimes you just need to dupe cards in order to get a finesse or to get the card played, and fuck the duplication, it doesn't matter that much when compared to your primary goal.

in a similar way, a disadvantage to *Unknown Trash Charm* is that sometimes you need to UTD bob and you don't have a lot of options, so you just UTD with ancillary trash, and fuck the duplication, it doesn't matter that much when compared to your primary goal.

this disadvantage is more relevant in e.g. brown.
with that said, not having a reliable way to discharge may be annoying and suboptimal across all variants

**Comment by pianoblook** [comment]
> in a similar way, a disadvantage to Unknown Trash Charms is that sometimes you need to UTD bob and you don't have a lot of options, so you just UTD with ancillary trash

We had that concern too, and for sure there *is** a chance of that. The question is which will be more beneficial at a macro level: the niche situation in which you somehow can't clue a slot 3 card **and** can't find any single discharge opportunities, or a universal Charm?
 
I'd argue three points:

1) It's _quite_ a niche situation to not have any possible way to Discharge a card without picking up ancillary trash. Even in 3 player games, I see options in both the above examples: 3 or 4 to piper in example 1, and red in example 2. In 4 or more players it seems almost impossible - since remember also it would have to be uncluable *and* un-pushable (*and* un Trash Push Dischargeable, if you're really desperate).

2) We currently have zero midgame _Charm_ opportunities, and this gives a _very_ simple and easy way to get a tricky slot 4 card.

3) Getting two known trash out of the deal is nothing to scoff at. Also don't forget that this can absolutely still be used _Unnecessarily_ to get a _CM_ or _Push_ out of the deal too. And two known trash can lead to an immediate OCM payoff too.

**Comment by Jayhui-q** [comment]
First of all. Wow. Why hadn't I thought about something like this? A brilliant mind, piper. 

> Therefore, if the non-focused cards touched by such a clue are also trash

If, _all_ of the non-focused cards are trash, right? If there's one good and one trash touched in it, this is still a discharge.

> which we've found to be much more common and useful (despite how sweet Junk Charms...

Yes. This is far far more applicable than the Junk Charm, in my opinion. 

> The question is which will be more beneficial at a macro level: the niche situation in which you somehow can't clue a slot 3 card and can't find any single discharge opportunities, or a universal Charm?

This is a fascinating question. You could turn it on its head for both 4P and 5P, which is: you can always clue and focus slot 4, but slot 3 is harder to find. This move is definitely more powerful in 3P, where a 4th finesse position exists. 

I will also say that I don't think we really have that many discharge opportunities. Either way, I agree with the general point. UTD seriously changed the game because it gave a consistent discharge. Having a consistent charm option might also be revolutionary. 

> Getting two known trash out of the deal is nothing to scoff at.

Facts. Free mid-game ocm too. It's quite hard to get that opportunity after the early-game.

> Also don't forget that this can absolutely still be used Unnecessarily to get a CM or Push too

Low-key, getting two known trash out of the way is so powerful that I think it's a solid choice even without a CM or Push. Just a thought 

______
One big thing I think to talk about is the following:
If there is no charm slot, then the next player should discharge, right? 

so it would be two unknown trash cards touched -> UTC if charm exists -> UTD otherwise. 
______

Does UTC also apply if the other touched card is known to be trash based on the contents of someone else's hand? Or, based on the negative information on the card? 
____

Altogether fascinating. I'll need to give this some more thought and run some hypos.

**Comment by piper0** [comment]
> If, all of the non-focused cards are trash, right? If there's one good and one trash touched in it, this is still a discharge.

I'd say so. I can imagine context that would make it clearly UTC or clearly UTD, but conventionally speaking, it's probably important for this to be defined as UTD.

> You could turn it on its head for both 4P and 5P, which is: you can always clue and focus slot 4, but slot 3 is harder to find. This move is definitely more powerful in 3P, where a 4th finesse position exists.

I disagree with the idea that you can always clue and focus slot 4 in 4p/5p. Sometimes the resultant bad touch will be a mess to clean up. Sometimes slot 4 is chop moved, and any clue we give will focus the wrong card. I agree that UTC might have more utility in 3p, but I maintain it's wildly useful in 4p/5p as well.

> Low-key, getting two known trash out of the way is so powerful that I think it's a solid choice even without a CM or Push.

Honestly, I agree in some contexts, but I think it's important that UTC aligns with Hyphen-ated unnecessary principles. There's really no reason to complicate that flowchart at this level.

> If there is no charm slot, then the next player should discharge, right?

I'm inclined to say that if there's no charm slot, then Alice just shouldn't be giving this clue. Bob's blind play is communication to Cathy the identity of her cards, and it'd be super funky and frustrating if when Bob only has three finesse positions, Cathy has to write "this could be literally anything" on her cards. Certainly there are emergency situations in which this makes sense, but this should all probably be defined very consistently at the convention level.

> Does UTC also apply if the other touched card is known to be trash based on the contents of someone else's hand? Or, based on the negative information on the card?

🤷‍♀️ Anyone else want to weigh in on this?

---

By the way, just a quick comment – I've found that we _very_ frequently have free choice between UTD and UTC, especially later in the game. This obviously won't be true across the board, but my experience thus far is that UTC really doesn't get in the way of UTD very often at all.

**Comment by Zamiell** [comment]
draft

### The Unknown Trash Charm

- First, see the section on the *[Unknown Trash Discharge](#the-unknown-trash-discharge-1-for-1-form)*.
- Normally, after an *Unknown Trash Discharge*, non-focused cards are known to be "good".
- However, what if a player performs an *Unknown Trash Discharge* where **all** of the non-focused cards are trash? A *Discharge* would incorrectly signal that the non-focused cards are useful.
- Instead, this should signal a *Charm* on the very next player.
- For example, in a 3-player game:
  - All of the 2's are played on the stacks.
  - Alice clues red to Cathy, touching a red 1 on slot 1 and a red 2 on slot 2.
  - Normally, Bob would treat this clue as an *Unknown Trash Discharge*. However, if he *Discharges*, then Cathy will discard the red 1 and mark the red 2 as either a red 3, a red 4, or a red 5, which would be a *Lie*.
  - Instead, Bob knows that this signals an *Unknown Trash Charm*, so he blind-plays his *Fourth Finesse Position*. It is a blue 3 and it successfully plays.
