### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by jian01** [hanabi/hanabi.github.io#490]
Hi, im a spanish native speaker from Argentina and im teaching a lot of friends from here, i was thinking on making a PR working on a progressive translation for the conventions but keeping a reference to the original names (like _chop_, _ocm_, etc.) so everyone can understand the concepts playing with english speakers.

Would this be useful? Is there a way i can make it so wont be a pain to update some convention in the future? A disclaimer saying it may be outdated? Maybe i can just translate the lower levels that should be less prone to changes? Maybe the conventions would be more appealing for spanish speakers if they can read the first levels in spanish and once hooked with the game they can make the effort to continue in english.

**Comment by Zamiell** [comment]
hello jian.
im glad to hear you are spreading the excellent game of hanabi to people in Argentina.
remember to direct your students to our discord server, so that when you are not around, they can play pick-up games with other beginners from elsewhere in the world.

as you can see from [the commit history](https://github.com/hanabi/hanabi.github.io/commits/main), the conventions repo is constantly updated and changed.
this ranges from small typo fixes, to new conventions.
so you would need to volunteer to spend hundreds of hours from now until perpetuity to keep it up to date.

this is probably best done in your own repo.
(it can be under the hanabi organization if you that's what you prefer.)
then, set up alerting so that GitHub emails you on every new commit to this repository.
