### ISSUE TITLE
ooo

### ISSUE THREAD

**Issue by mmelwen** [hanabi/hanabi.github.io#492]
https://hanabi.github.io/docs/level_14/#the-out-of-order-finesse-triple-o--ooo

the reference doesn't include direct play clues, only finesses

**Comment by Zamiell** [comment]
### The Out-of-Order Play Clue (Triple O / OOO)

- Sometimes, a player will have two playable cards in their hand of the same suit, but they will be "blocked", meaning that both a color clue and a number clue will not be able to focus the first playable card.
- One technique to get around this is to give a clue that focuses the wrong card, and then have the next player give a *Fix Clue*. This is called an *Out-of-Order Play Clue* because the cards were originally out-of-order, but the original focus is still playable.
- For example, in a 3-player game:
  - It is the first turn and nothing is played on the stacks.
  - Cathy hand is as follows, from left to right: `red 4, red 1, red 2, red 3, blue 4`
  - Alice clues red to Cathy, touching slot 1, slot 2, slot 3, and slot 4.
  - Bob sees that Alice has indicated to Cathy that she has the red 1 on slot 1. Cathy will go on to misplay the red 4 as the red 1.
  - Normally, Bob would think this is a *Finesse* and try to play the red 1 into the red 4. However, that doesn't make any sense, because Cathy has the red 1, and then Alice would be violating *Good Touch Principle*.
  - Instead, Bob knows that the team should be using Cathy's red 1. Thus, Bob knows that he needs to give a *Fix Clue* to Cathy, because Alice intends for her and Bob to work together.
  - Bob clues number 4 to Cathy, touching the blue 4 and "filling in" the red 4.
  - Cathy is surprised because the card that she thought was red 1 is actually a red 4. Cathy knows that since the red 4 was the original focus of Alice's clue, then it must actually be playable right now. Thus, Cathy must have the red 1, the red 2, and the red 3.
  - Cathy plays the red 1 from slot 2 (the left-most red card that could be the red 1). She will go on to play the red 2, the red 3, and the red 4.
  - Cathy (and everyone else on the team) knows that even though the blue 4 was the focus of Bob's clue, it is not actually playable right now, and was just "collateral damage" of Bob's required *Fix Clue*.

**Comment by Zamiell** [comment]
futhermore:

### The Out-of-Order Finesse Interaction with 5 Color Ejection

* The *5 Color Ejection* takes precedence over the *Out-of-Order Finesse* as long as the two-or-more-blind-plays rule is satisfied.
* For example, in a 3-player game, this would be a *5 Color Ejection*:
  * It is the first turn of the game and nothing is played on the stacks.
  * Alice clues red to Cathy, touching a red 5 on slot 1, a red 1 on slot 2, and a red 2 on slot 3.
  * Bob knows that this could be an *Out-of-Order Finesse*. Specifically, if Bob gives a follow-up number 5 *Fix Clue* to Cathy, then Cathy would play the red 1, Cathy would play the red 2, and Bob would blind-play the red 3, Bob would blind-play the red 4, into Cathy's red 5.
  * However, this line would require Bob to blind-play 2 cards, so Bob knows that he should prefer a *5 Color Ejection* instead.
* For example, in a 3-player game, this would be an *Out-of-Order Finesse*:
  * It is the first turn of the game and nothing is played on the stacks.
  * Alice clues red to Cathy, touching a red 5 on slot 1, a red 1 on slot 2, a red 2 on slot 3, and a red 4 on slot 4.
  * Bob knows that this could be an *Out-of-Order Finesse*. Specifically, if Bob gives a follow-up number 5 *Fix Clue* to Cathy, then Cathy would play the red 1, Cathy would play the red 2, Bob would blind-play the red 3, Cathy would play the red 4, and then Cathy would play the red 5.
  * Since this line only requires that Bob blind-plays 1 card, he knows that it cannot be a *5 Color Ejection*, so Bob performs the *Fix Clue* to allow for the *Out-of-Order Finesse*.
