### ISSUE TITLE
Delete The Trash Pull

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#501]
It conflicts with *Trash Double Ignition*.

**Comment by pianoblook** [comment]
oh lord please don't

**Comment by pianoblook** [comment]
It doesn't conflict because if it's truly a Pull, no one else should be responding.

And if it's _Unnecessary_ and no one else blind-plays a second card, the clued player should just trust it's a Unnecessary Pull.

*UNLESS* the clued player can truly see that Alice had zero other possible _Ignition_ clue available, which I promise is extremely rare

**Comment by pianoblook** [comment]
this has all been covered in #363

**Comment by Zamiell** [comment]
### The Trash Pull Interaction with Trash Double Ignition

- *Trash Pulls* and *Trash Double Ignition* are initiated in nearly the exact same way, so this can be confusing.
- *Trash Pulls* take precedence over *Trash Double Ignition*. This means that if everyone can see that the *Trash Pull* was necessary to "get" a blocking card, then no-one else on the team is promised to have a playable card. (This follows from *[Occam's Razor](level_8.md#clue-interpretation--occams-razor)*.)
