### ISSUE TITLE
Turn unnecessary trash bluff / UTD into true trash push

### ISSUE THREAD

**Issue by florian-5f3759df** [hanabi/hanabi.github.io#502]
**Currently:** When an unnecessary trash bluff / UTD is performed using a card on Donald's chop, it asks for a single extra blind play. If Donald has something playable on his new chop, it's a trash push, otherwise Cathy plays slot 1.

**Proposal:** When an unnecessary trash bluff / UTD is performed using a card on Donald's chop, it becomes a trash push.

**Implication:**
- If the trash pushed card is playable, Cathy does nothing.
- If the trash pushed card is one-away, Cathy plays slot 1 (like a normal _Trash Push Finesse_).
- If the trash pushed card is 2+ away, Cathy ejects (_Trash Push Ejection_).
- If the trash pushed card is trash, Cathy discharges (_Trash Push Discharge_).

If we need a name, we could call it an Induced Trash Push, and then an Induced Trash Push Finesse etc. (Or some other adjective would work too. Extra? Added? Generated?) 
 
In the original proposal by Kakashi and me, we already wanted to configure it like this. At the time, the unnecessary stuff was already a big change, so we kept backwards compatibility with trash double bluff to make it more palatable. Now trash double bluff doesn't exist anymore, and we have double ignitions to get double slot 1 if we want. 

**Example** by Kakashi:
Played on the Stack: g1 & b3
Alice clues green to Donald, the r1 in Bob's hand could've easily been clued and is not blocked
Bob's hand: X - X - r1 - X
Cathy's hand: X - X - r2 - X
Donald's hand: X - X - b2 - g1
Old configuration: Cathy would play slot 1, and Donald marks his b2 as maybe-trash, maybe-good.
Proposed change: Both Bob and Cathy play slot 3, Donald marks b2 as known trash.

In my opinion, the proposed configuration is actually simpler and easier to explain than what it currently is. Namely it can be summarized as 'treat it like a trash push'.

I seem to remember maybe some teams already play like this, so in that case: please share your experience.

**Comment by pianoblook** [comment]
This fits exactly with my proposal for _Unnecessary Trash Compositions (with Off-Chop Trash)_ in the google doc from #479 

I would be a huge fan of both of these changes

**Comment by Dr-Kakashi** [comment]
Example by Lel0uch:

Played on the stack: G4, R1 and O5
Bob's Hand
r2 - r1 - r5 - r1
Cathy's Hand
r3 - b1 - b3 - b4
Donald's Hand
b2 - r3 - r4 - o4
Alice clue's green to donald

O=Omni
Level=19

Current Interpretation: 
Cathy Plays slot 1 and Donald after seeing 2 blind plays does nothing
After Proposal: Bob's blind play is forced.  Donald now knows his chop is trash and will now push.  Cathy is now in a situation where she must do the known trash convention to tell Donald what his pushed card is.  She plays slot 1 to tell Donald to push.

Additional comments on example:
Donald can see that 3's to Cathy would've been a 3 for 1 and it's super unnecessary and overcomplicated to clue his chop as trash just for a 2 for 1.

**Comment by Zamiell** [comment]
it sounds like this would make things more complicated.
lets leave that aside for now.

dictating exactly what cathy should do in this scenario seems really specific.
like, what is the frequency of unnecessary clues that meet this structure? 1 in a 100?
since unnecessary moves were implemented on July 27, 2020, i have not yet seen this situation.
its going to be pretty hard to convince me that we need a new convention for a situation that *i have never seen*.

**Comment by florian-5f3759df** [comment]
> dictating exactly what cathy should do in this scenario seems really specific.
I don't get what you mean here as criticism. I'm saying: Just make it a trash push, nothing more, nothing less. It's not more 'specific' than our current trash push conventions at all.

> like, what is the frequency of unnecessary clues that meet this structure? 1 in a 100?
> since unnecessary moves were implemented on July 27, 2020, i have not yet seen this situation.
> its going to be pretty hard to convince me that we need a new convention for a situation that _i have never seen_.
Firstly, I don't see it as 'new convention' at all, but as slight change (and in my mind clarification/simplification) of a current convention. Notice that the second line of my opening post is shorter than the first, it would make the explanation of the convention shorter and easier to remember. For that reason alone I thought it would be an improvement.

For occurrence: it's little bit of a chicken and egg story, since we haven't been looking for the opportunity yet, so it's easy to not be totally. But it's something that's only relevant in 4p and 5p, and requires a few cards to line up, so it's clearly not something that happens in a majority of the games.

I'll look out for chances in my games, hopefully other people spot them too.

**Comment by pianoblook** [comment]
> For occurrence: it's little bit of a chicken and egg story, since we haven't been looking for the opportunity yet, so it's easy to not be totally.

I definitely remember wishing this *was* how things worked at least a couple times in the past. I'll be on the lookout for examples moving forward!

**Comment by Dr-Kakashi** [comment]
I feel it happens quite often.  Usually occur in variants where there's an abundance of trash and/or there are cards that can be used as trash easily

Omni
Pink
Rainbow 1's
etc.

**Comment by sjdrodge** [comment]
Perhaps I missed it, but is there some compelling reason this is better than the status quo? It seems like getting slot 3+1 or slot 3 + Trash Push is already _very good_ and this proposal would likely block at least as many good opportunities as it would create. How often do you have more than one way to get slot 3+1 such that we would expect this change not to block the most common desired result?

**Comment by pianoblook** [comment]
> Perhaps I missed it, but is there some compelling reason this is better than the status quo? It seems like getting slot 3+1 or slot 3 + Trash Push is already _very good_ and this proposal would likely block at least as many good opportunities as it would create.

1. Compared to a UTD + Trash Push, which is roughly a [(slot 3) + (slot 2-or-3)] play, this change would stay equivalent, just through Cathy's hand instead of Donalds (since Cathy _Ejects_ or _Discharges_ instead of always playing slot 1). 

2. Regardless of whether Cathy _Ejects_ or _Discharges_, Donald gets more information about his hand. In the best case this becomes a 3-for-1 via a _Trash Push Ejection Chop Move_, but even getting an extra known trash can be extremely helpful (mostly for free TOCMs).

3. Compared to [UTD + Cathy's slot 1] that combination could usually be replaced with an _Unnecessary Trash Push_ on Bob's card anyway. Alternatively, just clue Bob's card a(which by definition is cluable) and let him bluff/finesse Cathy's slot 1. 

So at the cost of one way to get a slot 1 blind-play, we get more flexibility and a simpler, more intuitive convention (which is a big deal imo). In my opinion our convention set is already **extremely** optimized towards getting slot 1 blind-plays, so dropping this one edge-case in order to simplify and give more options for cool Ejections and CMs is a big gain in my book.

**Comment by sjdrodge** [comment]
> > Perhaps I missed it, but is there some compelling reason this is better than the status quo? It seems like getting slot 3+1 or slot 3 + Trash Push is already _very good_ and this proposal would likely block at least as many good opportunities as it would create.
> 
> 1. Compared to a UTD + Trash Push, which is roughly a [(slot 3) + (slot 2-or-3)] play, this change would stay equivalent, just through Cathy's hand instead of Donalds (since Cathy _Ejects_ or _Discharges_ instead of always playing slot 1).
> 2. Regardless of whether Cathy _Ejects_ or _Discharges_, Donald gets more information about his hand. In the best case this becomes a 3-for-1 via a _Trash Push Ejection Chop Move_, but even getting an extra known trash can be extremely helpful (mostly for free TOCMs).
> 3. Compared to [UTD + Cathy's slot 1] that combination could usually be replaced with an _Unnecessary Trash Push_ on Bob's card anyway. Alternatively, just clue Bob's card a(which by definition is cluable) and let him bluff/finesse Cathy's slot 1.
> 
> So at the cost of one way to get a slot 1 blind-play, we get more flexibility and a simpler, more intuitive convention (which is a big deal imo). In my opinion our convention set is already **extremely** optimized towards getting slot 1 blind-plays, so dropping this one edge-case in order to simplify and give more options for cool Ejections and CMs is a big gain in my book.

Sold! Great argument.

**Comment by pianoblook** [comment]
By the way, this discussion about tradeoffs of slot 1 vs slot2/3 reminds me of the _Unnecessary Extensions_ proposal from my old Ejection/Discharge doc (link [here](https://docs.google.com/document/d/1n3IjeFZo-VFEf5KSsk9mu_hDjPFvooZjXEuiYk0FSu4/edit#heading=h.b3ar6es9llx4)

> **2. Unnecessary Trash Push Discharge**
- If a Trash Push Discharge is chosen instead of cleanly cluing the ‘gotten’ card directly, one of two things should occur:
- The clued player should plan to Trash Push the next unclued card TWO CARDS LEFT of the clued trash card (this is because the immediate next card is now Known Trash)
- If the Trash Push interpretation wouldn’t work, the immediate next player must ~~blindplay their First Finesse Position to fulfill the Unnecessary Trash Discharge instead.~~ [**update: if the current proposal goes through this would now, thankfully, be calling on Cathy to Eject or Discharge**]

**Comment by florian-5f3759df** [comment]
> By the way, this discussion about tradeoffs of slot 1 vs slot2/3 reminds me of the _Unnecessary Extensions_ proposal from my old Ejection/Discharge doc (link [here](https://docs.google.com/document/d/1n3IjeFZo-VFEf5KSsk9mu_hDjPFvooZjXEuiYk0FSu4/edit#heading=h.b3ar6es9llx4))
> 
That would be moving trash push discharge & bad chop move ejection from the 'known trash' to the 'unknown trash' version of the unnecessary principles. This makes a lot of sense, since the 'actual focus' of the clue was the trash pushed / chop moved card, not the touched known trash. That's a different discussion, but it seems fine & consistent to me.

**Comment by florian-5f3759df** [comment]
Example that kimbi happened to ask about: (Thanks kimbi!)

https://hanab.live/replay/448018#14
Consider hakha cluing 1 to kimbi. Currently it gets g1+bombs n2, after proposed change it gets g1+n1+save on g5 as trash bluff + trash push ejection.

**Comment by florian-5f3759df** [comment]
> > By the way, this discussion about tradeoffs of slot 1 vs slot2/3 reminds me of the _Unnecessary Extensions_ proposal from my old Ejection/Discharge doc (link [here](https://docs.google.com/document/d/1n3IjeFZo-VFEf5KSsk9mu_hDjPFvooZjXEuiYk0FSu4/edit#heading=h.b3ar6es9llx4))

I was confused with a different thing you also proposed at one point... What I should have said was:

If we do that, then we can just replace the whole 'unnecessary move with unknown trash' with the simpler: An unnecessary move that requires Bob already to blind play tells the the team to additionally interpret it as the 'known trash' version of the clue.

**Comment by Zamiell** [comment]
> An unnecessary move that already requires Bob to blind play, and for which this blind play tells the clue receiver about trash, tells the the team to additionally interpret it as the 'known trash' version of the clue.

that's probably good

**Comment by Zamiell** [comment]
florry can u do a pr?

**Comment by florian-5f3759df** [comment]
Yes, no problem.
