### ISSUE TITLE
Rename Known Priority Bluff --> Priority Ignition

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#556]

**Comment by Jayhui-q** [comment]
Hmm. I think it makes sense, but most of the existing ignitions can be on other players (not Bob)

In this case, Bob must play otherwise Cathy will play incorrectly. Just a thought, I'm good with the phrasing either way.

**Comment by Zamiell** [comment]
oh, that's true

i was more thinking of when alice plays a 5 to trigger it

**Comment by Jayhui-q** [comment]
Oh interesting!

Do you think that priority bluffs with 5s should be allowed out of position? I think this is extra confusing because of the inverted priority finesse, but it may be an interesting conversation for a new convention. I personally think the cleanest way to approach this is to leave it as is.

Also, just a heads up, I believe there's a duplicate issue opened for this.

**Comment by Zamiell** [comment]
> Do you think that priority bluffs with 5s should be allowed out of position?

no

> I believe there's a duplicate issue opened for this.

i closed it

>  I personally think the cleanest way to approach this is to leave it as is.

ok
