### ISSUE TITLE
Delete Unnecessary Trash CM Saves [replace with Playful Ignition assumption]

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#615]
Although some things were changed in response to #479, I intentionally didn't touch _Unnecessary Trash CMs_ since it seemed like a bit of a different conversation. As of now, it remains ambiguous to the clue receiver  whether or not the initial blind-play was from a Playful Ignition or a Unnecessary Trash CM (i.e. an "unnecessarily complicated way to save a critical card")

To help make my case, I'll repost some of the language from the Universal CM Doc:

> It is true that we [will] no longer be allowed to UTCM a non-playable critical. Here are a few reasons for why this doesn’t concern us:
> - In many cases, clever players can already just use Rank Choice or other Suboptimal save on a critical card to trigger a blind-play, without resorting to UTCM.
> - The blind-play component only occurs in situations where the card(s) could have been easily saved already, so eliminating this edge-case feels like a very inconsequential loss.
> - For the low cost of disallowing these cases, we get a huge amount of added clarity and tempo. Since this move would now always be a clear and immediate 2-for-1, we strongly believe that narrowing its scope will result in an increase in usage and appeal.

**Comment by florian-5f3759df** [comment]
Agreed. I think it's best to remove the Unnecessary Trash Chop Move because of conflict with the Playful Ignition.

It's technically free real estate then (so could be shifted to a discharge or charm), but I think it's better to not do that now, since it would require a new rule to remember for something extremely rare. So I'd propose to require no response at all, besides the cm itself obviously, if someone does a TCM on a critical card that could be clued directly.

**Comment by pianoblook** [comment]
> So I'd propose to require no response at all

I agree that it seems fine just not being defined / not requiring a blind-play. "Not everything needs to be defined" as they say

**Comment by Zamiell** [comment]
ok delete it then

**Comment by Zamiell** [comment]
submit a pr

**Comment by Zamiell** [comment]
### The Playful Ignition

- If a playable card is on chop, the natural thing to do is to give it a *Chop-Focus Play Clue*. If a player *Chop Moves* the playable card instead, this is very strange. If there is not a good reason to do so, then the cluer is trying to communicate something extra.
- In this situation, they intend for an *Ignition* on the next player. Since a *Chop Move* causes a blind-play, the *Chop Moved* player will know that the *Chop Moved* card is playable.
- For example, in a 4-player game:
  - It is the first turn and nothing is played on the stacks.
  - Cathy's hand is, from newest to oldest: blue 4, blue 4, blue 5, red 1
  - Alice clues number 5 to Cathy, touching a blue 5 on slot 3.
  - It is now Bob's turn. Bob sees that since there were other *Play Clues* for Alice to give, Cathy will interpret this as an *Early 5's Chop Move*.
  - Bob also knows that it is nonsensical to *Chop Move* a playable red 1 - Alice could have just give a red *Chop-Focus Play Clue* to the red 1.
  - Thus, this must be a *Playful Ignition*. Bob blind-plays his *Finesse Position* card. It is blue 1 and it successfully plays.
  - Cathy knows that if this was an *Early 5's Chop Move*, then Bob would not have blind-played anything. Since he blind-played his *Finesse Position* card, this must be a *Playful Ignition*. Cathy blind-plays her slot 4 card (the card to the right of the clued 5).
- Sometimes, it can be useful to *Chop Move* a playable card. Something is only a *Playful Ignition* if there is not some other good reason for the *Chop Move*. Specifically, the player might want to:
  - Avoid violating *Good Touch Principle*.
  - Save a *Delayed Playable* card that is followed by a critical card.
  - Save two important cards when there are a lot of cards to deal with and the team is low on clues.
  - Get a blind-play from *Elimination* when the duplicate is visible.

**Comment by Zamiell** [comment]
#### Interaction with 5 Rank Clues

- Normally, a number 5 rank clue to a 5 that is one-away-from-chop would be either:
  - a *5 Stall*
  - a *5's Chop Move*
  - a *Play Clue* on the 5
- If a *5 Stall* is impossible (i.e. it is not a stalling situation), then a *5's Chop Move* on a playable card would normally be treated as a *Play Clue* on the 5.
- However, for level 20 players, *Play Clues* like this are **turned off**. In other words, every number 5 clue that focuses a 5 that is exactly one-away-from-chop would always be a *5's Chop Move*. This is referred to as the *Playful Ignition Interaction*.
- The *Playful Ignition Interaction* can be tricky for players, since *Playful Ignitions* can look like normal *Finesses*. Players need to remember that the blind-play relates to the card being *Chop Moved*, not the 5 directly.
- For example, in a 3-player game:
  - It is the *Mid-Game*.
  - Red 3 is played on the stacks.
  - Cathy's hand is, from newest to oldest: blue 4, blue 4, blue 5, blue 1
  - Alice clues number 5 to Cathy, touching the blue 5 on slot 3.
  - Bob expected Alice to clue number 1 to Cathy. Thus, this must be a *Playful Ignition*. Bob blind-plays his *Finesse Position* card. It is red 4 and it successfully plays.
  - From Cathy's perspective, she first thought that Alice's clue was a *5's Chop Move*. However, if that were the case, Bob would not have blind-played anything.
  - Furthermore, Cathy knows that *Play Clues* on 5's one-away-from-chop using rank clues are turned off. Thus, Bob's blind-play must indicate a *Playful Ignition*.
  - Thus, Cathy's 5 can be any color (including blue). Cathy blind-plays her slot 4 card.
- Importantly, this interaction is **turned off** in the *End-Game*.
- Note that sometimes, players will use a rank 5 clue to touch an actual playable 5 that is exactly one-away-from-chop. Regardless of whether or not the 5 is playable, the next player needs to react as if it wasn't playable. (This is because it is agreed that all *Play Clue* interpretations are turned off.)

**Comment by Zamiell** [comment]
doc is updated now, let me know if any further edits need to be made
