### ISSUE TITLE
Delete The No-Context Double Gentleman's Discard

### ISSUE THREAD

**Issue by patrickc-dev** [hanabi/hanabi.github.io#643]
Hi. First time posting here. My hanabi ID is MangoPie

We explicitly said The Double Gentleman's Discard is illegal, however we also said that if there is absolutely no context, then it is legal.

Most of the time there are some context, however small for the player discarding the card. And the other players just didn't clocked the context.

I have never seen double gd worked in practice, but have seen tons of bombs from it when players just assume it is a double gentlemen's

**Comment by pianoblook** [comment]
This was already deleted 

https://github.com/hanabi/hanabi.github.io/blob/main/misc/deleted-conventions.md#the-double-gentlemans-discard

**Comment by pianoblook** [comment]
oh I take it back - it's also in the doc, weird

well then I support this lol

**Comment by patrickc-dev** [comment]
lol never seen this page. Yes it is still in the doc for other people reading it
https://hanabi.github.io/docs/extras/discards-misplays/#the-no-context-double-gentlemans-discard

**Comment by timotree3** [comment]
It's very hard to prove that your teammate had no possible way of knowing the identity of their card, especially when more than a couple of turns have been played. I think this goes in the category of difficult context reads that we're often hoping our teammates will make but not so expectantly as to allow critical cards to ride on their chop. 

I think we should delete this convention and that players should usually prefer discarding chop to blind-playing and assuming No-Context Double Gentleman's Discards. (Their chop will be safe since we shouldn't be betting the game on making these reads.)

To give an example of another type of difficult context read: [the deleted Play Elimination convention](https://github.com/hanabi/hanabi.github.io/commit/2e8db9e4db936dde97fd6a702b89fc21f2b82e60#diff-405bca9d4a2d836899e75ade6a464f5125c375f8102da14d8a2d81c10eb8787dL1806-L1810)

**Comment by Zamiell** [comment]
how about just changing the convention such that it only explicitly works on your first turn

**Comment by pianoblook** [comment]
Not weighing in one way or the other, but here are two fun examples:
https://hanab.live/replay/380487#32
https://hanab.live/replay/380487#33

**Comment by timotree3** [comment]
How does the first example work? I think piano could have a pink 2 in slot 2 and kimbi would be certain she had lime 2. Are you assuming piper would clue you on turn 39 if it wasn't in slot 1?

And the second example is not really a double gentleman's discard; before the discard kimbi knows that piano knows it's not n3. kimbi can't blaze so decides to assume she has n3. That's an undefined move regardless of the outcome of this issue.

**Comment by pianoblook** [comment]
> How does the first example work? I think piano could have a pink 2 in slot 2 and kimbi would be certain she had lime 2. 

I'll try to answer in a way that feels most productive to this conversation:

You're right that there is probably some context that I didn't have i2 deeper in hand (from lack of earlier clues), but more generally I felt comfortable playing because of not assuming asynchronous information. 

From my perspective piper marked it as one of two 2s - and he knows that we both marked it as such, as well (and I know he knows etc). So by discarding it, imo, it seemed like a Double Gentlemans

**Comment by timotree3** [comment]
> You're right that there is probably some context that I didn't have i2 deeper in hand (from lack of earlier clues), but more generally I felt comfortable playing because of not assuming asynchronous information.
I think when a gentleman's discard happens and we're not sure whether card was known, we should assume asymmetric information. Not the other way around.

The principle of not assuming asymmetric information is about clue interpretation:

If a clue either requires some context from your hand to work or requires you to blind play *and* if you're supposed to blind play but don't the clue will bomb, then you should blind play.

Your example (and Double Gentleman's Discards in general) are completely different because we already know the discard happened, so pianoblook doesn't have to decide whether there's context in his hand or he has a blind play. He can just ignore it and wait for clarification. (Schrodinger's Cat Principle)

**Comment by sjdrodge** [comment]
fwiw, what timotree is describing is the status quo agreement. It was decided a long time ago that players should be allowed to act on asymmetric information when it comes to Gentlemens' Discards, and therefore only the exact identity of the card is promised, not the entire superposition.

However, there are some rare circumstances that arise where it's just impossible (or nearly so) for asymmetric information to exist that could conceivably collapse the superposition fully.

Personally, I think the phrasing in the document makes this status quo rather clear, but also this is an error-prone agreement, and getting a wide variety of players on the same page about the expected depth of asymmetric reads is tough. Also, even without this entry in the document, a group of players with high trust and a good grasp of context would still be able to field the No-Context Double(Triple) Gentleman's Discard correctly anyway.

So, on balance, I think having this in the document is a small net minus. Let's delete it.

**Comment by pianoblook** [comment]
> Also, even without this entry in the document, a group of players with high trust and a good grasp of context would still be able to field the No-Context Double(Triple) Gentleman's Discard correctly anyway.

That's a nice way of putting it. Any secondary(+) blind-plays that *might* occur wouldn't be directly 'Signaled' via the Discard itself - they would just be a result of skilled players' extrapolation of the logic that allowed it to be known in the first place.

In which case it's probably just bad to have it codified. Any subsequent blind-plays would basically fall under 'Elimination Blind-Plays'

**Comment by patrickc-dev** [comment]
This doesn't help my case, but today we just see a no-context quintuple (5) discard 👍 

https://hanab.live/shared-replay/553256#6
