### ISSUE TITLE
Delete Continuation Clues for Layered Finesses in favor of Finesses with a Fix

### ISSUE THREAD

**Issue by timotree3** [hanabi/hanabi.github.io#646]
[The document states](https://hanabi.github.io/docs/extras/play-clues/#the-continuation-clue-touching-both-inside-and-outside-a-layer) that if a clue prevents you from thinking that your finessed card is where you thought it was, either through positive or negative information, and the clue touches a card outside of the layer, then you should assume that it was a layered finesse followed by a normal play or save clue focused on the card that was outside of the layer, rather than treating it as a fix clue.

The way that people actually play in my experience (including Zamiel) is that nobody gives such "Continuation Clues" for fear that they will look like a fix and that people give fix clues that touch cards outside of the layer routinely.

This convention is particularly bad in variants like omni where if you try to do a finesse with a fix, but then an omni card is drawn, you can no longer give a fix clue without it being interpreted as a continuation clue.

The theoretical downside of deleting this convention is that it prevents some delayed play clues to cards on finesse position and some early saves.

**Comment by mmelwen** [comment]
Totaly in favor on this fixing is far more important than give a delayed play clue.  The only problem I can see is if the delayed play clue is starting a finesse and/or prompt on someone else

**Comment by patrickc-dev** [comment]
Before you post this I didn't know this convention exist, and I agree that everyone I play with is on the assumption if it touch inside a layer just before playing the touched card, it is a fix.

**Comment by Lel0uch-H** [comment]
Most of the players I usually play with already play with the "fix interpretation" rather than the "continuation interpretation". It is sometimes impossible to fix without touching outside the layer.

**Comment by Zamiell** [comment]
> The way that people actually play in my experience (including Zamiel) is that nobody gives such "Continuation Clues" for fear that they will look like a fix and that people give fix clues that touch cards outside of the layer routinely.

dead wrong

**Comment by Zamiell** [comment]
vehemently opposed to any convention that supports people lying to each other, it fundamentally goes against the core of how we play hanabi.

give simple clues, and tell the truth to each other, end of story

**Comment by Lel0uch-H** [comment]
@Zamiell Please post 5 evidence in favor of continuation clues. I am sure I can find more than 5 in favor of fix clues.

**Comment by Lel0uch-H** [comment]
> it fundamentally goes against the core of **how we play hanabi**

Did you mean **how we play** or **how we should play**? Because both mean semantically different things.

I do agree that we should not support conventions that support lying. But we do have the **finesse with a lie component** convention which comes pretty handy in hard variants. Since the convention exists, we should try to make it work rather than restricting it so much that it becomes a negligible occurrence.

**Comment by Zamiell** [comment]
we've been playing with continuation clues for years and they do not make finesses with a fix clue a negligible occurrence

**Comment by Zamiell** [comment]
> This convention is particularly bad in variants like omni where if you try to do a finesse with a fix, but then an omni card is drawn, you can no longer give a fix clue without it being interpreted as a continuation clue.

then use context and disregard the convention in omni, just like you would any other convention that is inconvenient in any particular variant.

**Comment by sjdrodge** [comment]
In terms of "how we play," [Information Lock Principle](https://hanabi.github.io/docs/first-principles#7-information-lock-principle) is one of the _First Principles_. So when Bob receives a clue that is consistent with the possibility that previously given clues didn't require a fix, Bob should not assume fix, instead Bob should just assume it's a normal play clue aka a Continuation Clue.

That said, I've noticed a lot of players are not playing this way, and there are considerable merits to creating an exception to Information Lock Principle for this case (some of which are mentioned above).

My personal opinion is that there's not much in it and I'm happy to play either way, but let's try to get the discussion focused on the merits/drawbacks of the proposal.

**Comment by Zamiell** [comment]
not only does it violate information lock principle but it also violates lie principle

**Comment by Lel0uch-H** [comment]
From the doc: 

> However, some players will occasionally break the rules for the purposes of getting a Finesse.

The existing convention does explicitly say that we violate the lie principle this section: https://hanabi.github.io/docs/level-22/#finesses-with-a-lie-component

**Comment by Zamiell** [comment]
the idea is that players only assume that the lie principle is broken if there is no other explanation, like, for instance, a very normal *Delayed Play Clue*

**Comment by Zamiell** [comment]
if players were to assume a Lie would take precedence over Delayed Play Clue, then that would be a violation of Lie Principle

**Comment by Lel0uch-H** [comment]
Well, then I suppose we need a bit more clarification in the section **finesse with a lie component**. Since every fix to a **lie finesse** can look like a delayed play clue/finesse on the fixed card.

Just a short statement like "When a clue looks like a fix on a finesse with a lie component, or a play clue on the clued card, use context to determine the interpretation of the clue." would be pretty helpful.

**Comment by sjdrodge** [comment]
Whoa whoa whoa. It's definitely not true that "every fix to a lie finesse can look like a delayed play clue." Suppose b1 is played on the stacks and Bob is currently finessed for a b2 and expects it to be in his current slot 2. Bob's current hand is r3 g3 b2 y4. All of the following clues are unambiguously fix clues: blues, 2's, greens, and 3's.

**Comment by Zamiell** [comment]
i added the following bullet point to the doc:

> - Note that since we want to minimize *Lying* as much as possible, *Finesses with a Lie Component* have the **lowest possible precedence**. For example, this means that you can give a *Delayed Play Clue* to a player who is still blind-playing cards without it looking like a *Fix Clue*.

**Comment by Lel0uch-H** [comment]
@sjdrodge 

> "It's definitely not true that ... All of the following clues are unambiguously fix clues: blues, 2's, greens, and 3's."

That is not what Zamiel believes (and what we are trying to convince him against). From whatever I understood from this discussion, Zamiel believes 3 or green would be a continuation clue.

I do agree with @sjdrodge here that all 3 of them are valid fix clues, and fixing while getting an extra card is even better for efficiency reasons, which is the primary usecase for a **finesse with a lie component**.

**Comment by sjdrodge** [comment]
I think you will find yourself mistaken about what Zamiel's position is. A continuation clue looks something like this: b1 played on the stacks, Bob is finessed for a b2, Cathy has a clued b3, Bob believes b2 to be on his current slot 2. Bob's received a blue clue touching slots 3 and 4. There are two possible interpretations for this kind of clue (unlike the previous examples where there's only one possibility: fix). The first possibility is that it's just a fix clue on b2 and the slot 4 card is either b4 or b5. The other possibility is that the original finesse was a valid layered finesse (slot 2 is still playable), and slot 4 is exactly b4.

Under current conventions, Bob is required to assume the latter case thanks to _Information Lock Principle_. This proposal would change that.

**Comment by Zamiell** [comment]
> I think you will find yourself mistaken about what Zamiel's position is

the prophecy has come true

**Comment by Lel0uch-H** [comment]
@sjdrodge When the finesse with a lie component is given, it is not in the cluer's hands which card is going to be drawn next. Hence it makes no sense to consider the newly drawn card as the focus of a play clue, when that could be forced to be touched as part of the fix clue. So the argument stands despite touching **only** within the layer or **inside and outside**.

**Comment by sjdrodge** [comment]
Yep, one of the major merits of this proposed change is that the clue-giver won't get screwed by a freshly-drawn blocker, but I get the sense you may not be taking the time to understand the current conventions around _Continuation Clues_. You might find it easier to communicate effectively about the merits of this proposed change if you take some time to do so.

**Comment by Zamiell** [comment]
lelouch you seem to be confused.
in stephen's hypothetical, it sounds like you think that green would be a delayed play clue, which is incorrect.
(it can't be a delayed play clue because it doesn't get any cards to play)

**Comment by Lel0uch-H** [comment]
Yes, I did understand his position. What I'm trying to make you understand here is that a fix should be a fix despite if it touches outside the layer or not. Because if we always go ahead with "if touches outside, it is treated as continuation" interpretation, the situation that timo describes often occurs where a new card blocks the fix clue interpretation.

When I mentioned that the green clue in Stephen's 1st example can look like a "delayed play clue/finesse", I was trying to make you understand how it does not make sense to interpret it as a delayed play clue if we follow information lock by the book. Finesse with a lie component is an explicit violation of both: lie principle and information lock principle.

**Comment by Lel0uch-H** [comment]
> From whatever I understood from this discussion, Zamiel believes 3 or green would be a continuation clue

I meant to say if Bob draws another Omni card, 3 or green would look like a play clue on the freshly drawn Omni card. (Sorry for being not detailed enough).

**Comment by Zamiell** [comment]
> Finesse with a lie component is an explicit violation of both: lie principle and information lock principle.

no it is not.
you seem to be conflating breaking information lock with violating information loc principle.
read: https://hanabi.github.io/docs/level-3/#breaking-information-lock

**Comment by Lel0uch-H** [comment]
> you seem to be conflating breaking information lock with violating information lock principle.

That is not true.

In game example:

Turn 5: finesse with a lie component for b1 and b2 is given:

![Screenshot (16)](https://user-images.githubusercontent.com/81278716/116652851-a781d800-a9a3-11eb-9f8b-19fb7bb959b0.png)


Turn 8: The fix for the finesse is given using a rank 3 clue:
![Screenshot (17)](https://user-images.githubusercontent.com/81278716/116652927-ced8a500-a9a3-11eb-93c4-48d93d360848.png)


Now let's do a hypothetical where dobi draws y3: instead of b2:

![Screenshot (18)](https://user-images.githubusercontent.com/81278716/116652975-eadc4680-a9a3-11eb-9feb-1e66b0b15dc2.png)

Due to the nature of the pink variant, the rank 3 clue does not **break information lock** for dobi in either case, since pink cards touch all ranks. dobi's information lock would say this about the state of his hand:

In the real game case:

![Screenshot (20)](https://user-images.githubusercontent.com/81278716/116653350-a00efe80-a9a4-11eb-812d-22847e72c999.png)

In the hypothetical case:

![Screenshot (19)](https://user-images.githubusercontent.com/81278716/116653214-58887280-a9a4-11eb-9938-ecbea7e7d50c.png)

So for the finesse with the lie to work in game, dobi has to realise that "information lock that his slot 2 and 3 are playable" is violated.


[Link to real game: https://hanab.live/replay/515509]

**Comment by Aigul9** [comment]
Continuation clues can be given after the card is played, while fix clues are urgent, so it makes more sense to change the convention. And if a fix clue will stop clue-receiver from playing cards in the layer, it should call for an additional blind-play(s).

**Comment by Zamiell** [comment]
> So for the finesse with the lie to work in game, dobi has to realise that "information lock that his slot 2 and 3 are playable" is violated.

what you've linked does violate information lock principle, but it is not a valid finesse with a lie component.
it is illegal and dobi will bomb.
come up with some other name.
a **real** finesse with a lie component would not violate information lock principle.
an example of this is cluing green in stephen's hypothetical

**Comment by Zamiell** [comment]
> Continuation clues can be given after the card is played

firstly, this is a dangerous generalization to make, as it is often not true.
secondly, it sounds like you are thinking about this in the context of a hard variant.
remember that the hyphen-ated conventions are optimized for getting the maximum score in a no variant game, not a hard variant.
no variant does not require any more efficiency to be able to win.
what it does require is a good deal of discard modulation in order to prevent bottom deck losses.
having the ability to give delayed play clues for the purposes of orchestrating safe discards does fall in line with our overarching goals here.

**Comment by Zamiell** [comment]
RE: lelouch
another point of confusion might be that we are not optimizing the conventions for in-game value.
our conventions are intentionally designed to be suboptimal in favor of other values - fun & simplicity.
if the thrust of my argument is that a particular proposal goes against two axiomatic foundations, then we need to grapple with whether the expected value increase is more important than the other cons, not just focus on which configuration is more optimal

**Comment by Zamiell** [comment]
lelouch isn't responding so i will close this

**Comment by Lel0uch-H** [comment]
Why does me not responding make this issue stale? The issue was raised by @timotree3 not me.

And to respond to what @Zamiell said before, all I have to say is please stop saying "we are optimizing the conventions for no variant". If that is the case, finesse with lie component should not even exist since it would be such a rare occurrence in a no variant game as a "necessary" move.

When such a convention exists, it exists by definition to solve the problem of efficiency in harder variants. The fact that you dislike the idea of lying to teammates does not change the fact that the suggested configuration is the one that the wider community has considers more optimal for harder variants.

**Comment by Zamiell** [comment]
> The issue was raised by timotree3 not me.

he hasn't responded to any of the discussion, which probably makes it stale

> If that is the case, finesse with lie component should not even exist since it would be such a rare occurrence in a no variant game as a "necessary" move.

finesses with a lie component are often useful in no variant games.
there is a simple proof for this: the idea was codified into a convention prior to the creation of any additional variants.

if that you think that finesses with a lie component decrease win-rate of no variant, then that is a great reason to open a new github issue proposing that they be deleted and/or moved to a hard-variant-only convention.

> The fact that you dislike the idea of lying to teammates does not change the fact that the suggested configuration is the one that the wider community has considers more optimal for harder variants.

to be clear, tim's convention proposal is targeted at all games.
if you think that deleting continuation clues is a good idea when playing harder variants, then it sounds like we should probably re-submit this proposal as a hard-variant-only convention.
(but in very hard variants, people already play this way, so it strikes me that such a proposal would be pointless)

**Comment by Zamiell** [comment]
> Continuation clues can be given after the card is played, while fix clues are urgent, so it makes more sense to change the convention.

that goes against the goals of no variant.
remember that NV is about orchestrating safe discards - it is a design goal that players can give delayed play clues as a means of accomplishing discard modulation.
in the reconfiguration, such a player would be forced to discard.
