### ISSUE TITLE
Deprioritize Self-Finesse over clear Focus Inversion

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#647]
As discussed in #convention-questions today, it seems unnecessarily complicated + restrictive to now allow simple rank focus inversions when no risk of misplay is present.

For example:
> 4p game. r2 is down.
> Bob has negative red on his slot 2, 3, and 4 cards.
> Cathy clues 3 to Bob, touching **slot 1** and slot 4 (chop)
> Normally this would focus on slot 4, but in this case Bob sees that it cannot be r3.

So via Occam's Razor / 'assume Direct Play Clues over finesses', it seems as though Bob should simply _Focus Invert_ and play his slot 1.

But:
- The last bullet in the [Focus Inversion](https://hanabi.github.io/docs/level-11/#focus-inversion) entry reads, "Note that Self-Finesses with rank **always** take precedence over Focus Inversion. 
- Zamiel further clarified that this means that the self-finesse interpretation should "take precedence over Occam's Razor."

I guess I just propose that this seems unnecessarily confusing and the simpler interpretation would be to just let Bob _Invert_, and not assume self 3-bluff or w/e

**Comment by Zamiell** [comment]
repeating myself from discord:

the bullet point in question is:

>  Note that ***Self-Finesses* with rank always take precedence over *Focus Inversion***, which is a specific case where *Occam's Razor* does not apply.

the bullet point is an artifact of how we generally play.
self-finesses are extremely common and focus inversion is extremely rare.
even if this bullet point did not exist in the doc, because of how *Frequency Bias* works, players would act in this exact way anyway.
thus, while i am sometimes in favor of restructuring things in the doc to be more axiomatic, i don't think it helps us in this situation

**Comment by pianoblook** [comment]
Responding to @Zamiell's point on discord:
> the rule is that way because of how we generally play
> self-finesses are extremely common and focus inversion is extremely rare

It certainly makes sense that F.I's would be extremely rare if they're so often explicitly prohibited in the F.I doc! 

In other words I feel like they'd be a lot more common if this arbitrary "assume self-finesse over direct (but inverted) play clue" rule didn't exist.

**Comment by pianoblook** [comment]
Correct me if I'm wrong, but it sounds like you're saying it should stay as is mostly due to historical bias? As in, folks are very accustomed to assuming 3-bluff over Focus Inversion?

If so that is fair, and I definitely can imagine plenty of bombs cropping up from changing this assumption.

It is unfortunate, though, since assuming Focus Inversion is probably much more useful strategically

**Comment by Zamiell** [comment]
> In other words I feel like they'd be a lot more common if this arbitrary "assume self-finesse over direct (but inverted) play clue" rule didn't exist.

as a group, should our goal be to increase the frequency of focus inversion?
i'm not so sure.
it seems to me that focus inversion is one of the "conventions" that results in a high probably of mistakes and lost games.
they are difficult to intuitively see, and difficult to reason about.
usually, players only resort to focus inversion if it is pretty obvious what is going on and there are no other alternate explanations, which puts them in a good spot as far as I am concerned.

> Correct me if I'm wrong, but it sounds like you're saying it should stay as is mostly due to historical bias?

no, i am saying that it should stay as is because of *Frequency Bias*.
deleting the bullet point would pave the way to make *Focus Inversion* for frequent, but the increased frequency would still be tiny when compared to the amount of *Self Finesses* that occur, so it doesn't solve this problem.

**Comment by pianoblook** [comment]
I don't think I understand how Frequency Bias should play a role in the discussion. The main outcome of this added restriction is basically saying, "Assume Self-Finesse over Direct Play Clue".

That's fine, I guess, but what about this example:
> b2 is down
> Alice clues 3 to Bob's chop - he has no negative information on it

*certainly* you'd agree that Bob should not assume self-finesse or 3-bluff here, right? It's very obviously a direct play clue on b3.

So if we can agree on that, why should it be any different if a second 3 is involved, and one of them just happens to be known *not* b3?

**Comment by timotree3** [comment]
3 thoughts:

1. From a value perspective, usually the cards that this change would help us play clue are in slot 1 (since they have less negative info than the rest of the hand). A convention which makes it easier to play cards in finesse position but harder to play cards in second finesse position is a bad tradeoff, since in a 3+ player game, there will usually be efficient alternatives for getting slot 1.
2. From a clarity perspective, there's an issue with how much focus inversion demonstrates. For example:
    1. Alice gives this 3 clue to Bob and Bob focus inverts and plays slot 1. 
    2. Now the team can't distinguish between:
        - the clue being focused on slot 4 as a finesse on them + Bob having some context that allowed him to play slot 1
        - the clue being focused on slot 1 and not finessing anyone
    - I think this problem is similar to prompt bluffs.
3. From a clarity perspective, there's an issue of collective burden.
    1. In a 6 player game, Alice gives this 3 clue to Frank.
    2. Bob has to notice that Emily's chop and negative info, instead of playing into a finesse/bluff
    3. Cathy has to notice the negative info
    4. Donald has to notice the negative info
    5. Emily has to notice the negative info
    - Suppose 1 in 20 games each of these players misses negative info
.95 * .95 * .95 * .95 *.95 = 77% chance of this clue succeeding. Not very good.

**Comment by Zamiell** [comment]
> I don't think I understand how Frequency Bias should play a role in the discussion. The main outcome of this added restriction is basically saying, "Assume Self-Finesse over Direct Play Clue".

it has a role because of the first sub bullet of the 2nd goal.
for example, we deleted the convention called the *Weak Prompt* because it violated this sub bullet.

> certainly you'd agree that Bob should not assume self-finesse or 3-bluff here, right? It's very obviously a direct play clue on b3.

yep

> So if we can agree on that, why should it be any different if a second 3 is involved, and one of them just happens to be known not b3?

i don't think the progression you are laying out here is very compelling.
i could equally establish an alternate progression like so:

example 1:
- 3 player game
- blue 2 is on the stacks, and all other 1's are played
- bob has a 3 on chop with a negative blue clue on it
- Alice clues number 3 to bob, touching the 3 on chop and that's it
- Bob knows this must be a self finesse and blind-plays blue 2 from his *Finesse Position*

example 2:
- 3 player game
- blue 2 is on the stacks, and all other 1's are played
- Bob has a 3 on chop with a negative blue clue on it
- Bob also has a 3 on slot 1
- Alice clues number 3 to bob, touching the 3 on chop and the 3 on slot 1
- Bob knows this must be a self finesse and blind-plays blue 2 from his *Finesse Position*

using your own words against you, "why should it be any different if a second 3 is involved?"

**Comment by Zamiell** [comment]
agree with all 3 of timo's points.
point 3 relates to the general theme of minimizing the frequency of focus inversion, not increasing it

**Comment by pianoblook** [comment]
> 3. From a clarity perspective, there's an issue of collective burden.
> [...]
>    * Suppose 1 in 20 games each of these players misses negative info
>      .95 * .95 * .95 * .95 *.95 = 77% chance of this clue succeeding. Not very good.

I love this point - I've been meaning to write a doc about proper expected value of clues when factoring for % mistakes (even when very small). 

So right off the bat this point is quite convincing, as sad as it may be. From a general community convention perspective, I agree that there generally will be sufficient risk that someone would fuck up.

I'm gunna close this issue, though I do think there's some value in responding to the other 2 points:

--------

> 1. From a value perspective, usually the cards that this change would help us play clue are in slot 1 (since they have less negative info than the rest of the hand).

Definitely disagree here, since the real 'value' of this sort of clue - much like any 3-bluff, for example - is mostly the opportunity to touch the non-playable 3 on chop while you have an opportunity. Requiring a 3-for-1 instead of the simple 2-for-1 seems greedy; I'll always be happy to get to do a 2-for-1 that 'gets' a potentially hard-to-save 3 instead of a 3-for-1.

>  2. From a clarity perspective, there's an issue with how much focus inversion demonstrates.

This just seems like an extension of the 'collective burden' issue from above. If everyone was paying full attention and noticed the (requisite) negative information that allowed for the inversion to occur, no further blind-plays would occur
