### ISSUE TITLE
Convention Proposals: Junk Discharge & Charm (with 1's)

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#653]
All the recent talk about which (presumed) Trash cards players should be expected to discard in what order is leading to situations that I believe are sometimes unintuitive and error-prone. 

One possibility is what it looks like Zamiel just proposed, which is just to turn off the ability to TOCM at all in some cases. Another is keep things as is, which I do agree has been leading to some amount of confusion and mistakes.

While we're all on the topic, this felt like as good a time as any to propose something "new", at least for the doc. This is how kimbi&piper&I have been handling almost all 1's clues that have a mix of trash and non-trash:

### Junk Discharge (for 1's) credit to avanderkru)
- If two 1's are newly touched with a rank 1s clue while the focus is trash, Bob is obviously meant to respond in some way.
- But what if the *non-focused* 1 is actually playable? In this case, Bob cannot simply blind-play slot 1 because the clued player will falsely assume all their 1's are trash, as part of normal _Trash Bluff_ or _Finesse_
- Therefore, this is calling for a _Discharge_. Afterwards, the clued player will know that only their Focused 1 should be assumed Trash.

In-game examples: 
https://hanab.live/replay/410953#8
https://hanab.live/replay/400719#7

### Junk Charm (for 1's)
- If a playable 1 is clued (as the focus), this would be very strange if the clue intentionally picks up one or more other _trash_ 1's that would require another clue to _Fix_ in order to not misplay.
- Therefore Bob should respond in some way - but if he plays normal _Finesse_ position the focus (good) 1 will be _Promised_ as trash. Further, if he _Discharges_ it will look like a _Junk Discharge_.
- Therefore Bob should _Charm_ to signal that the ancillary 1 is trash.

In-game examples:
https://hanab.live/replay/411814#6

**Comment by Zamiell** [comment]
kinda similar to #399 isn't it

**Comment by pianoblook** [comment]
> kinda similar to #399 isn't it

Yep absolutely! Even though we transitioned to Unknown Trash Charms, we realized that the Junk Charm still works for specifically Rank 1 clues, since obv a _trash finesse_ is all that's necessary to promise all the clued 1s as trash

**Comment by pianoblook** [comment]
By implementing these two conventions we now have a complete 2x2 action/reaction matrix to 1s clues:

Focus good, nonfocus good = no reaction
Focus trash, nonfocus trash = trash finesse/bluff
Focus good, nonfocus trash = Charm
Focus trash, nonfocus good = Discharge

**Comment by Zamiell** [comment]
it sounds good but i worry that it will bloat the doc

**Comment by Zamiell** [comment]
does anyone else think that this is good enough to warrant putting in the doc for general-purpose use

**Comment by iamwhoiamhahaha** [comment]
i like them

**Comment by pianoblook** [comment]
I'll ping @Jayhui-q on this one too, since I first encountered the rank 1s UTD watching them play.

Also reading back through the proposal, I should clarify that the _Charm_ version should obviously only work if the secondary 1 *would* be considered playable if Bob doesn't respond in some way (otherwise it's fairly common to want to pick up the extra trailing trash for chop protection duties)

**Comment by Jayhui-q** [comment]
Thanks for the ping! 

Very on board with this, of course. 

It might be worth mentioning that we don't restrict this idea to 1-rank clues when we play. The premise for calling for a discharge originates from us finding that lying about the trash-ness of cards is much too dangerous. 

For example, if all r2 and all 1s are on the stacks and Alice clues Cathy a 2 (the focus of which is r2, and it also touches a good 2), then Bob would discharge. The same would be true of any clue, _even if only one blind-play is required to demonstrate that the focus is trash_. 

This system of trash signals I think is a super natural extension of existing UTD/ Trash Bluffs. I am very in favor of it, especially as a tool outside of just 1s.

A small downside that hasn't been brought up is the case where the blind-played card is the "good card" that was touched. That is, the blind-play from finesse conveys the right trash signal after the blind-play. I personally do not think this is a big loss because it is usually able to be bluffed or directly clued.
______

Junk Charm with 1s seems a bit too niche for me personally, but I will keep my eye out for them now. Might be a cool interaction with pink to be had.

**Comment by Zamiell** [comment]
submit a PR

**Comment by Zamiell** [comment]
if you don't finish your PR by august 10th, then I will close this issue

**Comment by pianoblook** [comment]
Fixed the PR by just fudging the attribution for the Junk Discharge, which was causing the error. I'd be super appreciative if someone with the coding capabilities could simply edit avander & rkass 's names into the file <3
