### ISSUE TITLE
New hard variant convention: TCCM even if it gets 2 units of tempo

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#658]
The [convention](https://hanabi.github.io/docs/level-6/#the-double-tempo-clue) states this:

> Typically, when a Tempo Clue is given that touches two or more cards, it means that all of the cards touched are playable in order from left to right.

In my experience, this is too rare to occur, especially for rank clues.

Suppose a game where not all the 1s have been played and the player has a bunch of 2s and a critical card right after that:

Played: r1, y1, b1

Bob's hand:  r4 g5 [2]r [2]g [2]b

In such cases, the rank 2 reclue conventionally says all of r2, g2 and b2 should play, which is so much more unlikely than only the left-most card is playable and the chop is important/critical.

I propose that we change this behaviour to a single tempo clue on the left most touched card and make it a tempo clue chop move.

**Comment by pianoblook** [comment]
I'm not convinced that the *opportunity* to double tempo clue cards doesn't come up fairly regularly, it's just that people might not feel very excited to give the clue - there's a lot of potential greed in the idea that you can wait for the following connector to show up and just tempo them for free anyway. Or say for 2s, a lot of greed to just wait for all the 1s to get played and get to played for free.

Personally I think it's just an underutilized convention

**Comment by Lel0uch-H** [comment]
The urgency to get a card played and cause a single chop move seems to be more than the urgency to play 2+ cards that lead nowhere. Hence, the proposal makes sense in my opinion.

Like you said, people might not feel very excited to give such a clue, because such a clue does not meet MCVP (gets no "new cards played). Getting a CM out of this instead seems to be better value both from a safety and efficiency perspective during the game.

**Comment by sjdrodge** [comment]
This is a relatively rare situation (that a re-clue cannot be given that gives additional identifying information on the card), but TCCM is more useful than double tempo, so it makes a lot of sense to cater to that case. The current agreement strikes me as an artifact from the old old old days when people weren't even sure they wanted TCCM as a convention so a compromise was created.

**Comment by Zamiell** [comment]
if you only want one card to play, focus the specific card.
if you want all cards to play, then focus all of them.
the *default* case is that either clue will not be blocked, the *special* case is that one of the clues is blocked.
the current convention configuration is (rightly) tuned for the default case.
if you configure the conventions for the special case, then you lose the ability to perform double tempo clues 100% of the time, for the gain of being about to perform TCCMs +X% of the time, where X seems likely to be in the 10-20% range
that reconfiguration doesn't sound very beneficial to me

**Comment by Lel0uch-H** [comment]
In the "migration from BGA" document, we have clearly mentioned that Hyphenated conventions are tuned more towards efficiency than tempo. Getting tempo on cards which are leading nowhere seems opposed to that statement, and the configuration I am proposing has greater merits than pure useless tempo.

**Comment by Zamiell** [comment]
be careful with your words - efficiency isn't relevant here.
TCCM is a 0-for-1.
DTC is a 0-for-1.
both of them have benefits *other than* tempo. compare and contrast those benefits without bringing up efficiency, because efficiency isn't relevant

**Comment by timotree3** [comment]
> both of them have benefits other than tempo
What is the benefit of a DTC besides tempo?

**Comment by Zamiell** [comment]
i meant other than efficiency

**Comment by Lel0uch-H** [comment]
> TCCM is a 0-for-1.

A CM is not exactly a 0-for-1. CM'd cards can often blind play during the later part of the game. @Zamiell In game reviews with you, I have myself heard you counting the value of a CM as 0.5 if not a full 1.

**Comment by Zamiell** [comment]
> A CM is not exactly a 0-for-1. CM'd cards can often blind play during the later part of the game.

i agree that chop moved cards *sometimes* blind-play.
however, this is the *special case*, and not the *default case*.
the default case is that you must spend a clue to get the card played.
for this reason, it is much simpler to assign a value of 0 than some arbitrary, fractional value on the order of ~0.15.
for the purposes of this specific discussion, arguing that getting an extra ~0.15 efficiency is more in line with the group's overarching goals of "high efficiency" doesn't strike me as a particularly good argument.
the group has many goals, which are all explicitly outlined on the convention goals page, and we should use that as a basis for our reasoning instead of an off-hand comment in a BGA tutorial.

>  @Zamiell In game reviews with you, I have myself heard you counting the value of a CM as 0.5 if not a full 1.

you are likely mistaking me for someone else as i have never counted a CM card as a 0.5 for 1.

**Comment by vEnhance** [comment]
> be careful with your words.
> TCCM is a 0-for-1.
> DTC is a 0-for-1.
> both of them have benefits _other than_ efficiency. compare and contrast those benefits without bringing up efficiency, because efficiency isn't relevant

I think the benefit of TCCM is that it chop moves a card that might not otherwise be eligible to be saved ;) I don't know if we have a word that means "protecting cards" (this seems slightly different than Tempo).

>  if you configure the conventions to optimize for the special case, then you lose the ability to perform double tempo clues 100% of the time, for the gain of being about to perform TCCMs +X% of the time, where X is the percentage of time that the clue is blocked, which seems likely to be in the 10-20% range

I am a bit skeptical that X <= 20, not sure if others agree. If I'm in a situation where red is going to touch Bob's r2 and r3, then I'd have to use number 2, so for this to work, clue receiver must have no other 2's.

To make things concrete, I think we have something akin to the following table (assume we never want to chop move a trash card, since I am not sure we want bad CM ejection flying around here...)

|#|Bob's touched red cards|Bob's chop|2 clue blocked|Status quo|Proposal|
|--|----|----|----|----|----|
|1|r2 r3|trash|no| DCTM | :( |
|2|r2 r3|trash|yes| DTCM | :(  |
|3|r2 r3|useful|no| DCTM or TCCM | TCCM |
|4|r2 r3|useful|yes| DCTM | TCCM |
|5|r2 r4|trash|no| none | none |
|6|r2 r4|trash|yes| none | none |
|7|r2 r4|useful|no| TCCM | TCCM |
|8|r2 r4|useful|yes| :( | TCCM |

I think row 8 may occur about as often as row 1 and row 2 because, although clues being blocked is not too common, it's also not that common Bob has exactly r2+r3 as opposed to r2+r4, r2+m3, r2+o5, etc.

Moreover, in rows 1 and 2 I don't really feel excited to give a DTCM anyways if I can't see r4 *and* Bob is discarding trash anyways. I would usually rather be greedy like piano suggests. And in row 3 I'm okay letting DCTM go in favor of actually chop-moving the card that I care about and only getting one card to play.

**Comment by Zamiell** [comment]
the table is a little confusing.
you should rename "status quo" to "possible clues to give" and ":(" to "no possible clues"

**Comment by Zamiell** [comment]
>  don't know if we have a word that means "protecting cards" (this seems slightly different than Tempo).

yes, it is obviously different from tempo. the phrase that we typically use is "orchestrating safe discards".
a fair way to "compare and contrast the benefits" would be to state it as follows:

- adding more TCCM orchestrates safer discards by A
  - this corresponds to row 8
- adding more TCCM increases efficiency by a marginal value that isn't relevant
- removing all DTCs removes player flexibility by B
  - this corresponds to row 3
- removing all DTCs removes tempo by C
  - this corresponds to rows 1, 2, 3, and 4
- removing all DTCs reduces safer discards by D
  - this corresponds to rows 1 and 2 (e.g. alice is forced to discard a desirable card for the team)

notice that D counteracts the positive effects of A.
depending on your assignment to the weight of the rows, the effect of D may even completely counteract or overtake A.

**Comment by pianoblook** [comment]
To toss out another point, giving someone a DTCM does a *lot* to protect their chop anyway. Giving them two rounds of plays will (a) keep them occupied while they draw new cards, (b) give the team more time to get the useful card through other means, and (c) likely make them extremely spooked in the first place without resorting to a full-blown CM

**Comment by iamwhoiamhahaha** [comment]
I'm fine with the proposal. I personally seldom do *Double Tempo Clues*, because they are not very useful in hard variants imo. I suggest to keep *Double Tempo Clues* in easy variants; while in hard variants, it becomes a single tempo with a single chop move as lel0uch proposed.

**Comment by Zamiell** [comment]
i agree with jeff, and it looks like several others do as well, although i wish they would post explicitly instead of using emojis
lelouch can you submit a pr for that?

**Comment by Lel0uch-H** [comment]
Sure will do that.
