### ISSUE TITLE
Proposal: Modified 3-bluffs in Up or Down

### ISSUE THREAD

**Issue by Eliclax** [hanabi/hanabi.github.io#672]
Assuming that crit 4-bluffs are still on (once the direction of a suit has been decided), it makes sense to replace 3-bluffs (which are turned off) with crit 3-bluffs, perhaps only available with colour as well.

Additionally, might it make sense to be able to use 3s to trigger a 3-double-bluff, in a similar manner to how we use 4s to trigger a 4-double-bluff? Such a bluff, when clued with colour, would result in a known 3-double-bluff as opposed to a superposition of 3- and 4-double-bluff, since the latter can only happen when exactly one card in that suit has already been played.

(Here I am using "4" to mean the fourth card of a suit to play onto the stacks, which may be a 2.)

**Comment by Zamiell** [comment]
the cost doesn't seem worth it

**Comment by pianoblook** [comment]
> the cost doesn't seem worth it

What's the added cost, compared to critical 4(/2) bluffs? Or do you think that should also be turned off?

**Comment by Zamiell** [comment]
> What's the added cost

complexity

> compared to critical 4(/2) bluffs?
 
 it is more complex than both of those

> Or do you think that should also be turned off?

i think turning crit 4 bluffs off would be added complexity, so i would be against that

critical 2 bluffs are not listed on [this page](https://hanabi.github.io/docs/variant-specific/up-or-down/), so they should not be used

**Comment by pianoblook** [comment]
turning critical 2s off but keeping 4s on seems super arbitrary + an extra type of complexity. 

The official U|D page is pretty sparse, so I sort of just assume some rarer conventions aren't specifically covered. For example, are 2 double bluffs not allowed just because it's not listed?

**Comment by Zamiell** [comment]
> For example, are 2 double bluffs not allowed just because it's not listed?

that doesn't make sense, it would either be a finesse or a pestilent double bluff

**Comment by pianoblook** [comment]
So why wouldn't a 2 clue just be a single bluff? All possible double bluffs are specifically outlined in the normal convention doc. The U|D doc doesn't *specifically* describe that _The 2 Double Bluff_ exists.

I hope you'd agree that's silly, though, and that it follows from our normal convention set that normally a two-away 2 isn't a valid single bluff target.

... But normal conventions *also* describe _Critical 4 Bluffs_ as being a valid single bluff target. So, therefore, one of these two facts needs to be true, but both can't be true:
(A) all 2s are just single bluff 
or
(B) critical 2 bluffs are on

**Comment by Zamiell** [comment]
> The U|D doc doesn't specifically describe that The 2 Double Bluff exists.

they you should not do it
if you want to do it, then open an issue and make it part of the doc

**Comment by florian-5f3759df** [comment]
I'm surprised by those statements, since I was under the impression that we were already playing with two-away 2 double bluffs since forever.

My opinion: there should be basically no asymmetry between 2s and 4s, and 1s and 5s. A 1/2 in a suit that goes down, is equivalent to a 4/5 in a suit that goes up. So if 4 double bluffs exist in the variant, 2 double bluffs also exist in the variant. Same for critical 4 bluffs <-> critical 2 bluffs. Conventions are basically always on for both (or off for both, like 2 saves).

**Comment by Zamiell** [comment]
if what you describe were true, then there would be no need to have a section in the docs called "1's Color Ejection (1CE)".
that section would be superfluous.

if you want to remove the asymmetry then lets open an issue + a PR

**Comment by Lel0uch-H** [comment]
It all goes down to how verbose we want the doc to be.

Saying that "3 bluffs don't exist" automatically implies that a 2-away 3 when clued calls for either a true finesse or a double bluff. Now do we want to include a separate section defining double bluffs in UOD is all about verbosity.

**Comment by Zamiell** [comment]
> Saying that "3 bluffs don't exist" automatically implies that a 2-away 3 when clued calls for either a true finesse or a double bluff.

i think that logically follows and doesn't need a section in the docs explaining that.

the same can not be said about a brand new convention that states "there is no asymmetry between 2s and 4s, and 1s and 5s".

**Comment by sjdrodge** [comment]
Just to clarify the conversation regarding "2 Double Bluffs." A 2 is 1-away before a stack is started, and becomes 2-away only when a stack is started w/ a 5. For a 2 to become 3-away, it would require something like the 5 of a suit being lost before its stack is started, forcing the team to play S 4 3 2 1 if they want a max score.

Why is this relevant? Because 2-away cards don't require any special convention to be used for a double bluff. The 4 Double Bluff convention is about 3-away 4's being used for double bluffs.

That said, in the really rare circumstance where a 2 becomes 3-away in an U|D game, I would actually expect it to be usable for double bluffs, but I don't think it's worth any doc space to cover this rare case.

**Comment by Zamiell** [comment]
> That said, in the really rare circumstance where a 2 becomes 3-away in an U|D game, I would actually expect it to be usable for double bluffs, but I don't think it's worth any doc space to cover this rare case.

agreed
