### ISSUE TITLE
Question: Adding i18n translation for zh-CN

### ISSUE THREAD

**Issue by yeqingyan** [hanabi/hanabi.github.io#674]
I would like to adding zh-CN translation to this repo, is it possible?  from the [docusaurus docs](https://docusaurus.io/docs/i18n/tutorial#single-domain-deployment) it said

> Docusaurus will build one single-page application per locale:

Does it means that you have to build two application if I enabled i18n in this case? 
Also I tried to enable i18n locally, but looks like the static assets were broken, I create an issue to [docusaurus](https://github.com/facebook/docusaurus/issues/5019) , Any help is appreciated!

**Comment by Zamiell** [comment]
hello yan,

the website changes too frequently to handle translations.
look at the [commit history](https://github.com/hanabi/hanabi.github.io/commits/main).
also see [the proposals](https://github.com/hanabi/hanabi.github.io/issues), which constantly change the document when accepted.
so, your translation would become out of date before you have finished even translating it.

if you really want to translate a static copy of the website that will become out of date, then do so on a fork, but make sure that you link back to the master copy so that people know how to get the real version

**Comment by jk15162428** [comment]
@yeqingyan if you still want to do it, feel free to contact me using email.
