### ISSUE TITLE
Clarification: Double Ignition

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#675]
https://hanabi.github.io/docs/level-20/#double-ignition

We were playing some 6p games where we were using double ignition quite frequently. The issues I see are this:

"Double Ignition does not necessarily have to be on the next two players. It can be on anyone."

In a 6p game.....one of the players can be 5 seats away (In a 5p game, it's 4 seats away max), which makes me feel....that isn't the intended purpose of this convention. I feel this convention was probably made with the intention of it being for 3 players or 4 players. Thus, I think there should be clarification for 5p or 6p situations that at most it can skip over 1 seat/player.

Another thing of note, it looks like Double Ignition is mainly for end game. Thus, it plays oddly when used during early/mid game. What I'm seeing happen is when DI is started, everyone just ignores getting finesse position, assuming the last 2 players with "clear" plays should blind play. Basically, it stalls/stops all players from doing finesse/bluffs.  

Can we have some clarification addressing these two points?

**Comment by timotree3** [comment]
I would propose that double ignitions call for the first card from Bob unless Alice had a very good reason that she should give the clue instead of him and call for the second card from the last player with a playable. (A very good reason = Bob has a play and Alice doesn't or Alice has lots of clued cards and shouldn't be discarding.)

The same rules for the first card of a double ignition would then apply to unnecessary trash pushes as well.

I think this is a good idea because often Alice is in a position where she must find a clue that gets Bob to play finesse and this makes it more likely that such a clue is available + efficient. The fact that it may result in worse discard modulation compared to the status quo when Bob has trash on chop is offset by two other facts:
- If we're trying to give a double ignition in the first place, all the bluff targets have been used up, so if Alice's chop was one-away, it probably would have been clued.
- If Alice discards and lets Bob decide how to get the two cards to blind-play, he may give a double bluff that permanently saves a two-away card in Alice's, which is much better than just protecting it for one turn.

**Comment by pianoblook** [comment]
Another idea to toss out that could help disambiguate in some cases:

If Alice has multiple available targets to use for an _Ignition_/Burn re-clue, across different players' hands, the player whose hand she chose to reclue is being promised to be involved in the _Ignition_.

Obviously that won't always be available - and I sort of doubt would get accepted anyway - but could be useful in tricky situations.

**Comment by Zamiell** [comment]
tim's idea seems fine, but i worry that extra rules of this nature complicate DI even more than it already is

**Comment by sjdrodge** [comment]
FWIW, a lot of us already play DI & UTP the way timotree describes, but the problem with such a rule for more general use is the possible lack of synchronization on what the "very good reason" threshold is for Alice to give the DI instead of letting Bob or Cathy give it. Occupied vs. not is easy enough, but "holding too many cards"  is tougher. I've tried the threshold of Alice holding at least 2 more unplayables than the other player who could give the clue, but I've also seen plenty of endgame scenarios where 1 extra unplayable makes it well worth it.

All of that said, players using the maximum convention level are theoretically expected to have a firm grasp of context, so given that having such a rule is _much_ better than not having it, I vote for inclusion.

**Comment by pianoblook** [comment]
Seconded for inclusion! DI has historically been way *under*defined imo, and I've recently seen it be thrown around fairly haphazardly. I'd rather have it occur less often but with a higher efficacy + clarity

**Comment by Zamiell** [comment]
tim can you submit a PR

**Comment by Zamiell** [comment]
pinging @timotree3

**Comment by timotree3** [comment]
I'll do that

**Comment by Zamiell** [comment]
if you don't submit a PR by august 10th, then I will assume you never will and will close this issue to try and keep the issues thread clean
