### ISSUE TITLE
Convention Proposal: Bubblegum Double/Triple Bluff

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#683]
When we clue a pink card and it causes an unreleated blind play the clue receiver immediately writes the card as a 1 away pink card as a pink promise. 
What if we cause a situation where the blind play does not resolve the identity of the promised card?
I believe this causes a double blind play.

Example:
Playfield: no pink cards are played

Donalds's Hand: 
X - X - i3 - X - X

Alice clues 4 to Donald touching only i3.
Bob will blind play slot 4 

It is Cathy's turn and she realizes that, if she does nothing, Donald will write i2 on i3. Thus the situation is not resolved.
She blind plays slot 1

Donald realizes, if it was i2, Cathy would do nothing. However, because she blind played, she is saying that it is not i2. Thus, it must be a 2 away pink card and now he is promised that it is i3.

Similarly, if a 3 away pink card is used, it should cause 3 blind plays as a Bubblegum Triple Bluff
1st Blind Play: the slot called for
2nd Blind Play: slot 1
3rd Blind Play: slot 1

**Comment by sjdrodge** [comment]
Seems great. I would vote no on the Triple. It seems better to just get two blind plays and go into superposition. Also it would be more consistent with the current idea in the conventions that there's no such thing as a Triple Bluff.

There's also the case to consider where the card is known not to be 1-away from the initial blind-play. Do we still require additional blind-plays in that case? Do we promise an exact pink card or let it be anything that's 2+ away?

The classic example is when a 2 clue to a pink card causes a slot 2 blind-play. Does this promise i3 and call for additional blind-plays when it's actually i4 or i5? Or are we simply satisfied to have the clue recipient write "not i2" on the card?

**Comment by pianoblook** [comment]
> Does this promise i3 and call for additional blind-plays when it's actually i4 or i5? 

I'd def be in favor of calling for a second blind-play if it's actually the 4 or 5; that seems more in line with the concept of 4 double bluffs. Otherwise we'd also have to entertain that any such clued card could be a 3, 4, or 5 which seems counter to the general philosophy of pink promise.

----

The only general pushback I'd have is that you could argue that a Bubblegum Bluff that touches i3 could still be considered a valid _3 Bluff_, and therefore should generally just be marked as 2/3 (which is just the same superposition as any normal color bluff that could be a 2 or 3)

**Comment by Lel0uch-H** [comment]
Tried this in a game 4 months ago, was interpreted as a double half bluff in game:

https://hanab.live/replay/383927#1

![Screenshot (59)](https://user-images.githubusercontent.com/81278716/124490974-5beb1080-ddd0-11eb-91bc-025858d98767.png)

**Comment by sjdrodge** [comment]
Good point. I didn't mention the option of having that edge case still require multiple blind-plays.

**Comment by Zamiell** [comment]
> It seems better to just get two blind plays and go into superposition. Also it would be more consistent with the current idea in the conventions that there's no such thing as a Triple Bluff.

definitely agree with stephen here!

**Comment by Zamiell** [comment]
> There's also the case to consider where the card is known not to be 1-away from the initial blind-play. Do we still require additional blind-plays in that case?

i think that depends on whether #342 is accepted

i will mark this as blocked until then

**Comment by Zamiell** [comment]
> The only general pushback I'd have is that you could argue that a Bubblegum Bluff that touches i3 could still be considered a valid 3 Bluff, and therefore should generally just be marked as 2/3

i can totally see this logic, but yuck! that sounds not good

**Comment by pianoblook** [comment]
In terms of a two-away i3, this would *only* be ambiguous if it got a slot 4 blind-play after being clued 4. 

- If it was clued 2 and gets a slot 2, it's already known !2
- If it was clued 3 and gets a slot 3, it's already know as !3

So the main question seems to be about this sort of hypothetical:
- Turn 1, 4p Light Pink
- Alice clues 4 to Donald, touching an i3
- Bob blind-plays slot 4
- **Does Cathy need to respond**?

I could go either way. The fact that Donald would need to deal with *multiple* superpositions now - is it i2, i3, or any 4 as a 4 Charm? - sways me towards Cathy blind-playing

**Comment by Dr-Kakashi** [comment]
I just submitted a pull request on #342, so I assume this is now open for discussion and unblocked.

> > The only general pushback I'd have is that you could argue that a Bubblegum Bluff that touches i3 could still be considered a valid 3 Bluff, and therefore should generally just be marked as 2/3
> 
> i can totally see this logic, but yuck! that sounds not good
> having true identities on pink cards is important, that's the whole reason why pink promise is the most important convention
> 
> (you could use that same argument in favor of triple bluffs, but I think that a double bluff is a good middle ground for the reasons Stephen stated above)

I see this and I see how Piano mentions that Cathy would put Donald in multiple superpositions if she does nothing. 

I'm under the impression that most, if not all, of the pink conventions, immediately identify the newly touched pink card. For the pink conventions we have in place, I don't believe the person receiving the clue would mark the card as having 2 identities simply because of the possibility of it being a pink 3 bluff. Bubblegum bluffs are generally resolved immediately and the clue receiver immediately knows the identity of the pink card.

If this is the case, then the proposal here should happen naturally. If everyone is on the same page with how pink conventions work, then I believe that alone should induce Cathy to blind play slot 1

**Comment by Zamiell** [comment]
#342 is accepted now, so i will remove the blocked tag

**Comment by Zamiell** [comment]
submit a pr

**Comment by Zamiell** [comment]
### The Taffy Double Bluff

- First, see the section on the [Taffy Bluff](#the-taffy-bluff).
- Rarely, a player can perform a *Taffy Double Bluff* by violating *Pink Promise* on a *two-away-from-playable* pink card.
- For example, in a 4 player game:
  - It is the first turn of the game and nothing is played on the stacks.
  - Alice clues number 4 to Donald, touching a pink 3 on slot 3.
  - Bob knows that since Alice violated *Pink Promise*, this must be some sort of *Bubblegum* move.
  - Bob blind-plays his slot 4 card. It is a red 1 and it successfully plays on to the stacks.
  - From Donald's perspective, he knows that Alice performed a *Bubblegum Bluff*. Donald marks his slot 3 card as a pink 2 (the pink card that is *one-away-from-playable*).
  - Next, it is Cathy's turn. Cathy sees that Donald will mark his pink card as a pink 2. However, the card is really a pink 3, so the situation has not yet resolved.
  - Cathy blind-plays her slot 1 card. It is a red 2 and it successfully plays on the stacks.
  - Donald realizes that if his clued card was a pink 2, then Cathy would not have done anything. Thus, this must have been a *Taffy Double Bluff*. Donald updates the note on his card to be a pink 3 (the pink card that is *two-away-from-playable*).

**Comment by Zamiell** [comment]
I deliberately left triple bluffs to be undefined and/or illegal
