### ISSUE TITLE
Triple ignition

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#685]
Just putting it out here after the discussion with @Zamiell earlier today.

If Alice denies a double ignition and clues a 1 for 1 on Bob instead, and Cathy can clearly see that a double ignition was available for Bob and Donald instead, Cathy can assume in some contexts that the double ignition would have been ambiguous hence she has another playable on finesse and thus should blind play. And Donald can do the same. This can work as a possible triple ignition.

**Comment by pianoblook** [comment]
#446 is another attempt, for the record

**Comment by Zamiell** [comment]
its not a very good convention because now every time a person doesn't see some arcane double ignition, it will cause someone to bomb a card

**Comment by Zamiell** [comment]
we played several high-efficiency games this week where lack of triple ignition was a problem leading to a loss.

there are 3 different kinds of double ignition.
i think a "simple" solution to the triple ignition problem (in hard-variants) is to make a precedence system as follows:

RDI > TDI > PDI

i choose to order them in this way because:
1) I think that RDI probably more common & easier to see than TDI
2) and TDI in turn is definitely more common & easier to see than PDI.

thus, if someone does a TDI when they it is globally known that they have a RDI available, then it causes a TI

advantage: you get TI
disadvantage: more rules to memorize
disadvantage: players will cause accidental bombs because they will not see a RDI is available and do TDI, and so forth
disadvantage: TDI might be preferable to RDI in some cases since you lose the ability to touch more useless trash cards, which piano has said he likes doing for more TOCM (but i dont find this a compelling reason to readjust the selected precedence)

**Comment by Zamiell** [comment]
any thoughts on this?

**Comment by Lel0uch-H** [comment]
I think defining a precedence order for allowed DIs is too error prone. I don't like the idea.
