### ISSUE TITLE
Relax 4 Charms to 2-Away Rules as 5CEs

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [hanabi/hanabi.github.io#727]
It's time to relax/extend *4 Charms* since they have been widely used. I saw a lot of people (including me) follow the `2-Away Blindplay Rules` when performing a *4 Charm*. It kills a *Double Finesse* in the Bluff Seat I know but the 5CE also kills them so it won't be a problem.

**Comment by Zamiell** [comment]
i don't think many players would be on board with this idea.
the original justification for selecting three-away instead of two-away is that 4's are the best discard in the game.
meaning that we want there to be sufficient reason/value if we do decide to touch them, and allowing for double finesses helps satisfy that goal.
i think that this same reasoning still applies today.
if you *need* more charms for some specific variant like null or omni, then propose a variant-specific convention, don't propose a change to no variant.

**Comment by pianoblook** [comment]
I don't think this is a good change in general. It's very strong in the first couple rounds, but #589 has already been rejected for whatever reason.

Basically, Charms lose effectiveness after the first few rounds, and I don't think declined 2-aways are a good way to set them up

**Comment by iamwhoiamhahaha** [comment]
O I think it's probably because there are few playable cards on the fourth finesse position and most of the 4s are not two-or-more-away in the mid game. That's the reason we never had this issue before (at least for me). And for those who want to play with 2-away rules could just start the game with *Dawn* instead.

**Comment by iamwhoiamhahaha** [comment]
Closing this in favor of *Dawn*
