### ISSUE TITLE
Delete Bad Touch Finesse & Bad Touch Bluff

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#760]
History lesson:
- In the *Unknown Dupe Discharge* proposal thread, Jerry and I discussed the interaction between UDD and *Bad Touch Finesses* & *Bad Touch Bluffs*.
- In order to preserve backwards compatibility, we agreed that color clues would be reserved for UDD, and number clues would be reserved for BTF/BTB.
- At that time, I noted that if UDD was more generally-useful than BTF/BTB, then it would make sense in the future to delete BTF/BTB entirely and make UDDs work for both color and number clues.

It is now 9 months later and my prediction has come true:
- BTF/BTB has always been a pretty rarely-used convention, and continues to be.
- On the other hand, while UDD seems to be used somewhat uncommon (mostly used in the first couple turns), I seem to encounter it more frequently than BTF/BTB.

Thus, I propose deleting *Bad Touch Finesse* & *Bad Touch Bluff*.

Pros for keeping BTF:

- You get to perform BTF/BTB, obviously.
- For reference, the most common *Bad Touch Finesse* that you will see is when:
  - Someone draws red 1.
  - A player has both red 2s, with one of them on chop.
  - You clue 2's, which looks like a "2 Save", but it actually works to cause a *Finesse*.
- This kind of thing does not happen very often, but is arguably useful. (On the other hand, UDD is also arguably useful.)

Pros for deleting BTF:

- Deleting conventions is always good because our conventions are already too complicated and hard to remember.
- It's annoying/confusing that UTD works with color/number, but UDD only works with color. These two conventions should be unified to work the same way.
- UDD seems to be more generally applicable/useful than BTF/BTB.
- UDD seems to be more frequent than BTF/BTB. (So deleting BTF would result in less *Frequency Bias* mistakes made by players.)

For reference, in a world where BTF is deleted, the previous example where Alice clues number 2 to two red 2's would result in Bob playing slot 3 instead of slot 1, which still seems probably okay for many situations, as there are other ways to get slot 1.

**Comment by Zamiell** [comment]
Kyle brings up that an advantage of having both UDD & BTF is that sometimes, you have a *Free Choice* between color and number, and this gives players more flexibility to choose either option.

I agree with this point, but I still think that we are overall better off with BTF deleted.

**Comment by timotree3** [comment]
I agree with deletion. I have never seen a bad touch bluff with 2s or bad touch double with 3s in my entire Hanabi career.

**Comment by EhDrone** [comment]
Agreed that Kyle brings up a decent example - but I have hardly ever seen any bad touch finesse or bluff, but do with relative frequency see UDDs. I think the additional overhead of needing to analyze free choice and then assign a difference doesn't benefit having btf/btb remain. Especially since negative info may be more useful one way or the other even when free choice is available.

In summary - with all the ways to get slot 1s, I am in favor of deletion to let UDD bring home the number and color bacon.

**Comment by Zamiell** [comment]
🥓

**Comment by mmelwen** [comment]
I agree with the deletion, I dont even remember the last time I saw a BTF or BTB

**Comment by micerang** [comment]
Yeah, I would delete it as well. Usually there are better ways to get slot 1

**Comment by HelanaAsh** [comment]
Agree with the above comments, its a defunct convention

**Comment by pianoblook** [comment]
I agree with Kyle's point about the added flexibility. I think objectively having both options available is probably useful.

I may be biased, though, since the reliance on UDDs goes way down when using Dawn. 

That said, I think we've all agreed across multiple threads that we have a shortage of reliable Discharges in the early stages of (non-Dawn) games. That's definitely been evidenced by the prevalence & popularity of UDDs, so this change would nicely reflect that. Plus it's simpler, and BTFs do seem quite rare.

**Comment by Jayhui-q** [comment]
I am totally on board with this. The pro of the simplicity would really make this convention much easier to learn, and I personally have found UDD with number (as I sometimes have played with) to be more useful.

**Comment by gnarama** [comment]
Agreed that it rarely comes up and I am fine with deletion.

**Comment by Zamiell** [comment]
i updated the doc to remove any references to bad touch finesses or bluffs, if someone wants to double check my work that would be appreciated
