### ISSUE TITLE
Change the continuation clue (touching cards both inside and outside a layer)

### ISSUE THREAD

**Issue by SL765** [hanabi/hanabi.github.io#766]
While the current interpretation of "Assume a continuation clue over a fix" follows Information Lock Principle, it goes against Occam's Razor: why should the player being clued assume that the card that was **not present when the layered finesse was given**, that the team could not predict/know in advance, is playable, in addition to the card that was originally in the layer?

I propose changing the default interpretation to "If a clue touches cards inside the original layer, and renders the card the person was originally going to blind play impossible to be what it's supposed to play as, then it should be interpreted as a fix whether it touches cards outside of the original layer or not". This also feels more in line with the idea of fix clues - a card was going to bomb, and it was prevented, no further action needs to be taken (and just keep going with the original layer).

This also solves the issue of the person blind playing potentially drawing blockers for fix clues (most notoriously, rainbow, pink and omni), forcing the original clue giver to look for ejections/discharges/charms as safe backups before giving the finesse with a fix, and if any exists at all would only exist if the clue giver is in their bluff seat.

Consider the following No variant (5 suits) board state, r1 on the stack
    
      Bob: x x x r4 g4
      Cathy: r2 y2 y3 r3 r2
      
Alice clues r to Bob touching r4 expecting to fix r3 with y to Cathy next turn.
Bob does something irrelevant.
Cathy blind plays r2 and draws any of y1/y2/y3/y4/y5 (or if playing with rainbow/omni suits, any cards from those suits). Depending on Bob's hand and the deck size, that's up to 8 blockers from at most 42 unknown cards, I'm too lazy to math but it feels pretty fair to say it'll happen at least ~20% of the time.

Under the current interpretation, the team now has to give more fix clues to fix Cathy's y2 y3 that she is supposed to write y1, y2 on respectively, or, Alice is forced to clue r to Cathy and fix r2 again later, basically losing all efficiency gained from the original finesse in the first place.

(drawing dupe y2/y3 would obviously not be ideal in any scenario but you get the gist)

Yes this means you'll lose out some efficiency in games where people draw nothing but playables, but IMO those games usually don't need this extra bit of efficiency anyway, and should make finesses with fixes more available/more efficient for the average game.

I'm open to other alternatives as well, but I think the current interpretation of continuation > fix unnecessarily restricts the availability and efficiency of finesses with fixes, which in itself feels very counterproductive as it's supposed to make efficient clues more available, and it just feels weird that of all the conventions we have, this is the only thing that's dependent on the (unpredictable) identity of a card that will be **drawn after a clue is given**.

**Comment by Zamiell** [comment]
> it goes against Occam's Razor: why should the player being clued assume that the card that was not present when the layered finesse was given, that the team could not predict/know in advance, is playable, in addition to the card that was originally in the layer?

i think you are misuing the term *Occam's Razor*, because what you stated does not have to do with *Occam's Razor*.
specifically, *Occam's Razor* is what you use to assume a *Prompt* instead of a *Finesse*, a *Bluff* over a *Double Finesse*, and so forth.
in fact, since a *Play Clue* is simpler than a *Fix Clue*, *Continuations Clues* directly follow from *Occam's Razor* (in addition to *Information Lock Principle* as you already stated)

> I think the current interpretation of continuation > fix unnecessarily restricts the availability and efficiency of finesses with fixes

the *Hyphen-ated* conventions are fundamentally about telling the truth to each other.
it is a baked-in design goal of our conventions to "restricts the availability and efficiency" of lying to each other - so that's not a disadvantage, nor is it something we want to change.

**Comment by mmelwen** [comment]
I believe it should always be a fix and not a continuation clue 
it is the same as the situation with the 1's in pink variants: you cannot touch them because it would be a fix. This is especially usefull in variants with omni because if you give a finesse with a lie component you cannot possibly know whether the next card would be an omni, blocking the fix. To be honest I never assume continuation clues unless Zam is giving the clue.

**Comment by Zamiell** [comment]
if you are making the argument that "continuation clues are not very good in pink variants or omni variants", then you should propose a variant specific convention then

**Comment by mmelwen** [comment]
What are the cons if we give the fix clue presedence over continuation ?
If the fix wasn't needed next player will play to indicate that is a finesse, so the only clues we lose are basically the 1-1 in the new card, and I am totaly on board with that

**Comment by Zamiell** [comment]
you seem to be making the argument that "a 1-for-1 clue isn't very efficient".
but this is a narrow analysis - the goal of our conventions is not to maximize efficiency.
the "efficiency dial" is already turned high enough to win no variant games - we don't need to sacrifice other things to turn it higher.
rather, the more important criterion in no variant games is *Discord Modulation*.
we want to empower players with the ability to give 1-for-1 clues as a mechanism for ensuring safe discards and not getting bottom decked by anything.
sacrificing this for to potentially get "more efficiency" is counterproductive.

**Comment by mmelwen** [comment]
I just saying that the 1-for-1 clue can be given after the finesse is over and we don't lose something whereas if a blocker is drawn with the current interpretation we just cannot fix. Also finesses with a fix are mostly used in variant with blockers not in "No Variant" games since we don't usually lie for no reason

**Comment by Zamiell** [comment]
> I just saying that the 1-for-1 clue can be given after the finesse is over and we don't lose something whereas if a blocker is drawn with the current interpretation we just cannot fix.

i'm pointing out that if a player has the option between
1) discarding a card and
2) giving a 1-for-1 *Continuation Clue*
then no, they cannot "wait until the finesse is over".
they must give the *Continuation Clue* now.

**Comment by EhDrone** [comment]
Also a quick reminder that the conventions are designed for maximum win rate in No Variant and Rainbow, because most of the arguments are "in harder variants continuation clues get blocked easily"

**Comment by mmelwen** [comment]
What would the same player if a player that is playing 1's from the initial clue has an i1 and a 5 in his hand? He will discard because cluing the 5 will look like a fix. Is exactly the same you cannot give a clue because will look like a fix

**Comment by Zamiell** [comment]
> What would the same player if a player that is playing 1's from the initial clue has an i1 and a 5 in his hand? He will discard because cluing the 5 will look like a fix. Is exactly the same

Lets split up the word "lie" into a spectrum:

1) Fib (Severity 1)
2) White Lie (Severity 2)
3) Black Lie (Severity 3)

In the case of a pink game:

- It is the first turn and nothing is played on the stacks.
- Bob's hand is as follows: `red 4, red 4, pink 3, red 1, pink 1`
- Alice clues number 1 to Bob, touching slot 3, slot 4, and slot 5.
- Because of the *Pink Play Clue Lie* convention, Bob knows that all of his cards are probably true 1's, but he is open to the possibility that slot 3 and slot 4 are not 1's and are instead pink cards.

This is different from the *Continuation Clue* case in two notable ways:

1) There is *no other option* to get the cards in Bob's hand. Indeed, more generally, due to the nature of pink cards operate, it is often mandatory to "pick up" extra pink cards with clues. This property does not exist in No Variant games, or other games of Hanabi more generally.

2) We could classify Alice's clue here as a Severity 2 lie. Notice that in this situation, Bob has some restrictions: he is **not allowed** to perform an *Order Chop Move*, because Bob is supposed to respect that a *White Lie* could be occurring. This is **explicitly baked into the convention itself**.

More generally, any such situation where a player gets to take a turn in which the conventions dictate that they must take a *Lie* into account is a *White Lie* (Severity 2).

A *Finesse* with a *Lie Component* is fundamentally different from this. **All players** who get to take a turn **should never assume** a *Finesse* with a *Lie Component** is happening. This is why *Finesses* with a *Lie Component* are usually required to be *Fixed* by the person who originally initiated the *Finesse*. And they are deliberately difficult to do properly, because they interfere with expert players being able to take correct game states into account, making all of their moves worse. We **never** want to turn the lies in a *Finesses* with a *Fix Component* from a Severity 3 lie to a Severity 2 lie.

So no, *Continuation Clues* are fundamentally different than "discarding before cluing a 5" in the PPCL case.

**Comment by SL765** [comment]
In the case of the finesse with a lie component:

1. There is no _other option_ to get Cathy's red cards. Sometimes cards just get fully blocked. Happens sometimes in NV. Happens way more often in variants with clue-absorbing suits.

2. Cathy also has some restrictions: the slot she is expected to play from at any point, before the finesse fully resolves, is **globally known** due to the nature of (what Cathy would first assume) _Layered Finesses_.

I agree that finesse with a lie component should be taken as severity 3 lie. However, I don't see why this leads to the conclusion that we should always assume continuation clues.

and I'd like to emphasize that this is currently the only convention in the entire reference, whose validity is dependent on the identity of cards that are **unknown at the time of the clue being given** (cards that will have been drawn by the time the fix is needed). A change to:

1. Does the clue touch cards originally inside the layer? If no, then it is a normal play clue. If yes, then:
2. Does it make the card that was going to blind play impossible to be the card being called for? If so, then it's a fix. If not, then it might be a fix, but only if the finessed card is behind the a clued card inside the original layer, otherwise it's still a normal play clue.

gets around this problem entirely, while preserving the desired characteristics of the finesse with a fix. i.e. Alice is still the only player who can fix, and now Alice doesn't need to worry about Cathy drawing a blocker, and the team is no longer required to give additional fix clues.

**Comment by Zamiell** [comment]
> There is no other option to get Cathy's red cards.

Assuming you are referring to the hypothetical in the OP, then you are wrong, because you can wait for Cathy to discard and then clue the cards normally.
More generally, you could classify the case of cards being "blocked" in No Variant as a special case, and the case of cards being blocked in a variant with a pink suit as a general case.

**Comment by Zamiell** [comment]
> I agree that finesse with a lie component should be taken as severity 3 lie. However, I don't see why this leads to the conclusion that we should always assume continuation clues.

The point of generating granularity here was to dispute Mel's statement that PPCL is the "exact same", when it very clearly is not.

> and I'd like to emphasize that this is currently the only convention in the entire reference, whose validity is dependent on the identity of cards that are unknown at the time of the clue being given

I'm finding it difficult to parse this statement. I think you might misunderstand what a *Finesse* with a *Lie Component* is.

A *Finesse* with a *Lie Component* **is not a legal move**.
You are not allowed to do it.
If you do decide to break the rules and do it, then everything *may* work out.
But it also may not.
It is a pattern that is frequently done in variants that have high-efficiency requirements, so it is documented on the website, but that does not make it "ok" or "legal" to perform.
Essentially, you seem to be saying something along the lines of:

- In my last game, I tried to perform a *Finesse* with a *Lie Component*.
- Everything that I saw on the table meant that the clue would work out perfect.
- However, the player got a really unlucky draw, which made my *Finesse* with a *Lie Component* fail.
- This sucks! We should change the conventions so that it becomes easier to perform *Finesses* with a *Lie Component*."

No! If you got unlucky and your *Finesse* with a *Lie Component* failed, that is your fault for not appreciating the risk involved, and it is not the fault of the conventions. We don't want to make any concessions here, because you should generally not be doing *Finesses* with a *Lie Component* in the first place. It is more important to have
1) strong synchronicity between the team and
2) *Discard Modulation* to prevent bottom-deck losses.

**Comment by SL765** [comment]
>It is a pattern that is frequently done in variants that have high-efficiency requirements, so it is documented on the website, but that does not make it "ok" or "legal" to perform.

and it's mentioned in lv22, in the conventions that's supposedly designed for NV/Rainbow winrate instead of Extras or somewhere in the hard variants section because..?

>you take a risk every time you decide to perform one.

If it's possible to construct **safe** lines, as the ref says, then why should it in the end always depend on the blindplayer not drawing a blocker, instead of, say, the trust between players?

Then the ref is simply incorrect, because if we were to strictly follow this interpretation, then there are practically no safe lines, and they only exist if all possible blockers are seen/in the trash, or the cluer has multiple alternative clues to otherwise get the finessed card on their next turn.

>Essentially, you seem to be saying something along the lines of...

That's a lot of assumptions you're making. Unfortunately none of it is true (this is frosty104 fyi).

The game that prompted me to make this issue is https://hanab.live/replay/669129#32
where everything is clear up and until t41 where (and we expected it) b4 bombs as b2, and i think we agreed that a 4+2 tempo for 2 isn't good enough, and qqqq is supposed to believe in b2b3 is what the convention would suggest, but it's also somewhat ridiculous.

Should the fix be yellow? If we are to strictly abide by the ref, yes. Does it lose out on 2 free blue cards? Also yes. Will such clues  lead to, or be the direct cause of losing in high efficiency variants? Probably.

>Assuming you are referring to the hypothetical in the OP, then you are wrong, because you can wait for Cathy to discard and then clue the cards normally. So this is not symmetric to the pink case.

and waiting for Cathy to discard her chop instead of cluing her exposes the team to the risk of Alice/Bob discarding from having nothing to do, possibly leading to bottom-deck losses anyway. How is that better for _Discard Modulation_?

**Comment by Zamiell** [comment]
> and it's mentioned in lv22, in the conventions that's supposedly designed for NV/Rainbow winrate instead of Extras or somewhere in the hard variants section because..?

I'm not sure I follow. If you want to propose moving the section somewhere else, feel free to do that.

> If it's possible to construct safe lines, as the ref says, then why should it in the end always depend on the blindplayer not drawing a blocker, instead of, say, the trust between players?

Which section of the doc you are referring to? In general, we can say that planning 100% safe lines is not possible due to the random nature of card drawing. When designing conventions, it is overall detrimental to bend over backwards and try and accommodate for situations that end up being uncommon.

> Will such clues lead to, or be the direct cause of losing in high efficiency variants? Probably.

The goal of this thread is to determine what is best for a No Variant game. If you want to propose a convention for a *Hard Variant*-only game, then you need to open a new thread and specify that restriction in the original post.

(But there is no need to do that, because slightly-adjusting-for-more-situations-to-be-fucked-up-lies is **already the way that we play *Hard Variants***, and nothing further needs to be specified to accomplish that goal.)

**Comment by SL765** [comment]
>Which section of the doc you are referring to? 

In the lv22 section regarding Finesse with a lie component:
>With that said, it is sometimes possible to construct safe lines that contain a Lie Component.

>In general, we can say that planning 100% safe lines is not possible due to the random nature of card drawing.

Yes, but if any other clue doesn't work, the cluegiver can realize that before giving that clue just by looking ahead, and instead do something else. e.g. If a bluff doesn't work, it's because it wrong prompts, or it's because Cathy will discard a critical on chop, or it's because Donald is locked with no playable cards and won't have any clues. If a finesse with a lie component won't work, then it might be because the blindplayer drew into a blocker a couple of turns later. The cluegiver can't see the future and say "whoops, they're gonna draw into a blocker so let me do something else". They are instead (imo unnecessarily) forced to consider "What are my options if they draw a blocker? Are my current alternatives so poor that I should take the risk anyway?"

Finesse with a fix, in its current state, feels like:

1. It's supposed to be efficient, but arbitrarily forces fix clues to be inefficient
2. It apparently frequently leads to mistakes, which is probably tied to it being in lv22 in the general ref, and I would say also because the idea of continuation>fix is simply counterintuitive, **because** it's supposed to be efficient in the first place.
3. NV doesn't need it at all because above a certain efficiency threshold all we care about is preventing bottom-deck losses (which I agree with)
4. Some players simply ignore this continuation>fix thing even outside of hard variants anyway (lol)

Guess I'll open some separate issues then ¯\_(ツ)_/¯

**Comment by iamwhoiamhahaha** [comment]
The main reason why I frequently perform *Finesses with a Lie Component* is not because of the "efficiency" (to be fair, they're not always efficient as someone has mentioned above), it is because they provide another way to "pre-save" an unrelated card(s) which prevents us from bottom deck lost. Not to mention their power to start an engine and "prompt/finesse" all the playable cards at the same time.

For the sake of preventing bottom deck lost, a fix clue interpretation should take precedence over the continuation one no matter in a hard variant or an easy one imo.
