### ISSUE TITLE
Consider Up or Down a hard variant regardless of efficiency requirement

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#772]
The efficiency is close to 1.25 anyway (1.20 is the minimum across all number of suits & number of players), and the lack of 5 stalls causes loss of lot of 1-for-1s in favor of fill-ins.

**Comment by Zamiell** [comment]
agree with this, it should be a hard variant not because of efficiency but just because of the complexity and mistakes involved

**Comment by sjdrodge** [comment]
In my experience, the density of playables in U|D is high enough that it ends up being easier than the raw efficiency would suggest.

**Comment by pianoblook** [comment]
Moving forward I'm going to be very vocally against any further conventions that encourage players to discard more and save less. 

Plus in this specific case I fully agree with Stephen

**Comment by timotree3** [comment]
There's an [Up or Down 4p game burned into my memory](https://hanab.live/replay/525451#10) where the required efficiency was 1.25 out of the early game, somebody gave a clue that forced a misplay just to double discard avoid, and then somebody else hard burned to double discard avoid, because they were afraid a 5 stall would look like a play clue. After that game, I very much felt that up or down should be a hard variant. That or we should turn on hard variant rules if the required efficiency is >1.25 out of the early game

**Comment by Zamiell** [comment]
Looks like required eff is 1.18 on turn 9, not 1.25 like you say.

**Comment by pianoblook** [comment]
> @pianoblook @sjdrodge I would love to see examples of UOD games where more than 2 DDA stalls were given and the game was still won.

well for one, the replay timo linked looks like it would have been a pretty easy win; I tried one blind hypo and cleanly won with nothing fancy, and even involving a complete hard burn DDA

**Comment by Zamiell** [comment]
@timotree3

**Comment by Zamiell** [comment]
since we seem to be split on whether or not its "optimal" to have *Discard Modulation* in Up and Down, i will offer a different perspective:

1) treating a variant as a hard variant makes it "easier" to play in the sense that it lowers complexity and lowers mental overhead necessary in order to interpret clues
2) Up or Down is very difficult mentally, with so much to account for leading to a much higher rate of mistakes and misplays

tuning the conventions this way or that is really not as important as the more underlying goal of minimizing mistakes and getting good scores with a wide variety of skill levels.

thus, let's intentionally make the conventions "less optimal" in order to make up or down easier to play, which i suspect will have the effect of actually increasing the overall win rate / score in real life.

**Comment by timotree3** [comment]
There are variants with 1.25 efficiency where strong teams that use the latest efficient conventions, blind-play cards in the endgame, and don't get random strikes would probably win more often if they played with DDA, such as Critical 4s (5 suits) and Black (5 Suits). In fact, I feel like I recall @pianoblook saying that 1.25 efficiency is too low to be considered a Hard Variant these days. However, I prefer treating them as Hard Variants because it feels more forgiving. 

That said, I don't really play H-group conventions often, so I defer to you all.

**Comment by Zamiell** [comment]
piano/stephen is what i said convincing?

**Comment by pianoblook** [comment]
I don't feel experienced enough in U||D to have much of a valuable opinion. 

I guess I agree with what you said about complexity tradeoffs in general. It's a shame to think that HVRs are somehow 'simpler', but I guess you're right that remembering stuff like DDA + 5 stalls does create more overhead

**Comment by mmelwen** [comment]
5 stalls are pretty weird in U||D anyway because they can be play clues in the early game as well, so we are talking about DDA only I guess. I believe that because is already hard multiple cards before the direction is defined HVRs are better suited for U||D

**Comment by sjdrodge** [comment]
> piano/stephen is what i said convincing?

Sure, making the variant easier to think about given that people demonstrably struggle with it seems fine.
