### ISSUE TITLE
Delete Whisper Discard (merge with Scream)

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#776]
Pretty straightforward. 

The doc entry says, "This is more subtle than a Scream Discard though, so it is called a Whisper Discard." 

This seems like pointless extra terminology. Sure, psychologically it might be a more subtle *FORM* of a Scream Discard, but the cause & effect is 100% the same: Alice discarded an unsafe card on her chop instead of doing her expected play/discard action, so therefore it's a _Scream_.

**Comment by Zamiell** [comment]
> Alice discarded an unsafe card on her chop

in a *Whisper Discard*, Alice does not discard an unsafe card, and Alice does not discard her chop, so you are wrong on both counts

**Comment by pianoblook** [comment]
What? Are you perhaps getting mixed up with _Shout Discards_?

> Occasionally, a player will have known-trash in their hand. Obviously, **they are expected to discard the known-trash first before discarding their right-most unclued card.**
> **Thus, if a player instead discards their right-most unclued card instead of the known-trash, it must be a signal that something is wrong**, exactly like a Scream Discard. This is more subtle than a Scream Discard though, so it is called a Whisper Discard.

**Comment by Zamiell** [comment]
yes, i am mixing those up

**Comment by Zamiell** [comment]
should we call it a Trash Scream Discard then to disambiguate it?

**Comment by Zamiell** [comment]
i guess that also makes it sound like a *Shout Discard*

**Comment by pianoblook** [comment]
Functionally it's just the exact same thing, right? "Alice discards her chop in an unexpected+unsafe manner, hence a _Scream_ is occurring." 

I guess I don't see the benefit in separating them into subcategories, but whatever floats the boat

**Comment by Jayhui-q** [comment]
Agree with the title - it took me a while reading this thread to even remember whisper discards existed. I have almost always referred to them as screams in my reviews.

**Comment by Zamiell** [comment]
I renamed the section to `The Scream Discard Chop Move (With Known-Trash)`

**Comment by Zamiell** [comment]
### The Scream Discard Chop Move (With Known-Trash)

- First, see the section on the *[Scream Discard](level-6.md#the-scream-discard-chop-move-sdcm)*.
- Occasionally, a player will have one or more known-trash cards in their hand. In this situation, the player is expected to first discard their known-trash card(s) before discarding their chop.
- Subsequently, if a player instead discards their chop instead of discarding their known-trash card, it must be a signal that something is wrong. This works exactly in the same way as a normal *Scream Discard* does (except for the fact that it was triggered by having a known-trash card in the hand instead of having a known-playable card in the hand).
- It is illegal for a player to discoard their chop if they have both a known-playable card and a known-trash card in their hand. (In this situation, if the player wanted to perform a *Scream Discard* in this situation, they would discard their known-trash card.) If a player does this, it is to be treated as a known-mistake.
