### ISSUE TITLE
Change the levels into a scale from 1 to 100

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#785]
Hi world.

Actually I have two problems:
 - telling you are playing at 'level 23' assume you are playing at 'level max', while it shouldn't be the case. That's maybe a problem from the players themselves, but meh.
 - you have no way to tell with levels only you want to play at 'level max' but without 'suboptimal moves'. But since that add a good source of mistakes, that should be a level higher the rest imo.

It's possible to give more liberty to add any new move/any change between two levels by making some empty levels. Per example, we could keep levels 1 to 16 like that, but as soon as it became way less logical: maybe put level 17 at level 20, level 20 at level 25, and level 23 at level 30.

And then put each advanced strategies to a certain level maybe just after the name wrote things like 'The Negative 5's Tempo Clue (or Inverted 5's Tempo Clue) [55]" to tell it's level 55.

'Dawn' or any big change to the document could start at 'level 40'.
If 'advanced moves' start at level 50, advanced 4-Charm and Trash pull sections should be pretty low, while things like Purge bluff should be really high.

So the previously 'level 23' would became a 'level 30'.
I believe the previously 'level max' should stay 'level max' or became 'level 100'.
There is possibilities to add levels above that like 'level 120' for things outside the general document (hi piano).
And there is possiblities to write 'level 70' to play with most advanced moves except those which causes lots of mistakes.

One of the upside of it, is that it will make new players understand where there is some big gap between conventions. That mean if we assume a player will read one level every 10 (or 20) games, having a gap of nothing between level 17 and 19, will maybe make him play 30 (or 60) more games without new conventions.
If you want to increase that even further, it's possible to increase the max of the scale to maybe put dawn at 'level 90', and max at 'level 200'.

Thanks :)

**Comment by Romain672** [comment]
Another thing possible:
Put 'Double gentleman's discard' as level 110 and for any convention >100 add a disclaimer:
' - since the level is >100, we discourage to play with it'.

But those who want level max could play with it. Those who want a more consistent game can play at level 100 instead.

**Comment by Romain672** [comment]
Ok apparently I didn't express me well.
Goal isn't to have one convention per level. But goal is to have half the level empty, which let you add others moves between those level.

So 2/3 finesses could all have the level 60. Some finesse which just follow that logic could be level 61. We could skip levels 62/63/64. Some even more advanced finesse could take level 65. And we could have nothing in levels 66/67/68/69.

Then, two years from now, a new type of finesse is added to the document, and take the level 62.
With that method, we haven't need to add one level to each convention after that point.

My proposition reorder nothing. It just add empty spaces, and give numbers for all advanced conventions.

**Comment by Lel0uch-H** [comment]
I understand what you mean Romain, but I would say it is just a big overhead to remember discrete number of levels rather than a continuous one.

**Comment by mmelwen** [comment]
I agree with Lel, continuing numbering is easier to remember and also what is the benefit of your proposal ?

**Comment by Romain672** [comment]
> It's possible to give more liberty to add any new move/any change between two levels by making some empty levels. 

> One of the upside of it, is that it will make new players understand where there is some big gap between conventions. That mean if we assume a player will read one level every 10 (or 20) games, having a gap of nothing between level 17 and 19, will maybe make him play 30 (or 60) more games without new conventions. If you want to increase that even further, it's possible to increase the max of the scale to maybe put dawn at 'level 90', and max at 'level 200'.

> Then, two years from now, a new type of finesse is added to the document, and take the level 62. With that method, we haven't need to add one level to each convention after that point.

Having discrete numbers let you move less the differents levels over time.
Normally, the level 60 play with X conventions on, will stay a level 60 with those same X conventions and some others, even after lots of changes.

**Comment by mmelwen** [comment]
I am sorry Romain I would never agree on putting empty levels there, as per the convention document the nice thing about it is the is changing as we are abandon some and discover other conventions, is not something static is changing and adapting in our play style. We can discuss more specific rearrangements if you want because obviously there is something you feel is not working. Also we need the levels to be grouped so we can play with new players without reading all the doc numbering.

**Comment by Romain672** [comment]
> as per the convention document the nice thing about it is the is changing as we are abandon some and discover other conventions

For me it's an argument for my way. Since you think there is lots of changes, you would want veteran players to know that 5-Techs is level X, and has few change to be changed (except if 5-Techs themselves are changed).

> We can discuss more specific rearrangements if you want because obviously there is something you feel is not working.

It is working, I just wanted mainly that "you have no way to tell with levels only you want to play at 'level max' but without 'suboptimal moves'. But since that add a good source of mistakes, that should be a level higher the rest imo", and at the same time, find a better solution in the long term.

> Also we need the levels to be grouped so we can play with new players without reading all the doc numbering.
> And then put each advanced strategies to a certain level maybe just after the name wrote things like 'The Negative 5's Tempo Clue (or Inverted 5's Tempo Clue) [55]" to tell it's level 55.

Again, all early level doesn't change (except the addition of some empty place, but that will not change much new things).
And for advanced moves, it just add a level into some []. That way, to retake my earlier example 
> And there is possiblities to write 'level 70' to play with most advanced moves except those which causes lots of mistakes.

I'm not seeing your point melwen D: Lel0uch got an argument (even if I disagree personally).

**Comment by mmelwen** [comment]
> It is working, I just wanted mainly that "you have no way to tell with levels only you want to play at 'level max' but without 'suboptimal moves'. But since that add a good source of mistakes, that should be a level higher the rest imo", and at the same time, find a better solution in the long term.
 
I can agree that we have far too may conventions  in the section "advanced Stategies" maybe a solution could be to continue the level numbering inside and perhaps have level 24 and level 25 under that label, to split them into levels. So point out which of the you think they are more difficult and lead to errors and we can continue from there

**Comment by Romain672** [comment]
(I gave a few examples here already, I guess if I need to explain more, I will need to look at every convention.
Trash pull should be soon after 23.
Suboptimal moves should be close to end/not ranked.)

**Comment by Romain672** [comment]
So as we talked melwen, I did what you asked (even if you was joking :p ):
https://docs.google.com/spreadsheets/d/1_vHH3kfHOsUA3Esj9hMrpn7V2jb8I_MSgxwASOk-bLU/edit#gid=0

This is all the advanced conventions with a certain number of point depending of: their complexity (and how much they are prone to mistakes), their rarity, if it's optionnal, and if it can be deduced on the fly.
Since I'm not good, and I'm not playing with half those moves, there will be lots of strange things, so feel free to edit it if you want.
And it depend a lot of which point you give depending of the factors.

So from that:
 - there is lots of chop moves which got ranked high

And... There is so much differents stuff ranked high.

I added a column which can make you see what the levels could look like. I didn't double checked, but most of the level 50/55/60 got only logical moves which aren't optional (ie, which can be deduced easily, and aren't optionnal).
I wasn't proposing that.

**Comment by HelanaAsh** [comment]
I like the how the levels are ordered atm, I have used it recently to teach some newer players and for the most part, they find it easier to follow, learn, and use. I share the same sentiments as Lel, do not like discrete numbering system, albeit I do have some issues with the doc:

1. Advanced strategies need to have a proper level. I often encounter players say 23, but not know unnecessary moves, etc, which makes me have to re-iterate the question: are you 23 or 23+? Suggestion: Add a level.

2. I disabled notifications for the server, because I hate the clutter of messages I have to go through everyday, and I have to, want to, need to have a clutter free inbox everyday D:. So its especially hard me for to follow through all the updates that get posted to the conventions, minor or major, I don't have time to read them everyday before playing. I was out for about a month at some point to come back and people asking me why i dont know xyz convention, but said I play at max. Suggestion: I recommend that convention changes happen every quaterly or something along the lines, making it easier for people to come back after a break and pick things up relatively easy. Also maybe have a update section in the doc itself for every quarter?

3. Another problem I often have when playing at a certain level is wrt to playing variant specific conventions. In particular, some people play pink at full levels, some at level x, because they are only at x levels in the reference doc. But for people who are less advanced in variant specific conventions, it is often frustrating when teammates give out out of level clues for the variant inadvertantly. Suggestion: Idk maybe divide variant specifc into 2 parts 0-10, 10+ or something? Not sure this is a real gripe, but has been occuring more frequently than I like. 

4. Can we add level requirements to the table? Often times, I would like to play with people of my skill level, but sometimes I also enjoy beginner games, but I feel bad to kick a beginner out if I am in mood for an advanced game, leading to creating a password protected games. I however, do not want to put in a password, since I would ideally like to play with anymore over say an x level that i am in mood for. Am I even still staying relevant to the thread?

Thanks!

**Comment by Zamiell** [comment]
> I often encounter players say 23, but not know unnecessary moves, etc, which makes me have to re-iterate the question: are you 23 or 23+? Suggestion: Add a level.

unnecessary moves are already literally level 23, so i dont understand your request

**Comment by Zamiell** [comment]
> So its especially hard me for to follow through all the updates that get posted to the conventions, minor or major, I don't have time to read them everyday before playing.

i have no idea what you are talking about.
there are not convention updates every day.
there are at most 1-2 convention updates per week that are posted into the announcements channel, and thats all you have to read.

**Comment by Zamiell** [comment]
> Can we add level requirements to the table?

thats not on topic for the discussion

**Comment by Zamiell** [comment]
> But for people who are less advanced in variant specific conventions, it is often frustrating when teammates give out out of level clues for the variant inadvertantly

are you talking about pink? pink is the only variant that has variant-specific conventions that are grouped by level

**Comment by HelanaAsh** [comment]
> > I often encounter players say 23, but not know unnecessary moves, etc, which makes me have to re-iterate the question: are you 23 or 23+? Suggestion: Add a level.
> 
> unnecessary moves are already at level 23, so i dont understand your request

im speaking of this

https://hanabi.github.io/docs/extras

**Comment by HelanaAsh** [comment]
> > Can we add level requirements to the table?
> 
> thats not on topic for the discussion

What exactly do you mean by that?

**Comment by Zamiell** [comment]
> What exactly do you mean by that?

if you want to discuss a change to the website, you should do that in the website repository

**Comment by Zamiell** [comment]
> im speaking of this

those are not unnecessary moves, those are extra moves.
be more careful in your language

**Comment by HelanaAsh** [comment]
> > So its especially hard me for to follow through all the updates that get posted to the conventions, minor or major, I don't have time to read them everyday before playing.
> 
> i have no idea what you are talking about. there are not convention updates every day. there are at most 1-2 convention updates per week that are posted into the announcements channel, and thats all you have to read.

You mean recently? I have seen a few updates on a single day or days together in the past. I speak of it because it is a **nuisance**

**Comment by Zamiell** [comment]
> You mean recently? I have seen a few updates on a single day or days together in the past. I speak of it because it is a nuisance

are you referring to github commits or what?

**Comment by HelanaAsh** [comment]
> > im speaking of this
> 
> those are not unnecessary moves, those are extra moves. be more careful in your language

Edited

**Comment by Zamiell** [comment]
> Edited

submit a pr with a level 24, and make sure that it is comparable in size to all of the other levels

**Comment by HelanaAsh** [comment]
> > You mean recently? I have seen a few updates on a single day or days together in the past. I speak of it because it is a nuisance
> 
> are you referring to github commits or what?

No, I am referring to Convention Announcement Channel.

**Comment by Zamiell** [comment]
if i click on the convention announcements channel and i look through the last N announcements, the time between announcements is, counting in order:
- 21 days
- 13 days
- 12 days
- 7 days
- 7 days
- 10 days
etc.

thus, i will say again, i have no idea what the hell you are talking about

**Comment by Zamiell** [comment]
based on the data above, the average days per announcement is 11.7 days.
i think it reasonable for members of the hyphen-ated group to read one announcement per 11.7 days.
if their lives are too busy and they take a month away from the game or something, then all they have to do is read 3ish announcements to catch back up.

**Comment by Zamiell** [comment]
> telling you are playing at 'level 23' assume you are playing at 'level max', while it shouldn't be the case.

that is a problem of communication.
if you want to play at level 23, then say that you are playing at level 23.
if you want to play with level 23 + the extra conventions, then say you are playing at level "max".
one way to ease communication would be to rename the "extra" conventions to level 24.
however, the reason why we haven't done that already is explained on the webpage:

```
- The "extra" strategies are separated from the rest because they do not come up that often. Thus, non-expert players do not have to worry about learning them.
- If an "extra" strategy does come up in a game, players with experience can often figure out what to do on-the-fly. Otherwise, they can quickly learn about them in the post-game review, and then reference the documentation later if they need to refresh their memory.
```

> you have no way to tell with levels only you want to play at 'level max' but without 'suboptimal moves'. But since that add a good source of mistakes, that should be a level higher the rest imo.

the levels are meant to be played in order.
for example, players who want to play "level 15 but without level 13 conventions" because "level 13 conventions are a higher vector for mistakes than level 14 and level 15" is an anomaly that does not represent how most people in our group play.
thus, i am not really interested in changing the structure of the document to solve for this problem.

**Comment by HelanaAsh** [comment]
> based on the data above, the average days per announcement is 11.7. i think it is reasonable for members of the hyphen-ated group to read one announcement per 11.7 days. if their lives are too busy and they take a month away from the game or something, then all they would have to do is read 3ish announcements to catch back up.

I think you could be more organized than randomly announcing updates whenever you feel like. I hope others comment on this thread and voice their opinion on the topic, even if they dont share my sentiment.

**Comment by Zamiell** [comment]
> I think you could be more organized than randomly announcing updates whenever you feel like

announcements are not announced randomly, they are announced when the relevant threads on github are finished being voted on and integrated into the document
(and queued until the next week if there was already an announcement that week)

**Comment by HelanaAsh** [comment]
> > telling you are playing at 'level 23' assume you are playing at 'level max', while it shouldn't be the case.
> 
> that is a problem of communication. if you want to play at level 23, then say that you are playing at level 23. if you want to play with level 23 + the extra conventions, then say you are playing at level "max". one way to ease communication here would be to rename the "extra" conventions to level 24. however, the reason why we haven't done that already is explained on the webpage:
> 
> ```
> - The "extra" strategies are separated from the rest because they do not come up that often. Thus, non-expert players do not have to worry about learning them.
> - If an "extra" strategy does come up in a game, players with experience can often figure out what to do on-the-fly. Otherwise, they can quickly learn about them in the post-game review, and then reference the documentation later if they need to refresh their memory.
> ```
> 
> > you have no way to tell with levels only you want to play at 'level max' but without 'suboptimal moves'. But since that add a good source of mistakes, that should be a level higher the rest imo.
> 
> the levels are meant to be played in order. for example, players who want to play "level 15 but without level 13 conventions" because "level 13 conventions are a higher vector for mistakes than level 14 and level 15" is an anomaly that does not represent how most people in our group play. thus, i am not really interested in changing the structure of the document to solve for this problem.

You cannot argue from the fact that some levels are easier to pick up than the rest. For example, I see many lvl 23 players still making mistakes on prio. It is general human nature to continue to evolve and advance, in many cases quicker than they should be. I am not asking you to restructure the document, we all eventually learn from mistakes, but I am asking you to organize that as a level and help with less miscommunications. I cant for example, say I am lvl 15-ish and proceed to give lvl 16 clues or fail to recognize lvl 13 moves. When you are lvl 23, are you 23, or max is a stupid question, it should be are you 23 or 24. When you say your are max, or lvl 24, it means I can do rare or unconventional moves and I am not limited by my choices, under duress with an intent to benefit the team or for research/swag purposes.

**Comment by Zamiell** [comment]
> You cannot argue from the fact that some levels are easier to pick up than the rest.

i was not arguing that, no

> I am asking you to organize that as a level and help with less miscommunications

i am against putting all of the extra conventions as level 24, because that would be too many conventions for a specific level, as well as undesirable for the reasons in the two bullet points of my previous post.

the post you are quoting as a response to romain, are you not going to respond to my post you to directly above?

**Comment by Romain672** [comment]
>  you have no way to tell with levels only you want to play at 'level max' but without 'suboptimal moves'. But since that add a good source of mistakes, that should be a level higher the rest imo.

I think there was lots of misscomprehension because of that point.
The only suboptimal moves which is present in the basic strategy is this one: https://hanabi.github.io/docs/level-19/#the-suboptimal-prompt--the-suboptimal-finesse--the-suboptimal-bluff . I'm referring to the section https://hanabi.github.io/docs/extras/suboptimal-moves in advanced moves.

> the levels are meant to be played in order.

Yeah I agree (ie: what I just writed).

**Comment by Zamiell** [comment]
> I and Helana want to have levels 24/25/26 on some potentials advanced conventions. To do that:
we can either try to find group of conventions which goes together (like the chop move part)
or we can add an '[xx]' to each advanced convention which give an idea to how much that convention is useful (a first shot of it was my document). Note on this idea, the advanced sections will remain the same*.
or another idea?

yes, i am proposing to you / helana / whoever that to make a pr for the first bullet point as a mechanism for instructing the group exactly what you want, rather than vagaries of "there should be more levels, zamiel should decide what to do and then do a bunch of work to implement it".
do baby steps, add one level at a time in a way that is reasonable and in a way that you can convince other people to get behind

**Comment by Romain672** [comment]
> make a pr for the first bullet point 1/3 as a mechanism for instructing the group exactly what you want

Ok thanks. To everyone who are interrested by it (=ranking the differents advanced moves), pm me on discord: I will open a discord conversation about it.
Once we got a good result, depending of the number we are, I will either add a pr, or we will propose it in a channel (in depth discussions I guess).

**Comment by Zamiell** [comment]
i think you should make an issue on github instead of posting in discord, since whatever arbitrary selection of moves that you propose for level 24 would be a change to the document

**Comment by Zamiell** [comment]
closing in favor of #796

**Comment by Romain672** [comment]
Small conclusion on that one so:
 - I voted to put a scale from 1 to 100.
 - Lel0uch and Melwen voted to add one level to each following conventions, and so change each time the value of the number max.

Since there was only 3 votes, if one day someone want to reopen that, the community didn't gave much opinions on it.

**Comment by mmelwen** [comment]
Romain sorry to disappoint you the only thing me and Lel agreed on is we don't want levels with no conventions in it, meaning empty levels.
I also said, that we could consider splitting the Advance Strategies into 2 because they are maybe to many. I certainly disagree with 100 levels because level are suppose to group conventions, 1 convention/level is useless imo.

**Comment by Romain672** [comment]
But again it's not 1convention per level...
Doing that scale would let you group conventions of the same type and add conventions 'in between two levels' more easily.

**Comment by Romain672** [comment]
Alternatively, I think we could keep levels from 1 to 23 normally.
And then create a level 30 to add the 'easy' advanced strategies.
And a level 40 to add the 'hard' advanced strategies.

I'm confident it's a nice 'in between' solution.
Thoughs?
