### ISSUE TITLE
Clarification: Trash Pull and Trash Double Ignition

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#788]
As it's currently written in the doc, it's ambiguous when trash pull is on.

I propose we write something to the effect of:
If Bob knows he is not being trash cm, he is required to look at Cathy's slot 1.
If Slot 1 is playable, Double Ignition
If not, Trash Pull.

This means trash pull can occur before end game.

**Comment by Zamiell** [comment]
that section has not been updated since the introduction of trash double ignition, so I will update it now:

### The Trash Pull

- Normally, when known-trash cards are clued, it is a *Trash Chop Move*.
- Otherwise, when players can see that the clue cannot be a *Trash Chop Move*, they should instead interpret the clue as a *Trash Double Ignition*.
- Rarely, players can see that a clue cannot be a *Trash Chop Move* or a *Trash Double Ingition*. In this situation, it should instead be interpreted as a *Trash Pull*, which is explained below.
- A *Trash Pull* is similar to a *5 Pull* in that it "pulls" the card to the right of the card that was clued. This is a useful tool to have because sometimes, towards the end of the game, there can be a playable card in the middle of someone's hand that is not cluable directly due to the presence of other blocking cards.
- Remember that a *Trash Pull* can only be performed if there is no other explanation for the clue.
- Since players often perform *Burn* clues for stalling purposes in the *End-Game*, care has to be taken to not confuse a normal *Burn* clue with a *Trash Pull*. This is especially true if there was nothing else obvious for the clue giver to do!
- *Trash Pulls* should typically be used as a last-resort since they might be misinterpreted.
