### ISSUE TITLE
Pink convention conflict: 5ND versus bubblegum finesse

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#801]
![image](https://user-images.githubusercontent.com/81278716/148788516-0b5f9018-7457-40c6-b624-32804e42b9e6.png)

Alice clued 5 to i2 to get i1 from slot 5 of Bob, which coincides with 3rd finesse position in this case. Cathy assumed it is a 5ND.

I think in this case too we should define pink convention to take precedence.

cc: @pianoblook

**Comment by mmelwen** [comment]
![image](https://user-images.githubusercontent.com/66402571/148790609-5924eb57-27e5-4573-874d-db8fc3fad346.png)
Same game
what it means if I play slot #2 and what if I play slot #3 also
is the turnabout ejection off after i1 is down? 
Posted the same at the convention questions feel free to delete on of them

**Comment by Zamiell** [comment]
its not in conflict, the precedence is clearly defined already https://hanabi.github.io/docs/variant-specific/pink/#pink-precedence

**Comment by Zamiell** [comment]
oh i guess this issue is for adding "Bubblegum Finesse" next to "Bubblegum Bluff" in that section?

**Comment by Zamiell** [comment]
afaik it was already intended to be in that section, the fact that it doesn't say "Bubblegum Finesse" in addition to "Bubblegum Bluff" is an oversight

**Comment by pianoblook** [comment]
oh nice, yeah I just responded to this on Discord.

> I guess by the letter of the law it may be confusing, but I'd argue that the spirit of Pink Precedence suggests the Bubblegum should be assumed (https://hanabi.github.io/docs/variant-specific/pink/#pink-precedence):
As an exception, the Bubblegum Bluff and the Taffy Bluff conventions usually take precedence over their non-variant-specific alternatives.
5ND isn't listed as one of the specific exceptions, but personally I think that's more of an oversight (woops!) than intentional, since it's a very rare scenario (the discharge coming from slot 5). Anyone else think otherwise?

**Comment by Zamiell** [comment]
lelouch can submit a pr
