### ISSUE TITLE
Delete Safety Charm

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#803]
Safety Charms have the property where if someone gives a slightly sub-optimal clue, you can lose the game from it.

For example, consider the following game: https://hanab.live/replay/697164#1
- On the first turn of the game, ADrone should probably clue 5, which would invoke a *5 Pull Clandestine Finesse* on Zamiel. This seems like it would work out just fine.
- asaelr, seeing this, charms because he sees the 2 clue as a *Safety Charm*.

Analysis of who is at fault:
- I do not think asaelr was at fault, because ADrone should have given the *5 Pull Clandestine Finesse*.
- However, I don't think ADrone is much to blame either, because the *5 Pull Clandestine Finesse* is very difficult to see from his perspective.

Thus, I think the actual problem is that we have the *Safety Charm* convention turned on, and we wouldn't have this problem if it was deleted.

The two main arguments against *Safety Charms* are as follows:
- They are used very rarely. Thus, they are using up convention space that could be taken by moves that are more frequent.
- The risk versus reward ratio does not seem worth it.

**Comment by pianoblook** [comment]
Definitely should be deleted in easy variants. As I said in reply to the replay post:
> if everyone agreed to play max level  w/ extras - and for some ungodly reason decided to subject themselves to 5p Dark - I think expecting misplays from mistakes goes with the territory.
(or in other words, "assuming a mistake" is not a luxury you can afford in 5p Darks)

**Comment by pianoblook** [comment]
It's also already pretty rare, so I'd be fine just deleting it from official conventions. Definitely doesn't warrant being the first individual "HVR only convention"

**Comment by sjdrodge** [comment]
YEET IT

**Comment by TheDaniMan** [comment]
I've never seen this convention used successfully, but I have seen people miss a possible 5 pull quite a few times. Also, I don't like the interaction with 5 stalls in easy variants. I'd yeet.

**Comment by Lel0uch-H** [comment]
I have tried to do a safety charm 5 times and it worked flawlessly only once.

Thus, I would also agree to deletion.

**Comment by mmelwen** [comment]
Same here, I have seen this convention work once, maybe is the game in which Lel refers. I agree with the removal

**Comment by mangopie1** [comment]
Agreed to delete too. Never seen it work, and only seen it attempted once or twice.

**Comment by T-Hoodie** [comment]
The following applies not only to the Safety Charm, but (from the top of my head) also to the Rank Choice Ejection, Shadow Finesse, Prophetic Clues and to some extend the Suboptimal Prompt/Finesse/Bluff/(Save).
They all share the property that the given clue is technically not a lie that needs to resolve, but instead relies on the idea that a player intentionally declined the superior option and wants to communicate something extra.

Whenever a (seemingly) suboptimal clue happens, the next player has to ask itself:
1) Was this truely suboptimal? Or is there a reason why this particular clue was given over the alternative? Given the nature of asymmetrical information in Hanabi, oftentimes there is no easy or clear answer to this.
2) If it is suboptimal, was it intentional? We rightfully assume that players don't give suboptimal clues on purpose, but we all know that those minor mistakes are part of the game.

So the next player has to make two seperate judgement calls, and answering one of them wrongly can lead to a game loosing mistake. However they are also very efficient ways to communicate extra information, when they are done properly.
I personally like playing with those clues. I've seen them all used succesfully, I've seen them all fail, and I've seen players (including myself) miss plenty of opportunity to apply them. Maybe making all of these clues Hard Variant only Clues is not such a bad idea afterall, because the risk/reward ratio is probably only worth it if we really need the extra efficiency.

**Comment by Zamiell** [comment]
please open a separate thread if you want to make other conventions hard-mode-only
