### ISSUE TITLE
Convention Cleanup for Q1 2022

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#804]
(Last thread: #196)

It is our responsibility to delete conventions that are rarely used, because some players forget about them, and other player's don't, and this causes lost games and desynchronization. See also: <https://github.com/hanabi/hanabi.github.io/blob/main/misc/convention-goals.md>

For every new convention, we should also delete an old convention to keep the balance, so deleting rarely-used conventions makes space for other moves that will actually have a substantial impact to win-rate.

I propose that the following conventions are rarely-used and should be deleted. If you see a rarely-used convention that should be deleted that I did not include in the list, please bring it up below.

<br />

**1) Selfish Focus Inversion**

- Rarely used, not very useful, prone to mistakes since it can be misinterpreted.

**2) 2 Saves Off Chop on the First Turn** (3-player only convention)

- Since it happens so rarely, this convention almost always causes a bomb.
- Thus, we should just make bombing the official policy: if you are starting a game and you have no "normal" clues to give, then just give a clue that will cause a bomb on the least-worst card.

**3) The Hesitation Chop Move (From a Misplay)**

- This convention is counterintuitive and tenuous because the normal thing to do after a bomb is to "chill out".
- Thus, by giving a save clue to the critical card in question, it can look to others like a *Play Clue* instead of a *Save Clue* and can cause additional bombs.
- I propose that since that this situation is so specific and so rare, it is better to let players figure out what to do on the fly.

**4) The Prophetic Finesse (for 1's)**

- Have never seen this. Even more rare than the already-super-rare *Shadow Finesse*.

**5) The Cursed Finesse**

- Have never seen this. Even more rare than the already-super-rare *Shadow Finesse*.

**6) The Rank Choice Ejection (with a number 2 or a number 5) (RCE)**

- Do people actually use this? I do think I have actually seen this used well once or twice, but I can't specifically remember the last time that this was.

**7) The Self Color Ejection**

- Have never seen this.

**8) The Prophetic Discharge**

- Delete this for the same reason we should delete the **Prophetic Finesse**.

**9) The Layered Jump**

- Libster did this one time in 2019 and I have not seen it since.

**Comment by sjdrodge** [comment]
I want to keep Rank Choice Ejection. Happy to kill the rest.

**Comment by Zamiell** [comment]
oh that's interesting that it finessed as well

**Comment by florian-5f3759df** [comment]
For me RCE involves some cognitive overhead, because Chop Move Ignition / 5 Double Pull both use a slot 1 blind play to move from save to play, while RCE uses slot 2 to do that. Also it's a bit error-prone because of cases where the rank actually was enough to show the card playable (because Alice and the recipient can account for any unplayable 2s of the other suits in a way that's hard to see by Bob). For these two reasons I wouldn't be that sad to see it go.

(The example is really cool though, and shows that it can be quite powerful. Also I admit we're lacking a little bit in late mid-game ejections.)

**Comment by Zamiell** [comment]
> For me RCE involves some cognitive overhead, because Chop Move Ignition / 5 Double Pull both use a slot 1 blind play to move from save to play, while RCE uses slot 2 to do that. Also it's a bit error-prone because of cases where the rank actually was enough to show the card playable (because Alice and the recipient can account for any unplayable 2s of the other suits in a way that's hard to see by Bob). For these two reasons I wouldn't be that sad to see it go.

excellent point!

**Comment by pianoblook** [comment]
I just saw a successful Prophetic Discharge the other day in a game I wasn't even part of - was pretty sweet! They, like Shadows, are only infrequent because people don't look for them. I'd urge them not be deleted because they don't actually cause a bomb if they're missed + I seriously doubt would ever cause a "false positive" (unlike Safety Charms, since apparently it's not uncommon for 5 pulls to just go overlooked).

RCE is an incredibly important convention IMO, and I see it not infrequently. And once again, importantly it does *not* cause a bomb if it's missed.

- Selfish Inversion I agree is very error-prone and rare
- 2 saves off chop ambivalent
- hesitation chop move never heard of it lol
- layered jump doesn't feel like it needs to be explicitly defined

**Comment by mmelwen** [comment]
Agree that we dont look for shadows because we are trying to find a finesse and not decline one. In favor of keeping no. 6 as well

**Comment by Lel0uch-H** [comment]
Here's my position:

- Selfish focus inversion: Good convention for 2p, have rarely seen it WAI in multi player games. Agree to delete.
- 2 saves off chop 1st turn: Does not hurt to keep it in the doc. In fact, I have even seen a 4p game with literally no legal clue to give than a _2-stall_.
- Hesitation CM: Candidate for deletion, most players assume scream over hesitation anyway.
- Prophetic finesse: Have seen the opportunity bunch of times. I would certainly want to keep this.
- Cursed Finesse: Have never seen it in a real game but I think it is likely that it will be decently frequent, probability of this occurring seems to more than a triple finesse (at least intuitively, I would love if somebody has actual math to prove this).
- Rank choice ejection: Seems neat as an idea, but have hardly seen it working less than 5 times.
- Self color ejection; Never seen, candidate for deletion.
- Prophetic discharge: Same as prophetic finesse, I would like to keep this since it can be useful in super hard variants.
- Layered Jump: Never seen, candidate for deletion.

**Comment by mmelwen** [comment]
1.	Selfish focus inversion: bad for tempo doesn’t hurt to keep, it suppose to be rarely used anyway
2.	2 saves off chop 1st turn: never see that work but I want to keep it anyway
3.	Hesitation CM: Never seen that move, in favour for deletion
4.	Prophetic finesse: I like prophetic we should use them more is true!
5.	Cursed Finesse Never seen that move either, in favour for deletion
6.	Rank choice ejection: is super consistent with the save to play logic we have, I like it, I would like to keep it.
7.	Self color ejection; Never seen, in favour for deletion.
8.	Prophetic discharge: Same as prophetic finesse, I would like to keep this since it can be useful in super hard variants.
found one today, and I didn't try it https://hanab.live/replay/699441#1 yellow to will, I will start tag them I believe they are could be really nice move!
9.	Layered Jump: Never seen that move, in favour for deletion

**Comment by Eliclax** [comment]
I'm generally in favour of keeping conventions as long as they don't contradict with other conventions, because some of the best moments in Hanabi are when you finally get to use a rare convention for the first time
1. Selfish focus inversion: never seen, but not sure if it's just because I'm not searching for it. Candidate for deletion ig.
2. 2 saves off chop 1st turn: have done it once, Bob bombed rip, imo we should remove iff we value scorehunting highly
3. Hesitation CM: Although I've never seen this move, this is one of those moves that many people would probably implicitly agree on even if this convention weren't official, so I think we should keep this one
4. Prophetic finesse: prophetic is pretty cool, and have seen it happen like twice, agree we should use them more.
5. Cursed Finesse: have seen the opportunity to perform it once, but it was out of level. If we had to delete something, this would probably be one of the first to go, although it does fall into the category of not causing a bomb if it's missed (on the other hand, all of the moves that fall into this category will cause a bomb if Alice did a truly suboptimal move and Bob/Cathy is responding to the "suboptimal-ness".)
6. Rank choice ejection: have used a few times. Even used as a fake pink clue, see https://hanab.live/replay/693225#2
7. Self color ejection: never seen, but I feel like this one could be useful
8. Prophetic discharge: Have seen it once before, along with prophetic finesse, it's pretty cool, would like to keep
9. Layered Jump: I've never seen before, but why could the skipped over card not be a useful card that is just not playable? I'm not sure why this is a convention in the first place.

**Comment by HelanaAsh** [comment]
1) Selfish Focus Inversion: I forget this exists, never seen it in game, has a higher vector for error at lower levels, but if we upgrade it to Advanced Moves, then I would be more inclined to use it.

2) 2 Saves Off Chop on the First Turn (3-player only convention): Used it a a few times, cant remember causing bombs if people pay attention, its useful enough to be kept imo.

3) The Hesitation Chop Move (From a Misplay): never seen, i would take it as a scream

4) The Prophetic Finesse (for 1's): Seen this a couple of times actually, was super cool. Recommend to keep it, its not super rare.

5) The Cursed Finesse: Seen this once or was discussed in review. Not sure if it has enough utility to ve kept.

6) The Rank Choice Ejection (with a number 2 or a number 5) (RCE): People like this a lot, and use it.

7) The Self Color Ejection: Never seen, deleting is fine.

8) The Prophetic Discharge: seen it done, could be super useful, recommend to keep.

9) The Layered Jump: Never seen, deleting is fine.

**Comment by pianoblook** [comment]
I rather like the idea of starting to build out a _Hard Variant Only_ Convention section, as @T-Hoodie mentioned. Reminds me of what the KiPiPi doc used to be called, tongue-in-cheek: _The Explosive Convention Guide_.

I suspect if we really pondered the convention goals, distinguishing between 'normal' and Hard variants, a lot of us would agree that Hard Variants are often enjoyed for their increased complexity and higher stakes. It would also maybe be a nice happy medium of being able to tidy up the main doc section while maintaining conventions that are arguably _good_ in theory, but deemed a bit too rare, risky, and/or complicated for standard play

**Comment by iamwhoiamhahaha** [comment]
Self Color Ejection
https://hanab.live/replay/700697#25

**Comment by TheDaniMan** [comment]
I agree with 1,2,3,5,9. 
Hesitation chop move from misplay should really happen only if the guy giving the finesse fucked up, and in that case typically people figure out what's up anyway.
For 4,8, I personally have not seen shadow finesses or prophetic finesses much, but think it's okay to still give them a chance, since they're on only in highly experienced games anyway.
I think RCE and SCE are both logically consistent with the theme of ejections in general, so for me they do not cause overhead, and I've actually seen them used successfully more than a few times. Perhaps only they need a caveat about when all twos/fives are playable (e.g, R1B2Y2P2 on the stacks, Bob is holding an unknown green card and Alice clues Cathy's r2 with number should not trigger RCE).

I'm generally opposed to a 'hard variant only' section because you are able to tune what kinds of conventions you want to use based on how well the deck is going anyway. Due to the high dependence of the difficulty of the deck on just how many 1s are at the top of the deck vs how many criticals, it makes more sense for players to decide on the spot, rather than agreeing before they see the deck.

**Comment by Zamiell** [comment]
> only infrequent because people don't look for them

we need to agree that this isn't a valid excuse.
if people are not looking for them, that by definition means they are a bad convention, because they are not coming naturally

**Comment by sjdrodge** [comment]
> we need to agree that this isn't a valid excuse.
> if people are not looking for them, that by definition means they are a bad convention, because they are not coming naturally

I don't buy this argument at all.

**Comment by Zamiell** [comment]
1) SFI - looks like consensus is to delete
2) 2 Save - seems mixed
3) HCM - looks like consensus is to delete
4) Prophetic Finesse - looks like consensus is to keep and/or move to hard-variant-only
5) Cursed Finesse - looks like consensus is to delete
6) RCE - looks like consensus is to keep
7) Self Color Ejection - looks like consensus is to delete
8) Prophetic Discharge - looks like consensus is to keep
9) Layered Jump - looks like consensus is to delete

**Comment by iamwhoiamhahaha** [comment]
another example for self color ejection :p
https://hanab.live/replay/709453#28
