### ISSUE TITLE
Translation pages

### ISSUE THREAD

**Issue by Pimak** [hanabi/hanabi.github.io#816]
As asked in #674 and #490, many people would love to have the pages in other languages.
As far I've seen and heard, people would like to translate it into French (myself and some of my friends), German, Spanish (#490) and Korean (#674).
I know that I will not keep updating the conventions.
I understand the concerns about the size of the convention to translate and the constant change in the conventions.
I have some answers for that :
1. Each page doesn't need to be translated, if only the first 8 levels are translated at first. A new person will only play at low level with the people from their community.
1. I want to point out that low level conventions don't change a lot, so if the translation isn't up to date for those pages, it won't be too far off.
1. If someone outlevels the available translated conventions, then he would go to the English up-to-date version. 
1. Each translated page (it could be done per translated convention even) can have a last updated date (based on commit history) and could show the English last updated date, so that someone reading the convention could know that this convention is up to date or outdated.

One thing I've already seen in a beginner convention guide in a pdf format which was made by a french group (not me) still keeps most of the English convention naming (eg. Chop, finesse, chop move, prompt (this was loosely kept)). So switching afterwards from a translated language to English won't be that bad.

**Comment by Zamiell** [comment]
> Korean (#674)

thats chinese not korean

> I want to point out that low level conventions don't change a lot, so if the translation isn't up to date for those pages, it won't be too far off.

i wouldn't be so confident as to make this claim

**Comment by Zamiell** [comment]
for example, we are currently considering moving finesses and prompts to a new level 2, and currently considering moving tccm to a new level 7

**Comment by Pimak** [comment]
Well compared to the higher levels, low level don't change as much.

**Comment by Zamiell** [comment]
sure. im confused though what this issue is actually proposing?

let me make my position clear.
as the maintainer of this repository, i refuse to officially maintain any other language than English.
if other people want to volunteer to maintain translations of this repository on their own repositories, i am not opposed to that, as long as they slap a warning on the front page that says:
"Since the conventions constantly change, this translation is almost certainly out of date. Please see the English version if you want a more accurate version: <link>"
