### ISSUE TITLE
"DIS" CLUES

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [hanabi/hanabi.github.io#826]
### Dis
- If a player gives a clue touching **two** cards (we can also define the rules for three or more cards if needed) and the non-focus card is *Trash*, where the clue giver has *Free Choice* to avoid *Bad Touch* while giving the clue, this action initiates a ***Dis***. In this situation, the first player (next to the clue giver) has to react (to the focus) as usual; and the second player has to blind-play their *Third Finesse Position* as a *Dis*.
- Compared to *Discharges*, a *Dis* is always on the second player (Cathy) to react the clue. Maybe we could name it as a *Jump Discharge* for this reason.
- Notes that this move conflicts with *Elimination*, i.e, Cathy has all the rest of the cards in her hand corresponding to the clue. But feel free to perform this move if you know Cathy is not gonna write the *Elimination Notes*.
  - We can also define a rule for *Dis* like how we defined the 5CE one-blind-play rule before.
  - For example, if it requires Cathy to take 3 or more *Elimination Notes* from the clue, then it's always a *Dis*.
- Examples and replays of *Dis Clues* are listed below:

#### Dis
- Examples
  - Red 1 is played. Donald has `red 2, red 1, blue 5, green 5` in hand (left to right).
  - Alice gives a red clue to Donald.
  - Bob does something unrelated.
  - Cathy blind-plays a green 1 from slot 3 as a *Dis* to tell Donald that his slot 2 (not-focus card) is *Trash*.
- Replays
  - (searching)

#### Dis Finesse
- Examples
  - Red 1 is played. Donald has `red 3, red 1, blue 5, green 5` in hand (left to right).
  - Alice gives a red clue to Donald.
  - Bob blind-plays a red 2 from slot 1 as a *Finesse*.
  - Cathy blind-plays a green 1 from slot 3 as a *Dis* to tell Donald that his slot 2 (not-focus card) is *Trash*.
- Replays
  - (searching)

#### Dis Bluff
- Examples
  - Red 1 is played. Donald has `red 3, red 1, blue 5, green 5` in hand (left to right).
  - Alice gives a red clue to Donald.
  - Bob blind-plays a blue 1 from slot 1 as a *Bluff*.
  - Cathy blind-plays a green 1 from slot 3 as a *Dis* to tell Donald that his slot 2 (not-focus card) is *Trash*.
- Replays
  - (searching)

#### Dis Ejection
- Examples
  - Red 1 is played. Donald has `red 5, red 1, blue 5, green 5` in hand (left to right).
  - Alice gives a red clue to Donald.
  - Bob blind-plays a blue 1 from slot 2 as a *5 Color Ejection*.
  - Cathy blind-plays a green 1 from slot 3 as a *Dis* to tell Donald that his slot 2 (not-focus card) is *Trash*.
- Replays
  - (searching)

#### Dis Discharge (Double Discharge)
- Examples
  - Red 1 is played. Donald has `red 1, red 1, blue 5, green 5` in hand (left to right).
  - Alice gives a red clue to Donald.
  - Bob blind-plays a blue 1 from slot 3 as an *Unknown Trash Discharge*.
  - Cathy blind-plays a green 1 from slot 3 as a *Dis* to tell Donald that his slot 2 (not-focus card) is also *Trash*.
- Replays
  - (searching)

#### Dis Charm
- Examples
  - In a *Rainbow* game. Red 1 is played. Donald has `rainbow 4, red 1, blue 5, green 5` in hand (left to right).
  - (Or a *non-Rainbow* game if *Dawn* on, where Donald has `red 4, red 1, blue 5, green 5` in hand)
  - Alice gives a red clue to Donald.
  - Bob blind-plays a blue 1 from slot 3 as a *4 Charm*.
  - Cathy blind-plays a green 1 from slot 3 as a *Dis* to tell Donald that his slot 2 (not-focus card) is *Trash*.
- Replays
  - (searching)

**Comment by pianoblook** [comment]
Definitely seems like this kind of thing is under-explored in 4p+. I like it!

These could combine nicely into a whole new Section, along with the _3-Hand "Composition"_ set posted awhile back (#687)

**Comment by Lel0uch-H** [comment]
Looks like a nice idea overall. I would warn against conflicts with trash touch elimination (https://hanabi.github.io/docs/level-16#trash-touch-elimination) in some cases, and double discharge as defined above is currently a charm (https://hanabi.github.io/docs/extras/charms/#the-unknown-trash-charm-utc).

**Comment by iamwhoiamhahaha** [comment]
> conflicts with trash touch elimination in some cases

Yeah I have mentioned *Elimination* above. I just forgot that it has a name

> double discharge as defined above is currently a charm

Yeah it does conflict with UTC

Btw, you can insert a link into a text with the commend `[](url)` to make your comment "cleaner"

**Comment by iamwhoiamhahaha** [comment]
Forgot to mention: Acknowledge to @Lel0uch-H for making me come up with this move in [this game](https://hanab.live/replay/700716#9) lol

He missed a UTD because I deferred playing into it and performed a 3 bluff (which is illegal). Then he discarded the purple 3 (thinking muddy 1) as a *Gentleman's Discard* on me. During the game, I thought he discarded it as ***Trash*** because I blind-played slot 3 from the purple clue.

**Comment by Romain672** [comment]
About the name 'Dis' is too close to 'Discharge' and give no translation in google translate, so is twice bad for me.

**Comment by Aigul9** [comment]
dis itself doesn’t follow the pattern and may cause confusion if cards touched by bob’s clue can potentially be among donald’s clued cards

**Comment by Dr-Kakashi** [comment]
I'm fine with this, of course we would avoid cards that are already touched in Bob's hand. I recommended that it should be an ejection over a discharge, as there are more playables in slot 2 over slot 3 as the game progresses. Jeff mentioned that it might affect consistency that we always discharge when trash cards are clued. I feel it's still clear to eject, as there are no conflicts and no other interpretations.

**Comment by Zamiell** [comment]
i dislike this proposal

> Red 1 is played. Donald has red 2, red 1, blue 5, green 5 in hand (left to right).
Alice gives a red clue to Donald.
Bob does something unrelated.

the problem is that generically, Cathy has no idea that Bob did something unrelated.
Cathy could be reacting to Bob's clue.
having this convention exists means that Bob has to constantly be aware that any possible clue that he gives can make Cathy think the wrong thing, and now Bob has to tip-toe around this fact.
it's like creating a web of lies that the other players get trapped in.
i prefer to not encumber Bob with any mind-games like this - it would be nice if Bob has the full freedom to decide what the best move is himself.

**Comment by iamwhoiamhahaha** [comment]
I just listed all the possible forms of *Dis* clues in this issue. I agree that Bob would be in a tough position in that situation. We could delete the first form and keep the other ones.

**Comment by Zamiell** [comment]
> We could delete the first form and keep the other ones.

with respect to information symmetry, Dis Finesse/Bluff/whatever doesn't have the same problem because it works like a double bluff.

> Dis Ejection

the example is weird because you would almost never have free choice in that situation.
consider if Donald has:

`red 5, red 1, green 3, green 4`

in this case, Alice just might choose to dupe a card in return for ejecting something.
it feels like this could be another situation of "not everything has to have a meaning" and give Alice the freedom to do the clues she wants.

> dis itself doesn’t follow the pattern and may cause confusion if cards touched by bob’s clue can potentially be among donald’s clued cards

yes, jeff or someone else should probably come up with a better name because "Dis clues" are not great =p

> Bob blind-plays a blue 1 from slot 3 as a 4 Charm.

it would be slot 4 right

> Jeff mentioned that it might affect consistency that we always discharge when trash cards are clued. I feel it's still clear to eject, as there are no conflicts and no other interpretations.

i feel like that is hard to remember / counter-intuitive

**Comment by iamwhoiamhahaha** [comment]
> the example is weird because you would almost never have free choice in that situation.
consider if Donald has:

O that's true. But you might have free choice in a rainbow game though. Like the 4 Dis-Charm example, if the 5 is a rainbow 5

> it would be slot 4 right

Yeah, it's slot 4

> jeff or someone else should probably come up with a better name because "Dis clues" are not great =p

Yeah, sure we could have a different name if someone comes up with a good one. But *Dis* sounds really interesting to me lol

**Comment by Dr-Kakashi** [comment]
Main words:
Taking out the trash (TOTT)
Garbage
Waste
Rummage 
Scrap 
Shavings
Sweepings 

+ Ejection/Discharge

For example: Garbage Discharge

**Comment by iamwhoiamhahaha** [comment]
I like ***Scrap***

*Scrap Dinosaur* is one of my favorite decks in YuGiOh 😂😂

**Comment by T-Hoodie** [comment]
If we agree that it conflicts with UTC, then we can also just generalize the Junk Ones Charm into Bad Touch Charms.
Example:
Red 1 is played. Donald has red 2, red 1, blue 5, green 5 in hand (left to right).
Alice gives a red clue to Donald.
Bob charms, playing his fourth Finesse Position.  Donald knows this cannot be r4, because r4 is not a valid charm target for a 4-charm. Therefore it must be a Bad Touch Charm, and he marks his slot 1 as playable and his slot 2 as known trash.

Pros of a Bad Touch Charm: 4 charms are common early, but very rare in the later game. Trash however is sparce in the early game, and gets more common in the later game. So I don't see many potential conflicts with 4 charms. Additionally this could make it easier to efficiently play clue chop moved cards in a later stage of a game, when any potential direct play clue might be blocked.

I would give both the BTC and the Dis a try, and find out how efficient they actually are.

**Comment by Zamiell** [comment]
post examples of it being used

**Comment by TheDaniMan** [comment]
https://hanab.live/replay/734505#16
It's not really clear whether it was intended to work this way, but the clue seemed to have worked.
I'll add that I really don't like the idea of forcing the next player to do something unrelated that cannot be confused for a simpler convention, and that if Bob does not have a third finesse position then it's really easy to mistake the clue for an OOP UTD, but perhaps if the convention is restricted to the finesse/bluff version (to be demonstrated immediately) then it can be consistent.

**Comment by Zamiell** [comment]
i guess ill close since jeff isn't posting any examples

**Comment by iamwhoiamhahaha** [comment]
https://hanab.live/replay/770430#21

- MKQ clues red to maxupicchu touching rainbow 3 and red 1
- Tailz blind-plays green 3 from slot 1
- frosty104 blind-plays green from slot 3

**Comment by iamwhoiamhahaha** [comment]
https://hanab.live/replay/798276#1
- omegaxis gives a yellow clue to BlueNovember (It's not a *Triple O* since omega could just give a 4 clue instead)
- HelanaAshryvr blind-plays a green 1 from slot 4
- Nitrate blind-plays a light pink 1 from slot 3
- BlueNoevember now knows the yellow cards on slot 1 and slot 2 are duped.

**Comment by iamwhoiamhahaha** [comment]
<https://hanab.live/replay/891945#1>
- SpikedJackson gives a yellow clue to hnter01 touching orange 4 and yellow 1
- WillFlame blind-plays a yellow 1 from slot 4 as a *4 Charm*
- Klyzx blind-plays a red 1 from slot 3 as a "dis"
- hnter01 now marks their slot 1 as known trash
