### ISSUE TITLE
Clarification if Finessed Cards are Clued Cards

### ISSUE THREAD

**Issue by T-Hoodie** [hanabi/hanabi.github.io#830]
From the doc: Even though Finessed cards are unclued, you can think of them as having an invisible clue on them. (Because they are already "gotten".)
I would assume that they are treated exactly as clued cards accordingly, and e.g. the section on Stacked Ejections seems to support this.
In practice however many players treat them as clearly unclued. This can cause some issues with e.g. Chop Focus if a finessed card is on chop or with null positionals.
Can we set a clear precedent on how they should be treated in the doc?

**Comment by Zamiell** [comment]
> In practice however many players treat them as clearly unclued. This can cause some issues with e.g. Chop Focus if a finessed card is on chop or with null positionals.

can you type out an alice and bob story

**Comment by TheDaniMan** [comment]
Timehoodie should add to this if he has something else in mind, but I actually have 2-3 very related issues.
Example 1: 3p no variant game, turn 1. Cathy's hand is r1r2r3b4r4. Alice and bob have only yellow/green/purple cards.
Alice clues 4s to Cathy, performing a triple finesse. Bob and Alice clue and play some cards in each other's hands while Cathy plays r1r2. Alice then clues blue to Cathy, touching slots 1,2,4.
What is the focus of this clue? Is it slot 2, since r3 is a known finessed card?

Example 2: similar to the above, 3p no variant game, turn 1. Cathy's hand is r1b1g1r2r3. Alice and bob have only yellow/purple cards.
Alice clues 3s to Cathy, performing a double finesse with two layers. Bob and Alice clue and play some cards in each other's hands while Cathy plays r1b1. Alice then clues blue to Cathy, touching slots 1,2.
What is the focus of the clue now? even though g1r2 are both finessed and slot 2 is next to discard, slot 4 is not considered clued by Cathy, so is it okay that Cathy doesn't know the focus of the clue until she finishes blindplaying? Note that in this situation, Cathy is legally allowed to immediately play her blue cards for priority reasons, since she has already demonstrated the finesse.

The next example regards the interaction between stacked bluffs and stacked ejections.

Example 3: 3p no variant game, turn 1. Alice clues Cathy yellow to her yellow 3. Bob plays slot 1, and it is y1. Cathy clues 5 to Bob's chop, touching two 5s. Is it possible for Alice to stack a 5ce on Bob, who is finessed for his second card? Conventionally, it seems very clear that a stacked ejection calls for first finesse position. Suppose Alice gives a blue clue to Cathy touching two blue cards and Bob plays slot 1. Perhaps the two blue cards are 2 and 1, causing it to be an obvious bluff, or in another situation there may be some other reason jointly known to Alice and Bob that would make Bob think he cannot possibly be layered for the requested card.

In practice I see players simply play the corresponding unclued card and never attempt to stack an ejection on someone finessed for slot 2, a discharge on someone finessed for slot 3 etc.

It seems like for all of these purposes, the situation is simplified if finessed cards are treated as unclued, and stacked ejections call for slot 2.

**Comment by T-Hoodie** [comment]
4p Null Variant.
Bobs Starting Hand is u1 u2 r1 y5 . In the first turn of the game Cathy clues red to Donald, touching a red 2 and initiating a layered Finesse on Bob. Later on Bob blind played u1 and u2, y5 got clued at some point, and r1 becomes a globally known card. No blue cards have been played.
Example 1:
Cathy clues Blue to Alice, focusing a b2. Bob doesn't see a b1 on anyone elses Finesse Position, and on his turn tries to play his slot 1 as b1, bombing red 3. In the review Cathy explains she expected Bob to treat the red 1 as a blind play and he would play it before trying to play b1; and that Donald would patch the Finesse with his known r2.
Example 2: (Identical to TheDaniMans first example, feel free to skip)
Alice clues Blue to Bob, touching both of his unknown cards on slot 1 and slot 2. Bob considers his r1 to be a globally known clued card, and tries to play his slot 2 as a chop focus on b1, bombing b3. In the review Alice explains she believed that because the red 1 is unclued, Bob had no reason to discard, and she assumed the chop to be the rightmost unclued card. Accordingly she thought the focus was on slot 1.
Example 3:
Alice clues Blue to Donald, focusing a b4. Bob knows this should be a color positional, and believes he should play his right most unclued card. He considers the globally known r1 to be clued, and plays his slot 2, which bombs as a b3. In the review Alice explains she believed that the blue clue would indicate that Bob should play his slot 3, the globally known r1, and she expected Bob to play his first finesse position instead because a null positional on a non-null card is nonsensical.
Example 4:
Same as Example 3, but with Green instead of Blue: Bob tries to blind play his slot 1 because he thought he should treat the r1 as a clued card.

In all of the examples Bob treated his card like a clued card, whereas the clue giver considered it to be unclued, resulting in a mistake.
I would like a clarification to what extend globally known cards without a clue on them should be treated identical to clued cards or unclued card.

**Comment by TheDaniMan** [comment]
In Example 1, the situation is covered by the Stacked Bluff (Exception), and must be demonstrated immediately, so by our current conventions Cathy is making a mistake.

**Comment by T-Hoodie** [comment]
Cathy is not Bobs Bluff Seat, so it doesn't qualify for a Stacked Bluff.

**Comment by Zamiell** [comment]
time for the love of god please fucking put alice as the person cluing, why the fuck is cathy going first on the first turn of the game

i'll respond to the examples once they are fixed

**Comment by Zamiell** [comment]
> Example 1: 3p no variant game, turn 1. Cathy's hand is r1r2r3b4r4. Alice and bob have only yellow/green/purple cards.
Alice clues 4s to Cathy, performing a triple finesse. Bob and Alice clue and play some cards in each other's hands while Cathy plays r1r2. Alice then clues blue to Cathy, touching slots 1,2,4.
What is the focus of this clue? Is it slot 2, since r3 is a known finessed card?

focus of the clue is slot 4 as chop focus

**Comment by Zamiell** [comment]
> Example 2: similar to the above, 3p no variant game, turn 1. Cathy's hand is r1b1g1r2r3. Alice and bob have only yellow/purple cards.
Alice clues 3s to Cathy, performing a double finesse with two layers. Bob and Alice clue and play some cards in each other's hands while Cathy plays r1b1. Alice then clues blue to Cathy, touching slots 1,2.
What is the focus of the clue now? even though g1r2 are both finessed and slot 2 is next to discard, slot 4 is not considered clued by Cathy, so is it okay that Cathy doesn't know the focus of the clue until she finishes blindplaying? Note that in this situation, Cathy is legally allowed to immediately play her blue cards for priority reasons, since she has already demonstrated the finesse.

"so is it okay that Cathy doesn't know the focus of the clue until she finishes blindplaying?"
i guess Cathy is supposed to retroactively re-determine the focus of the clue after she finishes blind-playing, yes.
however this is prone to failure so in practice i would say that alice is making as mistake as per this section: https://hanabi.github.io/docs/level-13/#clarity-principle

**Comment by Zamiell** [comment]
> Example 3: 3p no variant game, turn 1. Alice clues Cathy yellow to her yellow 3. Bob plays slot 1, and it is y1. Cathy clues 5 to Bob's chop, touching two 5s. Is it possible for Alice to stack a 5ce on Bob, who is finessed for his second card?

undefined, alice should never give this clue: https://hanabi.github.io/docs/level-13/#clarity-principle
if alice made a mistake and did it anyway, i imagine that blob would play slot 3, because:
- slot 2 is a yellow 2, that can't be played right now because bob has to react
- playing slot 1 would make cathy's card look like a one-away-from-playable card
- playing slot 3 is the only other alternative

**Comment by Ibot02** [comment]
> focus of the clue is slot 4 as chop focus

slot 4 is not a newly touched card - it was clued as a 4 with the r4 before.

**Comment by Zamiell** [comment]
i meant slot 3 as chop focus
