### ISSUE TITLE
Rename the convention framework

### ISSUE THREAD

**Issue by DarthGandalf** [hanabi/hanabi.github.io#832]
since you want it to an issue instead of PR, fine

ref #831

**Comment by NumerateClutter** [comment]
I agree with this change. I believe we should implement it ASAP, since it's rather rude of us to be using Hyphen-ated's name against his will. We're effectively branding these documents as his even though he rejects this branding.

There can be a more drawn-out discussion about proper naming, but "H-group" seems like a very nice, clear, unambiguous solution that can be implemented immediately while we figure out a better name for the conventions and group.

**Comment by Zamiell** [comment]
For now, I've taken the steps to rename "Hyphen-ated" to "Hyphenated" out of respect for the actual person Hyphen-ated, since that seems like it is relatively non-controversial.

I am against renaming the convention framework from Hyphenated to anything else, because he doesn't have any right to the English word of Hyphenated any more than I have the right to my real-life name of James, and so on.

**Comment by sjdrodge** [comment]
H-Group seems like a good official name to me. We can backronym it to mean Hanab.live instead of Hyphen-ated. @Hyphen-ated is that a solution you'd be happy with?

The argument that Hyphenated is technically an English word doesn't impress me very much. The system clearly has nothing to do with that word.

**Comment by DarthGandalf** [comment]
H-Group is how @Zamiell already renamed the purple roles on discord recently: "H-Group Community Leader", I didn't just invent this from nowhere

**Comment by Zamiell** [comment]
I only named it that because if the role name is too long it gets cut off, and then you would be unable to see the words "Community Leader".

**Comment by EhDrone** [comment]
I'll add a few points:
1) Hyphenated or H-Group Conventions are both fine to me. I think it will be ultimately trivial for people calling it Hyphenated to switch their reference window to HGroup Conventions. 
2) Hyphenated is a valid name for a convention set as much as 'Logic Only' is a name for a convention set. It no longer matches Hyphen-ated's name is a true statement.
3) There is a clear history and connection between Hyphen-ated Conventions and Hyphenated, so even though Zamiel is correct that Hyphen doesn't own the word, I think dealing with the issues that others will maintain with the name being Hyphenated vs Hyphen-ated is a larger ordeal than just changing the name so that everyone can move past this. 

I disagree that we need Hyphenated's explicit blessing to change the name to HGroup or any other word that is not Hyphenated because regardless of the history, the game is also called Hanabi, and many other H words are applicable. HGroup Conventions seems like a natural potential new name for the doc with minimal shift in mindset for the community, many of whom already refer to it as HGroup anyway.

Green role can also be changed to 'H-Group Community Member' to coincide with the new purple role name. 

If there are large technical/sweeping efforts to rename from Hyphen-ated to HGroup in the doc, then perhaps people other than Zamiel can help sweep through it and make the required changes. 

Lastly, if you guys want to change the name to ADrone Conventions, go for it :).

**Comment by sjdrodge** [comment]
> 2. Hyphenated is a valid name for a convention set as much as 'Logic Only' is a name for a convention set. It no longer matches Hyphen-ated's name is a true statement.

Sure, and chodeloversanonymous is also technically not a word so it wouldn't make sense for anyone to object to that name.

> I disagree that we need Hyphenated's explicit blessing to change the name to HGroup or any other word that is not Hyphenated because regardless of the history, the game is also called Hanabi, and many other H words are applicable. HGroup Conventions seems like a natural potential new name for the doc with minimal shift in mindset for the community, many of whom already refer to it as HGroup anyway.

Nobody suggested that we require Hyphen-ated's sign-off on a new name, but I think for many of us, it's desirable to pick a name that Hyphen-ated is okay with, given the history of their name being used against their explicit wishes for so long.

> If there are large technical/sweeping efforts to rename from Hyphen-ated to HGroup in the doc, then perhaps people other than Zamiel can help sweep through it and make the required changes.

DarthGandalf already did that work, see the original PR.

**Comment by DarthGandalf** [comment]
> DarthGandalf already did that work, see the original PR.

Most of it. I didn't touch 2 places: name of voice channels, because that needs to be synchronized with renaming of the channels, and the setting name on hanab.live

**Comment by EhDrone** [comment]
Just because I am not sure if Stephen thinks I disagree with something - my stance in two sentences:

I am in favor of changing the name mostly out of respect for the people who have a larger issue with it. I think the issues that MAY arise with changing the name are far smaller than the issues we currently have with keeping it.

Also - cool the PR is done, minimal work would be needed to update on the server itself to reflect it. And damn - I think stephen found my alt account >chodeloversanonymous

**Comment by RaKXeR** [comment]
I would like to know, did the definition of the word hyphenated impact at all the choice of name for the conventions and group? I've been trying to discourage usage of this name for years, so using "it's too late now because people are used to the name" is quite a suspicious argument. Me and many others have called and encouraged calling the group by other names (usually settling on H-Group) not to lead people into thinking executive decisions and group direction was endorsed by @Hyphen-ated .

It really is about time (I would say at least 2-3 years too late though) to state who the group really belongs to, whether that's @Zamiell or multiple trusted members of the community.

**Comment by Hyphen-ated** [comment]
> H-Group seems like a good official name to me. We can backronym it to mean Hanab.live instead of Hyphen-ated. @Hyphen-ated is that a solution you'd be happy with?

Sure.

> I would like to know, did the definition of the word hyphenated impact at all the choice of name for the conventions and group?

No. Zamiel simply named them after me.

I have had multiple experiences with people meeting me and automatically disliking me and/or saying they refuse to play Hanabi with me because they think I am responsible for Zamiel's convention system.

**Comment by iamwhoiamhahaha** [comment]
How about ***Zamiel Conventions***? (See: https://github.com/hanabi/hanabi.github.io/issues/104#issuecomment-558928389)

**Comment by DarthGandalf** [comment]
> How about Zamiel Conventions? (See: #104 (comment))

Only if to put Zamiel on the other side of the unwanted usage of name bullying. Oh, no, we'll respect his wishes to not use his name, and name the conventions "Za-miel" instead, because [za](https://dictionary.cambridge.org/dictionary/dutch-english/za) and [miel](https://dictionary.cambridge.org/dictionary/spanish-english/miel) are existing words, not related to Zamiel at all. Just like Hyphenated is not related to Hyphen-ated.

/sarcasm

H-Group doesn't have that problem at least

**Comment by T-Hoodie** [comment]
If Hyphen-ated does not want the conventions to be named after him, we should change it.
I think it would also be a good opportunity to invite a larger part of the community to participate in the process of choosing a new name and/or logo for the discord. I assume that a large part of the community is unaware of a lot of the discussion going on here because they treat it as a place where the high level players meet to discuss potential convention changes.
As of right now, a part of the community feels like they have no say in what is happening, and asking them to help shape a lasting part of our community might go a long way - even if it is more of a symbolic thing.

**Comment by mmelwen** [comment]
Agree with Time, this is a good topic - thread to have on discord under a text channel called, community discussions or something relative where people can propose whatever they want

**Comment by Zamiell** [comment]
@DarthGandalf can you submit a pr to rename "Hyphenated" to "H-Group"?

**Comment by DarthGandalf** [comment]
@Zamiell the easiest is to just revert your changes from Hyphen-ated to Hyphenated, and then merge #831

**Comment by Zamiell** [comment]
i renamed it manually to h-group for now
