### ISSUE TITLE
[Convention proposal] Final Unplayable Suit Stall Clue

### ISSUE THREAD

**Issue by jack67889** [hanabi/hanabi.github.io#848]
Inspired by what [Romain672 posted](https://discord.com/channels/140016142600241152/776176933120507964/935891067482570832) today, I think this situation is common enough to turn into a convention/strategy tip. Since I think (didn't look for examples though) it's a common error and it's just always better to stall in similar cases. Holding the 4 of an unplayable suit and drawing the 5 de facto reduces the pace by *# of players - 1*, something similar applies to other ranks. You can't really afford a bomb in those tricky end-games, since it costs a clue that you might need to win, while waiting for the last missing card(s) to show up.

### Final Unplayable Suit Stall Clue

- When the cards of all the suits but one are played or globally known up to rank 4. We call the remaining suit the *Final Unplayable Suit*.
- If you hold a card from the *Final Unplayable Suit* (that can’t be redistributed with certainty), can’t give a play clue and can’t play a card; you should give a stall clue if a card(s) with a rank directly below and/or above yours is still missing. We call this the *Final Unplayable Suit Stall Clue*.
- If the conditions for the *Final Unplayable Suit Stall Clue* apply to multiple players and there aren’t enough clues for all to stall, make sure the player(s) holding the card(s) higher in rank have a clue available to give a *Final Unplayable Suit Stall Clue*.
- Note that even when it’s not end-game yet, a *Final Unplayable Suit Stall Clue* should be given . Since this always improves the de facto pace and chance of winning.
- If there is no clear stall clue available, you should stall by giving a clue that looks like a trash chop move to the next player. This should be treated as a *Final Unplayable Suit Stall Clue* when applicable, since a chop move would usually be non-sensical at this stage of the game.
- For example, in a 3-player game:
    - Red 5, yellow 5, green 5, blue 4 and purple 1 are played on stacks.
    - Alice is holding the only visible copy of purple 4. Bob is holding the only visible copy of purple 3. Cathy’s hand is trash.
    - Since both Alice and Bob are holding a card from the *Final Unplayable Suit* of which a card with a rank directly below and/or above is missing (purple 5 for Alice, purple 2 for Bob) they should give a *Final Unplayable Suit Stall Clue* when a clue is available.
    - There is 1 clue available. The rank of Alice her card is higher, so she should take the clue and make Bob discard. Because if Alice would draw purple 5, this effectively reduces the pace by 2, since both Bob and Cathy won’t have a play on the final round.
    - Alice gives what looks like a trash chop move to Bob. However, Bob knows he should interpret this clue as a *Final Unplayable Suit Stall Clue*, since it’s important that Alice can stall in this case and he saw no other obvious stall clue for Alice to give.

**Comment by Romain672** [comment]
First problem, kinda resolved:
"If you hold a card from the Final Unplayable Suit (that can’t be redistributed with certainty), can’t give a play clue and can’t play a card; you should give a stall clue if a card(s) with a rank directly below and/or above yours is still missing. We call this the Final Unplayable Suit Stall Clue."
=>
"If you hold a card from the Final Unplayable Suit (that can’t be redistributed with certainty), can’t give a play clue and can’t play a card; you should give a stall clue if a card(s) with a rank directly below and/or above yours is still missing AND NOT PLAYABLE. We call this the Final Unplayable Suit Stall Clue."

Second problem I see:
Played all but r2
Discarded: r3, r4
Alice: x-x-x-x
Bob: x-x-x-(r3)
Cathy: x-x-x-x
Donald: x-x-x-x
Emily: x-x-x-(r5)
You want Cathy & Donald to discard to draw r4. And here Alice got no play.
But maybe that can be considered as rarer. So for later.

**Comment by Romain672** [comment]
To anyone reading this not familiar with end game optimisations, I advise you my guide:
https://docs.google.com/document/d/1jKFqt9WbWAc1Dj3M2E_kwDwS3J0xeIp0UNkiqkLLApk/edit

**Comment by Romain672** [comment]
I did lots of edits.
Like you have seen, there is so many conditions, which make it pretty hard to create rules which work all the time.
I like my actual result though.

**Comment by pianoblook** [comment]
I'd request this be named _Bottleneck Stalls_, since that's what I've mainly heard it referred to. 

Definitely an important optimization tool, but sort of doubtful to be a good fit for official inclusion - recognizing these stalling situations can be super hard when there are still a decent number of cards left in the deck. 

I'm all for it personally, since even though it'll probably lead to an increase in bombs in the short term I think it's a great strategic consideration to start normalizing

**Comment by Romain672** [comment]
So I again edited a lot this post: I added examples, corrected some of the mistakes remaining, merged case 1 and 4, and there it is.

My problem with that proposition, is that imo, my case 2 & 3 are more likely, even if more obvious. So if 1 is added, 2&3 should be added first imo. Else 1 should be considered as an 'end game situation'.

(I think it's the post I made the most edits ever)

**Comment by iamwhoiamhahaha** [comment]
I like the idea but the probability seems quite low. It decrease the ability to perform a normal play clue and increases the complexity if someone is in that stalling situaion.

In a *No Variant* game, there are 50 cards and there are 5 pairs of 2s for each suit. Let p be the probability of a random pair of 2s on the bottom of the deck:

p = 5/50/49 = 0.2%

(correct me if my math is wrong)

**Comment by Romain672** [comment]
First it's (2/50)*(1/49)*(5suits)=0.4%.
Multiply that by 2 because pairs of 3s have same problems.
Reduce it in case randomly the right players would draw the missing card.

Now, only for missing 2s, you can lose if 4/3/5 are out of order, like oh the game highlighted. On those case, that matter when then 2s are in three last cards of the deck:
(3/50)*(2/49)*(5Suits)=1.2%

1.2% (2s) + 0.4% (3s) = 1.6%

**Comment by Romain672** [comment]
Hi, feel free to do edits here: https://docs.google.com/document/d/1KSs3s1La4V4Go-_t-Y07gs40KJOoVXoXMrtXeXmXcd0/edit

 ### Final Unplayable Suit

   * When the cards of all the suits but one are played or globally known up to rank 4. We call the remaining suit the _Final Unplayable Suit_.

  * That suit must be carefully planned to optimize the end game.


 ### Final Useful Draw

  * When the number of cards in the deck is equal to 2 and a card in the suit is missing, you want for a person between the card below it (not included) and above it (not included) to do the next discard. If the card below it is already played, replace it by the holder of the 5 (included).
  * That number 2 can be higher in specific situations (if more than one suit is problematic)
  * For example, in a 3-player game:

     * There are exactly 2 cards on the deck left, 7 clues are available, and Red 5, yellow 5, green 5, blue 5 and purple 2 are played on stacks.
    * Purple 3 is still missing
    * Bob is holding the purple 5
    * Cathy is holding the purple 4
    * Alice should normally discards since she got nothing to clue
    * But here, there is exactly 2 cards left on the deck. She must take attention to which player discard.
    * Here, discarding would make Alice draws purple 3. Then, purple 3, 4, and 5 would be out of order.
    * To avoid that, Alice clues 5 to Bob as a stall.
    * Bob discards
    * Cathy clues 3 to Bob on purple 3
    * Alice clues 3 to Bob on purple 3
    * Bob plays purple 3
    * Cathy plays purple 4
    * Alice clues 5 to Bob on purple 5
    * Bob plays purple 5


 ### Final 5 non-play

  * When a player is holding a playable 5, he should in most cases play it
  * In some cases, if playing it would not make enough stalls clues available, he should delay by clueing
  * For example, in a 3-player game:
    * There is exactly 1 card on the deck left, 7 clues are available, all cards except Red 5 and Yellow 4 has been played on stacks.
    * Alice is holding the red 5
    * Bob is holding the yellow 5
    * Cathy is holding the yellow 4
    * Alice should normally plays her red 5, but wait, playing it would start the last turn, and then Bob would not be able to play his yellow 5
    * Alice give a stall clue
            * Bob discards or give a stall clue
            * Cathy plays y4
            * Alice plays r5
            * Bob plays y5




 ### Final non-5 non-play

  * Sometimes, you should not play your non-5 for the same reasons than as Final 5 non-play.
  * When a player is holding a playable card (and in most cases if it's his single playable) which can be played during the last turn, and if not playing the card would make the team be able to stall enough turns to increase the max score, he is allowed to **discard** or to do a  **Generating Final Not Playing Stall Clue** with Rank.
  * Remember that playing a 5 is never worst than discarding (outside of clue starved variants)
  * For example, in a 3-player game:
      
    * There is exactly 2 cards on the deck left, 0 clue are available, and Red 5, yellow 5, green 4, blue 4 and purple 3 are played on stacks.
    * Alice is holding the purple 4
    * Bob is holding the purple 5.
    * Cathy is holding the green 5 and the blue 5.
    * Alice should normally plays her purple 4 since it's playable. But here, playing it would force Bob to start last turn.
    * Furthermore, not playing her non5 card would let players be able to stall one more turn, and here that would make Cathy be able to start the last turn which is great since she got two plays
    * Alice discards
    * Bob clue 5 to Cathy as a stall clue thanks to the clue generated by Alice
    * Cathy plays green 5
    * Alice plays purple 4
    * Bob plays purple 5
    * Cathy plays blue 5




 ### Final Unplayable Suit Stall Clue

  * Sometimes, close to the end game, it's good to stall. When it's the case, we call the stall a **Final Unplayable Suit Stall Clue**.
  * There are at least two cards from the final unplayable suit stall clue missing.
  * You usually should give one if all the following conditions are met:
    * you hold a card from the Final Unplayable Suit (or you draw none, and either drawing the highest one would make the numbers of that suit out of order OR you drawing the lowest, then the highest would make the game lost)
    * you can't give a normal play clue
    * number of clues isn't a problem: you are not in case ‘Final non-X non-play’ above
    * it's still possible that all numbers between your card and the 5 can be played during last turn (or the specific(s) person(s) drawing the highest missing card would make all the cards between one lower the highest missing card and the 5 be possible to be played during the last turn)
    * all players between you and the 5 (or all players you want to not discard) can play or give a clue as many turns as needed 
  * Note that even when it’s not end-game yet, a _Final Unplayable Suit Stall Clue_ should be given . Since this always improves the de facto pace and chance of winning.
  * If there is no clear stall clue available, you should stall by giving a clue that looks like a trash chop move to the next player. This should be treated as a _Final Unplayable Suit Stall Clue_ when applicable, since a chop move would usually be non-sensical at this stage of the game.

   * For example, in a 3-player game:
       
       * All cards except red 3 are played on stack
       * Alice is holding the only visible copy of red 4
       * Bob and Cathy have only trash card
       * Alice check the board state:
                    * Red 3 & Red 5 are missing
                    * she is holding a card from the Final Unplayable suit
                    * she can’t give a normal play clue
                    * there is 7 clues in bank: it’s not a problem
                    * it’s possible for the whole red suit to be played during the last turn: Cathy can play r3, Alice r4, and Bob r5
                    * she is the only one which should stall here so number of clues isn’t a problem
       * Therefore, Alice give a Final Unplayable Suit Stall Clue with rank
       * Bob and Cathy will assume that clue is a 5-stall and usually will discard

**Comment by Romain672** [comment]
Just a remark "Final Useful Draw" and "Final 5 non-play" are really easy.
But writing them make it easier to wrote what follow since we can ignore/refer to those cases.

**Comment by pianoblook** [comment]
The probability of any given pair to be on the bottom increases exponentially as the deck size goes down. For a simplified example, let's consider the risk of double bottom deck (DBD) g2 over the course of the game:

- early-game (32 cards left) = (2/32)*(1/31) = 0.2%
- mid-game (16 cards left) = (2/16)*(1/15) = 0.83% (4 times as likely)
- late game (8 cards left) = (2/8)*(1/7) = 3.57% (4 times again)

So each time you half the deck size, you quadruple the chance.

I guess more generally it'll be (n/d)*(1/d-1) = n/(d^2-d), where n = # of unseen cards (e.g. 2s and 3s), and d = deck size.

The d^2 in the denominator explains the exponential shift. *But*, n usually drops rapidly through the game, so it makes sense that players don't usually end up perceiving an actual threat until around d = 10 or so.

**Comment by Romain672** [comment]
Just as a comparaison for 2s and when 4/5 has a chance to be out of order (since if both 2s are in the last 3cards of the deck, you need to have 4&5 in differents hand):
 - early-game (32 cards left) = (3/32)*(2/31) = 0.6%
 - mid-game (16 cards left) = (3/16)*(2/15) = 2.5%
 - late game (8 cards left) = (3/8)*(2/7) = 10.7%

But you should double piano's number because the 3s got same problem

**Comment by pianoblook** [comment]
> But piano's numbers can be about 2s or 3s.

Like I said, that was a "simplified example".

The more generalized calculation is based on what I wrote: "where n = # of unseen cards (e.g. 2s and 3s),"

**Comment by jack67889** [comment]
> I'd request this be named Bottleneck Stalls, since that's what I've mainly heard it referred to.

Sounds good to me.

> I like the idea but the probability seems quite low.

As noted by Romain it also applies to 3s, of which it's more likely to lose one early on. It also depends on how many clues are still available and how many cards still need to play, so it's hard to make an exact calculation of the odds. Since for example holding the 4 and drawing the 5 can reduce the pace by *# of players - 1* it can certainly be that the 2s need to be a lot higher in the deck to win and make a difference by stalling at the right moment.

> It decrease the ability to perform a normal play clue

It seems to me that this hardly ever reduces the ability to give a play clue, but maybe I'm missing something.

@Romain672: I've marked a few points below. I tried to make sure the proposal is relatively simple and generally applicable. That means that indeed it doesn't tell who should draw a card optimally (which depends too much on the circumstances to easily codify I would think), but at least it tells who shouldn't draw a card. Maybe this can also indirectly increase the awareness of players about who should draw.

- Why two cards missing? It also applies when only the 3 is missing for example right?
- Could you explain why you removed the directly above or below part? For example holding the 5 and drawing the 4 is almost as bad as the other way around. While when only the 3 is missing it's a lot more likely that it might be better if you draw while holding the 5, no?

I'm also hoping a bit that if this conventions works in practice, you can write elimination notes for a missing unclued card in your hand, when someone doesn't stall, because you are holding the higher card and should (now) stall instead. (For example when Alice is holding a critical 3, the 2, 4 and 5 are missing and Bob drew a 4 last round.)

**Comment by Romain672** [comment]
If only one card is missing: #850

**Comment by Romain672** [comment]
> * Could you explain why you removed the directly above or below part? For example holding the 5 and drawing the 4 is almost as bad as the other way around. While when only the 3 is missing it's a lot more likely that it might be better if you draw while holding the 5, no?

Because if r2 & r4 is missing you are holding all the copies of r3, and your next player hold r5, your way tell to stall while it's actively bad.

**Comment by Romain672** [comment]
> I'm also hoping a bit that if this conventions works in practice, you can write elimination notes for a missing unclued card in your hand, when someone doesn't stall, because you are holding the higher card and should (now) stall instead. (For example when Alice is holding a critical 3, the 2, 4 and 5 are missing and Bob drew a 4 last round.)

Already did it 3 times I believe. But none which matter. More to point out a potential mistake.

**Comment by Romain672** [comment]
Just did another rework :D
I initially seperated the initial post in 2cases, but now it's separated in 6 cases, we lost the global formula, but it let players not familiar with end game just open the page, check the right section, then see if he is in that case.
Look like a great section now.

I think people who would want a global formula can see the reasonning behind all 6 cases.

**Comment by Zamiell** [comment]
this is too much for the doc, can you start your own end-game optimization guide or something?
i want to keep the doc simple

**Comment by Romain672** [comment]
From what I have seen recently, those conventions and the 'non-5 non-play' one **occurs** a lot, maybe 10%+.
The 'non-5 non-play' always **matter** when it can be done.
This one **matter** in a lot less cases. I'm unsure to have seen a single occurence of it which really matter outside of puzzles.

But I'm happy to now think I got something complete about those.

**Comment by Romain672** [comment]
The main reason I wanted to add it, is that it let you make stalling clues illegal outside of those case.
Which look great because actually you can have lots of lots of undefined spots, where you don't know at all if you must: play (as usual)/not play (#851)/discard (as usual)/not discard (pace 0)/stall (#850)/not astall (negative of #848).
