### ISSUE TITLE
Positional Misplay Clarification

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#868]
The Positional Misplay (Indicating a Play with a Misplay)
https://hanabi.github.io/docs/level-7#the-positional-misplay-indicating-a-play-with-a-misplay
The above link is for positional misplay of chop.

The Double Positional Misplay (Indicating Two Plays with a Misplay)
https://hanabi.github.io/docs/level-7#the-double-positional-misplay-indicating-two-plays-with-a-misplay
The above link occurs for a positional misplay of all slots, excluding chop.

I believe we should show the Single Positional Misplay before the Double Positional Misplay. 

Single Positional Misplays should happen when they are "necessary"
This occurs when players are unable to positional discard any slot, excluding the chop, as they may be discarding a playable card during end game. 
They are misplaying because they are trying to play a card themselves, while also signaling for 1 blind play from the positional slot.

I believe we had this defined previously, was this removed?

**Comment by Zamiell** [comment]
wrong repo

**Comment by Zamiell** [comment]
> I believe we should show the Single Positional Misplay before the Double Positional Misplay.

they already are, right? i dont understand this issue

**Comment by iamwhoiamhahaha** [comment]
> thats the way it already is, right?

Someone would take it as a double and the team receives two strikes. That's why we need a clarification for that

**Comment by Zamiell** [comment]
i dont understand what clarification is needed

**Comment by iamwhoiamhahaha** [comment]
For example, in a 3-player *No Variant* game:
- All cards are played except for r5, g5, and b5.
- Bob has a g5 on slot 2 and a b5 on slot 3. (both are unknown)
- 3 cards left in the deck.
- 0 clues.

If Alice discards her *Chop* (as usual) and doesn't draw a r5; and Bob would probably discard in his turn and he might draw a r5, which is awful. Alice decides to do a *Positional Move* and makes Bob play one of his 5s.

Since Alice might have a r5 on slot 2 and she's not allowed to perform a *Positional Discard*. Thus, she misplays her slot 2 as a *Positional Misplay*. Bob blind-plays g5 from slot 2.

Now, it's Cathy's turn.

**Question: Does Cathy have a red 5 on slot 2?**

**Comment by Zamiell** [comment]
cathy does, yes

**Comment by Zamiell** [comment]
it will almost never be the case that alice *needs* to do a positional discard in order to win the game in this specific scenario.

if it is, then it is a hard variant, and these rules probably don't apply anyway, so the doc does not need to be updated, and certainly not at level 7

**Comment by iamwhoiamhahaha** [comment]
fair enough

**Comment by iamwhoiamhahaha** [comment]
and i just realized the team still lost if bob drew the red 5

**Comment by iamwhoiamhahaha** [comment]
Here's a good example what kakashi is proposing:
https://hanab.live/replay/726299#29

It's newduke's turn, he didn't have a clue to give and he wanted to get the brown 5. He couldn't discard slot 3 for it could be a red 5. Thus, he misplayed slot 3 as a *Positional Misplay (Single)* for ReaverSe's brown 5 on slot 3.

From arv's perspective:
- If newduke saw a red 5, then arv should know that his red 5 must be on slot 3 and cannot be on other slots because newduke could just perform a *Positional Discard* for the brown 5.
- If newduke didn't see a red 5, then arv should know that newduke was trying to play the missing red 5 and marks nothing on his hand.

However, arv doesn't know if newduke saw a red 5 or not, he is not allowed to blind-play the missing red 5 from slot 3. The only information he can deduce from the bomb is he doesn't have a red 5 on slot 1, 2 and 4 (could be on slot 3).

**Comment by Dr-Kakashi** [comment]
Looks like Jeff is addressing it properly, but yes there are situations where a player will positional for a card through a misplay. At that point in the game, that player knows they will not misplay a critical card as any important card will immediately play. 

In doing this, it only gets 1 card for the team. It is globally known that the player who initiated the positional misplay was trying to play a card themselves. 

The doc as it is currently written only addresses the unnecessary situation where a positional misplay calls for 2 cards.

**Comment by argothiel** [comment]
Alice could also have some information from the context on her chop or finesse. Thus, she might have some reasons to try a specific slot for her red 5 and I wouldn't read into this as an indication to blind-play as Bob.

**Comment by Zamiell** [comment]
> Alice could also have some information from the context on her chop or finesse. Thus, she might have some reasons to try a specific slot for her red 5 and I wouldn't read into this as an indication to blind-play as Bob.

to be clear the doc doesn't share this opinion (or take an opinion at all)
