### ISSUE TITLE
split up level 1

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#871]
the beginners guide is pretty long, do we want to move finesses and prompts to a new level 2, and then shift all the other levels upwards?

**Comment by Zamiell** [comment]
@vEnhance i think we discussed this at some point and i forgot what we decided

**Comment by vEnhance** [comment]
I remember voting against it since I think prompts/finesses are pretty fundamental and follow naturally from the notion that "play clues promise a card is playable". 

(Also, when we last talked about this, I think it was just finesses. How would you play without prompts? If I give a clue that touches r1 and r3 on the first turn, and I can't prompt the r3, do I just have to tempo clue it?)

**Comment by argothiel** [comment]
> How would you play without prompts? If I give a clue that touches r1 and r3 on the first turn, and I can't prompt the r3, do I just have to tempo clue it?)

From the newbie perspective: either that or you wait until you see both the red 4s and a 5 in other hands.
