### ISSUE TITLE
Clarification: Low Score Phase

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#879]
![2022-02-12_03-28-52 (single 5 bluff over 5 double pull](https://user-images.githubusercontent.com/48993588/153709839-1156a0f4-185e-488b-be89-c99ae5573140.png)
5 Single Bluff vs 5 double pull

I've been finding the low score phase to cause more bombs than I would like. I think it's time to look at the low score phase and:
1) Clarify some things 

- "However, all number 5 clues in the Low Score Phase are never to be interpreted as a direct Play Clue." This may be too restrictive.

2) Consider removing low score phase entirely.
3) Consider Reducing low score phase from 10 to some lower number. 

I've found that during low score phase, 5's get really close to being playable (1 away) or being actually playable.

This causes conflicts with our existing conventions. 

For example: in the image above the interpretation of our current conventions is that it's a 5 double pull, instead of a single bluff.

**Comment by Lel0uch-H** [comment]
https://hanabi.github.io/docs/level-20/#interaction-with-5-rank-clues

> However, for level 20 players, Play Clues like this are turned off. In other words, every number 5 clue that focuses a 5 that is exactly one-away-from-chop would always be a 5's Chop Move. This is referred to as the Chop Move Ignition Interaction.
The Chop Move Ignition Interaction can be tricky for players, since Chop Move Ignitions can look like normal Finesses. Players need to remember that the blind-play relates to the card being Chop Moved, not the 5 directly.

It's not causing any bombs if we remember the above part and is totally logically consistent. I don't find either configuration any more or less confusing, we just need to remember which one is the conventional interpretation. Following from that, Dani should eject and not play finesse.

**Comment by iamwhoiamhahaha** [comment]
agreed with lel

**Comment by mmelwen** [comment]
agree with Jeff who agrees with Lel

**Comment by Dr-Kakashi** [comment]
What do you guys think about having low score phase turn off once a 5 is 1 away from being playable?

**Comment by Lel0uch-H** [comment]
@Dr-Kakashi 
We used to have this convention in White specifically called "White compromise" and we decided to delete it. I don't think the complexity of entertaining 1 away 5s as finesses is worth much compared to the current config.

**Comment by Zamiell** [comment]
the reason we deleted it is because it was an exception for a specific variant, which was hard to remember and increased complexity.

if you were to configure the conventions such that you could give play clues to 5's universally, i dont think that would have quite the same character of white compromise.

with that said, my intuition is that such a convention would still be harder to play with.
the reason that we settled on the current configuration is that there is little thinking involved, its just a flowchart.
e.g.:

1) is it low score phase? yes
2) is a number 5 clue? yes
3) then it is impossible to be a play clue, it must be something else

as opposed to:

1) is it low score phase? yes
2) is a number 5 clue? yes
3) could the 5 possibly be playable? no
4) then it must be something else

now there are 4 steps instead of 3, which is an extra vector for mistakes/misplays

**Comment by Zamiell** [comment]
> "However, all number 5 clues in the Low Score Phase are never to be interpreted as a direct Play Clue." This may be too restrictive.

i'm confused, because this seems indistinguishable from deleting the low score phase

**Comment by Zamiell** [comment]
> Consider removing low score phase entirely.

on optimality:

the group is deliberately trading away play clues on 5s (tempo + clues back) for other benefits.
i think if you poll most players, they will think that the trade off is worth it, because
1) they voted on it to be passed as an official convention, and
2) they subsequently have played with it and noticed the value in real games

on complexity:

personally, i dislike having to keep track of whether or not it is the low score phase, and find it annoying.
with that said, low score phase has been demonstrated to bring a substantial amount of value, which may make the annoying complexity cost worth it.
my UI changes can help this a little bit (e.g. making the score color blue instead of the normal color).

overall, i think you would find that most players would be opposed to deleting low score phase

**Comment by Zamiell** [comment]
> I've found that during low score phase, 5's get really close to being playable (1 away) or being actually playable.

i would characterize this as happening <50% of the time

**Comment by Zamiell** [comment]
closing since kakashi isn't responding
