### ISSUE TITLE
Add a section to the doc called "Discretionary Conventions"

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#883]
We can add some of the deleted conventions to this section. Many older players like to play with some conventions which were deleted for the reason of being "too error-prone", and not being on the same page about them before the game definitely hurts. Additionally, some of the current "advanced strategies" can be moved to this section and the "advanced strategies" can be renamed as level 24. 

Some candidates for this section (not exhaustive):
 - OOP bluffs
 - Safety charm
 - Redundant save CM
 - (Distributed) Dump Truck
 - SFI
 - Rank choice finesse/bluff

**Comment by Zamiell** [comment]
absolutely not
there is only one convention set, and if a convention is voted to not be used then it will be removed from the doc entirely.

**Comment by iamwhoiamhahaha** [comment]
We already have at least "24" convention sets. (Players used to determine the level before the game.) What's bothering you by adding them?

Or maybe we could just add a section called ***Extremely Hard Variant Conventions*** as @TheDaniMan proposed in this [issue](https://github.com/hanabi/hanabi.github.io/issues/880#issuecomment-1039506688). I believe we need some deleted conventions to score hunt in these variants.

**Comment by Zamiell** [comment]
see convention-goals.md

**Comment by Lel0uch-H** [comment]
It is a lazy excuse that the goal of the doc is to optimize win-rate for the classic variants, because if that were true we would not have many _many_ conventions which are not useful for that at all (and in some cases even counter-productive).

Let's not kid ourselves and recognize that a vast majority of H-group players like to score-hunt hard variants.

**Comment by Zamiell** [comment]
then lets open an issue for hard-variant conventions instead of an issue for optional conventions

**Comment by mmelwen** [comment]
Let's add two sections with 24 error prone conventions and 
25 extremely hard variant conventions 1,25 efficiency with 1,76 are not even close to been the same difficulty, agree with Dani proposed on the other issue.
I would propose to include in level 24 

1. OOP bluffs
2. Safety charm
3. Redundant save CM
4. SFI
5. Rank choice finesse/bluff

and in the very hard variants the cms proposed https://github.com/hanabi/hanabi.github.io/issues/880

I haven't use or seen the dump truck ever but I am not opposed to have it in any of those two categories

**Comment by TheDaniMan** [comment]
Most of these conventions are gone because it's much more common to make a mistake than to use them, even for experienced players, and even then they're quite underwhelming. In some rare cases when I'm really sure that my teammates cannot be making a mistake I'll entertain something illegal, but it would be difficult to play with these optional conventions if I even admit the possibility that one of the very experienced players in the lobby is slightly sleepy, and it would be an absolute nightmare around newer players.
Regarding the very hard variant suggestion I made elsewhere, it's because those variants have such a frustratingly low winrate that it's more likely to lose because the current conventions are not powerful enough than it is that a group of players seriously attempting it is going to make the sorts of minor 'mistakes' that can be assigned some extra convention space.
If the conventions are geared towards playing "classic variants" in a fun way to the point that they make playing very hard variants too difficult and not fun, I don't see how adding some modifications that apply only in variants that are not within the scope of the goal would go against the goal.
To me, the difference between optional conventions and very hard variant conventions is that instead of having to learn them and remember which conventions are on and which are off depending on the other players in the game, I can treat them just like any other variant-specific conventions and look at the current variant, open the corresponding page of the doc before the start of the game and not worry about the conventions otherwise.

**Comment by pianoblook** [comment]
definitely in favor, whether it's 'optional' or 'hvr'.

My preferred resolution would be to increase HVR to only being >1.25, and making specific HVR conventions

**Comment by EhDrone** [comment]
I am not necessarily in favor. These conventions are **rarely** needed even in hard variants (probably <1.56). Score Hunting is a sub-goal that people enjoy (me included) because it defines 'progress' on the profile page of perfect scores - however getting a perfect score and aiming for maximum average score are distinctly different, and conventions aiming for one are not necessarily beneficial to the other.

If there were a proposal that was very specific and defined (Like "These conventions are only useable in Double Darks, or >1.57 efficiency games, and require that all other conventions plus advanced section are being used" - probably similar to what DaniMan has in the other post - although I think that one might be too broad) I could see being worth adding a section to the H-Group doc. I'll add though that even then, a massive amount of luck is required to not get bottom decked - so how much benefit would these even have beyond just looking for a lucky deal? Otherwise, since most of the argument here is about Score-Hunting (it seems to me at least) why not just create a separate "Score Hunting" convention document and put whatever you want? Then when you play with people and you specifically want to score hunt you can say "We are using the Score Hunting conventions, that cool with you?"

**Comment by mangopie1** [comment]
How about a section called. "Deleted Convention" hence anyone can refer to it if they wish to use it 😆😆😆

We deleted convention due to it being error prone or net negative. Therefore I don't agree with reviving a convention just because we need it for super hard variant.

**Comment by Lel0uch-H** [comment]
@mangopie1 We already have a [documentation of the deleted conventions](https://github.com/hanabi/hanabi.github.io/blob/main/misc/deleted-conventions.md).

**Comment by Romain672** [comment]
(Some people strongly disagree with #785 , but that's the point of it too. Depending of the variant, you could move a 'cursor' from 1 to 200 which would tell you until which part of conventions you wanna play.

And so it give place to put on some really advanced conventions which are a lot prone of mistakes.
And you can totally strongly discourage people from reading conventions above 100.)

**Comment by iamwhoiamhahaha** [comment]
> why not just create a separate "Score Hunting" convention document and put whatever you want

I agree the goal of H-group conventions are for maximum average scores rather than perfect scores and it was the reason why I wrote [*Score Hunting Guide (2-Player)*](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Score_Hunting_Guide.md). We could create a new document for score hunting in multi-player but I'm afraid no one can maintain/keep updating it. Why not just adding a new section in the H-group convention document for score hunting so that we don't have to create a new one for that?

> Some people strongly disagree with https://github.com/hanabi/hanabi.github.io/issues/785 , but that's the point of it too

That's unrelated. The point is Zamiel doesn't like a convention set with an optional section.

**Comment by Lel0uch-H** [comment]
It is inevitable that the doc will have "optional conventions" and/or "extension conventions" eventually. We have reached a point where virtually anything new has a direct conflict with any older convention. Also, conventions like Dawn would be a good candidate for such a section given how not everyone might want to play with them.
