### ISSUE TITLE
Rename '5 Number Discharge' into '5 Pull Number Discharge'

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#888]
For clarity.
From the name, i though it was a reclue of a 5, not a 5 Pull.

**Comment by iamwhoiamhahaha** [comment]
https://github.com/hanabi/hanabi.github.io/issues/92#issuecomment-555815639

**Comment by pianoblook** [comment]
That is what it's doing though, right Jeff? Bob looks at the identity of the card being Pulled and needs to decide how to respond.

**Comment by iamwhoiamhahaha** [comment]
It was called *5 Pull Ejection (Discharge)* when the convention was proposed. Libster thought it shouldn't be called "5 pull something" because the move doesn't actually pull a card to the right of the 5. I'm fine with both name honestly. I was just telling the reason why it was changed to *5 Number Discharge* from *5 Pull (Number) Discharge*.

**Comment by Zamiell** [comment]
i dont like making convention names longer, because it makes them more difficult to say and minimizes their ability to act as concept handles
