### ISSUE TITLE
Fake 5-pull on non-critical pink

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#890]
Hi,
I would like to talk about clueing a number 5 early on any pink or light pink card.

There is 10 possibilities:

If the 5 clue is on Donald:
 - if it's i1, Bob eject (turnabout ejection)
 - if it's i2 or i3, or i4, Bob plays slot 4 (not you have access to slot 3 too if it's turn 1)
 - if it's i5, it's a 5-pull and others players will usually only play their finesse position

If the clue is on Bob, Bob will assume a 5-pull and will usually play his pulled card, then:
 - if it's i1, Cathy play slot 1
 - if it's i2, Cathy play slot 2
 - if it's i3, Cathy play slot 3
 - if it's i4, Cathy play slot 4
 - if it's i5, nothing else happen

I think it start to really be chaostic if you respect actual conventions :(

**Comment by ZakisanGithub** [comment]
I like the idea of ascribing different meaning to cluing 5 focussing pink 234 to someone other than Bob since in my experience it is rarely used to Bubblegum outside of 6 player games. 

However, I'm not a fan of the suggested convention of Cathy blind playing to ilucidate Bob about what pink card he holds. The issue is that any clue given by Bob might have been trying to trigger that blind play as well (or Bob just clues the card directly), and thus adoption of this convention would severly limit the ability of freshly 5-pulled to act. Beacuse it is such a specific circumstance, I would expect adoption of this convention to be quite error-prone, especially since this modification of allowed behavior only applies in variants with a pink/omni suit.

**Comment by Zamiell** [comment]
the pink conventions are already long enough, we don't really gain much value from making things more complicated
