### ISSUE TITLE
Occupied Stomp Discharge & Charm

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [hanabi/hanabi.github.io#945]
### Origin
- Came up with this convention from this game: https://hanab.live/replay/794484#6
- From my perspective, it is weird that Utopia refused to play their card (potentially a red 1) and stole my chance to bluff the red 1 from arv. We were playing a level 18 game and I understood that was just a pure "mistake" by Utopia.
- However, as a player who loves reading context aggressively, I was trying to imagine in a situation where I'm playing a max level game with some experts, would they still give this clue? If not, then what is the purpose of this clue if they intend to do it? If my teammate is trying to get my card, then which slot am I supposed to play?
- I agree this convention is way too complicated and I have a feeling that it won't get approved based on my experience. However, I believe this convention might be common and helpful and it doesn't cause a bomb if Bob misses it.
- Thread in #in-depth-discussion channel on discord: https://discord.com/channels/140016142600241152/776176933120507964/989071732021297213

### Occupied Stomp Discharge & Charm
- If an *Occupied* player gives a direct *Play Clue* on a playable card where their next player who is currently not *Occupied* can literally give the same clue, and their next player can see that there's no other valuable clue to give which is related to the *Play Clue* (or defined as the next player are in a *Call to Discard* situation). In this situation, the player must be trying to communicate something extra.
- If the *Play Clue* touches a 1, and only one card is touched by that clue, the next player is supposed to blind-play their *Third Finesse Position* as an *Occupied Stomp Discharge*.
- If the *Play Clue* touches one or more cards and the focus of the clue is a playable card and it is not a 1, the next player is supposed to blind-play their *Fourth Finesse Position* as an *Occupied Stomp Charm*.

### Occupied Stomp Discharge & Charm Finesse Position Exception
- Normally, you are only allowed to perform an *Occupied Stomp Discharge & Charm* if the next player is not *Occupied*.
- However, what if the player gives a direct *Play Clue* on a playable card which is on the *Finesse Position* of the player (Cathy) after the next player who is currently *Occupied*? In this situation, the player must be trying to communicate something extra.
- Similar to an *Occupied Stomp Discharge & Charm*, the next player is supposed to blind-play their *Third Finesse Position* as a *Discharge* or *Fourth Finesse Position* as a *Charm* depending on the card which is focused.

### Examples
- (none)

**Comment by Romain672** [comment]
I've got the feeling for that move to be clear, it can only be the early game.
And so stealing a clue which touch a single card in slot 1 could be enough as a condition.

**Comment by Dr-Kakashi** [comment]
I think there could be some problems with this passing. 

Assumption: Alice is the "occupied player" who has a play and steals Bob's clue

1. What if Alice has a blind play? If Alice defers, then it looks like the initial clue on Alice was ambiguous and this causes Bob to bomb the first finesse.

Solution: Alice should only do this convention if she doesn't have a blind play. 

This brings problem #2

2. What about situations where Alice chooses to not play her card because she is "hesitating?"

Solution: Unsure how to rectify it, it would just cause bombs. 

Unless these 2 problems are rectified I don't see how this clue can be "clear." If anything, it makes the situation very complex for marginal gain. 

Arguably, it's probably worse overall for Alice to steal Bob's clue as Bob himself can most likely bluff/finesse/eject/discharge out the card from Cathy's hand. If Bob is able to do that, then it's not really a big deal to just directly clue Bob's 3rd slot.

**Comment by Dr-Kakashi** [comment]
I've just checked your game and noticed that utopia clued red 1 because utopia wanted to 4 charm your r2 which is completely blocked. So actually that brings up a 3rd problem.

3. What if Alice wanted to set the game up so that it's easier to get cards out of Bob's hand and/or set up the game for more efficient clues?

**Comment by iamwhoiamhahaha** [comment]
> What about situations where Alice chooses to not play her card because she is "hesitating?"

Yeah good point, that might be a problem. So maybe Alice can only do this if they know Bob won't hesitate.

> I've just checked your game and noticed that shouldn't utopia think they have b2 since you did a selfish play clue?

I know you're a good player who can read through context and understand why it can't be a b2 from my perspective.

> What if Alice wanted to set the game up so that it's easier to get cards out of anyone's hand and/or set up the game for more efficient clues?

Alice could still do it after Bob does a *Bluff* on Cathy.

> if you include Romain's point, conflict with UTD and UDD

It doesn't conflict with *UTD* and *UDD*. It only conflicts with *UTC* which is rarely seen.

**Comment by Dr-Kakashi** [comment]
> > What about situations where Alice chooses to not play her card because she is "hesitating?"
> 
> Yeah good point, that might be a problem. So maybe Alice can only do this if they know Bob won't hesitate.
> 
I'm not sure what you're talking about? Alice is the one hesitating, not bob? Also, the team won't know Alice is hesitating as discarding is really the only clear indication a hesitation has occurred. 

> > I've just checked your game and noticed that shouldn't utopia think they have b2 since you did a selfish play clue?
> 
> I know you're a good player who can read through context and understand why it can't be a b2 from my perspective.
> 
But, that's the point? It isn't about your perspective, as you are Bob. It's about Alice's perspective. Utopia really can think they have B2. 

> > What if Alice wanted to set the game up so that it's easier to get cards out of anyone's hand and/or set up the game for more efficient clues?
> 
> Alice could still do it after Bob does a _Bluff_ on Cathy.
> 
You're proving my point? Alice should just play and let Bob do the bluff on Cathy. The team would be worse off doing your proposed convention per my explanation above. 

> > if you include Romain's point, conflict with UTD and UDD
> 
> It doesn't conflict with _UTD_ and _UDD_. It only conflicts with _UTC_ which is rarely seen.

It certainly does conflict, as your proposal is on a "playable card." 
It seems the only way this proposal would work is if the clue receiver knows it isn't trash, which means the single touched card is a 1, as there is no trash at that point in that game.

**Comment by iamwhoiamhahaha** [comment]
> I'm not sure what you're talking about? Alice is the one hesitating, not bob? Also, the team won't know Alice is hesitating as discarding is really the only clear indication a hesitation has occurred.

If Bob gave a clue to Alice last turn and made her *Occupied* and Cathy gave a *Save Clue* to someone in their turn.

> It's about Alice's perspective. Utopia really can think they have B2.

From Alice's perspective looks at Bob's perspective. If that's a blue 2, Jeff would just play their blue 1 for arv to give this clue. This is like a level 12 read.

> The team would be worse off doing your proposed convention per my explanation above. Also, the team is losing Tempo on the card Alice is supposed to be playing.

You can't use the example from my replay since Jeff's *Third Finesse Position* was not playable. But imagine Jeff's red 2 is a brown 1 and it's blocking (in a brown variant), you would agree my point.

> It certainly does conflict, as your proposal is on a "playable card."

Please re-read the definition, it does not conflict with either a *UTD* or a *UDD*.

**Comment by iamwhoiamhahaha** [comment]
>> If Bob gave a clue to Alice last turn and made her Occupied and Cathy gave a Save Clue to someone in their turn.
>
> My point is about Alice being in a hesitation situation. I don't see why Alice making sure Bob isn't in a hesitation situation applies here?

Because Bob gave the *Play Clue* to Alice... Which card is Bob going to hesitate? A Magic Bluff?

> > From Alice's perspective looks at Bob's perspective. If that's a blue 2, Jeff would just play their blue 1 for arv to give this clue. This is like a level 12 read.
> 
> Are you taking Utopia's experience into account here? They have 364 games. If I was Utopia, I most certainly would consider having B2.

Please see ***Origin***. I'm not talking about a real game. This convention is developed hypothetically in a max level game. I don't see the reason why it can be a blue 2. Come on man, I know you can read through context, which is only level 11... If that's blue 2, I would just play my blue 1 for arv to give this clue 😫

> > Please re-read the definition, it does not conflict with either a UTD or a UDD.
> 
> You said "playable" in your first point. Your second point says it touches a 1. It's confusing of your intention the way it's written, which is why I'm pointing it out for you. The way you have the proposal written it is most certainly conflicting with UTD and UDD. Romaine even pointed that out for you.

Omg. Somebody help me please. Kakashi is being ridiculous. IT DOES NOT CONFLICT. @Romain672 figured it out immediately after they got the answer:

> Romain672 — Yesterday at 9:24 AM
> Oh so that work only with 1s since it can't be trash.
> Ok that's what i was missing, ty.

How can a playable 1 be trash???

**Comment by iamwhoiamhahaha** [comment]
> > You can't use the example from my replay since Jeff's Third Finesse Position was not playable. But imagine Jeff's red 2 is a brown 1 and it's blocking (in a brown variant), you would agree my point.
>
> No, I would not. Your read was bad here. I've explained in detail why over multiple points and perspectives.

It depends. You love doing something nonsense. I know you. But anyway, as my response to Kyle:

> Kyle — Yesterday at 7:14 AM
> From Jeff's POV, there could be a number of reasons Utopia is stealing this clue (most involve Jeff discarding)
> IAMJEFF — Yesterday at 9:15 AM
> I agreed in this example, i.e. Occupied Stomp Discharge & Charm Finesse Position Exception, Utopia might have some reasons to steal the clue, and this convention is prone to errors. However, Occupied Stomp Discharge & Charm should be a thing imo, like piano has mentioned, if the next play is called to discard, that clue means something.

I agreed *Occupied Stomp Discharge & Charm Finesse Position Exception* is likely to be confusing and prone to errors. Can we first talk about *Occupied Stomp Discharge & Charm* without *Finesse Position Exception*?

**Comment by Dr-Kakashi** [comment]
Jeff I don't know why you immediately jump to me not fully understanding the situation and your intentions. Then put me in a place where I would be no different than someone who hasn't read the document. I'm annoyed and frustrated that you have done this to me on multiple occasions.

I gave you multiple in-depth scenarios from multiple POV's. The whole proposal is quite frankly confusing and highly prone to errors. It honestly does not matter nor change the scenario if you "successfully" played a card. I completely understand you're asking for a max-level situation and your intentions. You still have not addressed my points, but instead changed the scenario to fit your narrative. 

I'll try again to point out how you wrote the proposal incorrectly and explain in detail why:

Your first bullet point:
If an Occupied player gives a direct Play Clue **on a playable card** 

Your second bullet point:
**If the Play Clue touches a 1, and only one card is touched by that clue,**

Again, the way it is written is confusing because the first bullet point conflicts with UTD and UDD. It isn't until the reader gets to the 2nd bullet point that they have to retroactively figure out your true meaning so that it does not conflict with UTD and UDD. 

This proposal hinges on the context of whether or not the situation is suboptimal. Part of the definition of suboptimality is that it must be absolutely **clear** it is a suboptimal clue. If I'm giving you a multitude of scenarios where it isn't clear and you agree with me on at least one, then you're already saying the proposal is bad.
