### ISSUE TITLE
[Omni Proposal] Add Mud Clues + Free Choice Finesse to Omni

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#972]
I was surprised to learn yesterday that _Mud Clues_ aren't currently 'on' in Omni. I reviewed the Omni convention page and saw it doesn't include *ANY* conventions from other Rainbow-type variants.

If we're comfortable relying on _Rank Choice_ conventions like _Pink Tempo Clues_ in Omni, I see no reason not to take advantage of certain  _Color Choice_ conventions as well.

I propose we include at least the following two conventions:

- [Mud Clues](https://hanabi.github.io/docs/variant-specific/muddy-rainbow-cocoa-rainbow/#mud-clues)
- [Free Choice Finesse](https://hanabi.github.io/docs/variant-specific/rainbow/#the-free-choice-finesse)

There might be another convention or two that I'm not recalling that would also make sense for the same reason.

Here's the situation we had the other day, btw - SS is a hypo where _Yellow_ would be a free choice tempo clue, whereas a rank clue would have been blocked.

In game eliclax felt forced to discard instead: https://hanab.live/replay/823409#9

<img width="1300" alt="Screen Shot 2022-08-11 at 1 43 17 PM" src="https://user-images.githubusercontent.com/32303453/184208204-d474d675-76fd-4e77-88c0-01b2bb80935b.png">

**Comment by Zamiell** [comment]
i think the reason is that the conventions are currently structured this way is because its mostly not a problem to use the pink tools to "get" the omni card that you want.

as you say, the advantage of adding mud tools is that it will increase the flexibility to get omni cards in the case where the pink tools are blocked.

but on the other hand, allowing both mud tools and pink tools increases complexity, increases the total space for players to make mistakes, and makes it harder to remember all of the conventions that are currently "turned on" for the variant.

**Comment by iamwhoiamhahaha** [comment]
> it is not a problem to use the pink tools to "get" the omni card that you want

The reason why piano brought up this issue is because they played omni & light pink. Clearly, piano has a blocking light pink card in hand (I didn't check the replay). But I agree with Zamiel we used to deal with this problem with pink techs.

>I propose we include at least the following two conventions:
[Mud Clues](https://hanabi.github.io/docs/variant-specific/muddy-rainbow-cocoa-rainbow/#mud-clues)
[Free Choice Finesse](https://hanabi.github.io/docs/variant-specific/rainbow/#the-free-choice-finesse)

I vote for yes.
