### ISSUE TITLE
Pace 0 stall

### ISSUE THREAD

**Issue by DarthGandalf** [hanabi/hanabi.github.io#987]
https://hanabi.github.io/docs/level-8#allowable-stall-clues-stall-table doesn't have anything about pace 0, so technically it's not even a stalling situation now.

Should it be added to level 3 severity?

**Comment by Zamiell** [comment]
probably not because its super obvious

**Comment by DarthGandalf** [comment]
I'm glad that it's obvious for you :) But if to count like that, we can declare many of these conventions obvious, and therefore remove them.

**Comment by kunyavskiy** [comment]
At least it is not obvious which severity level it is.

**Comment by Zamiell** [comment]
> so technically it's not even a stalling situation now

it is defined as a stalling situation in level 7 (i.e. the previous level).

introducing a chart that covers stalling situations in level 8 doesn't change any of the information introduced in level 7.

> Should it be added to level 3 severity?

well i think that it would make more sense to add it as a new column with severity 5, since if you discard, you 100% lose the game.
but again, i feel like this is kind of obvious.
something has gone horribly wrong with our system if a person is reading a page called "level 8" and does not already understand that discarding at pace 0 loses the game.

**Comment by DarthGandalf** [comment]
> it is defined as a stalling situation in level 7 (i.e. the previous level).

But the table skips it, and no severity is assigned to it.

It's not the first time next level changes meaning of moves from previous level. E.g. bluff vs layered finesse (change at level 10), or simple play clue vs reverse finesse (change at level 2)

> something has gone horribly wrong with our system if a person is reading a page called "level 8" and does not already understand that discarding at pace 0 loses the game.

It's not about discarding. But about interpretation of which exact stalls are to be understood as play clues, and which stalls are just stalls.

**Comment by Zamiell** [comment]
ok i added a severity 5 to the table for your review

**Comment by vEnhance** [comment]
What's the difference between "❌" and "n/a (nonsense)"?

**Comment by Zamiell** [comment]
❌ means it isn't allowed. if it were allowed, a player might want to do it.
nonsense means that you wouldn't make sense to ever do it for any reason.

**Comment by argothiel** [comment]
I don't think it's "pace 0 stall". I think it's more like an "End Game stall", where in the End Game you are allowed to stall anytime you see a better chance to win. So that would obviously include pace 0, often pace 1 etc. And by the guide, you are even allowed to clue trash, so End Game stalls are more contextual: https://hanabi.github.io/docs/extras/pushes-pulls/#the-trash-pull

**Comment by GuolinM** [comment]
I'm failing to see why this isn't just rolled in with Severity 4 (8 clues). In both cases, discard is absolutely non-negotiable, because of either game mechanics (8 clues) or instant loss (0 pace)

Stuff like LHS might still be relevant unless we allow LHS as endgame stalls (which btw I don't see a clear answer for what's allowed vs. what should be considered as play/save clues instead).

**Comment by DarthGandalf** [comment]
The reason I thought severity would be closer to 3 is because sometimes it's obvious that it's impossible to get the full score, and discarding at least would make it possible to get e.g. 24 or 23 instead of 0

**Comment by Zamiell** [comment]
ok i updated the page from "Pace 0" to "End-Game", so i think the new version makes more sense
