### ISSUE TITLE
Rename Chop Transfer to Transfer Chop Move and Extend It to Non-Emergency Fix Clues

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [hanabi/hanabi.github.io#992]
### Origins & Reasons
- According to the discussion on discord, I just realized that the *Chop Transfer* doesn't include a *Fix Clue* on a duped *Clued* card.
<https://discord.com/channels/140016142600241152/1016060964619157557/1016174606391967894>
- In Score Hunting Guide (2-player), I've renamed it as a [*Transfer Chop Move*](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Chop_Move_Guide.md#transfer-chop-move) since *Chop Transfer* is basically a type of *Chop Moves*. Then, why not call it a *Chop Move*?
- For the reason to extend *Chop Transfer* to non-emergency *Fix Clues*. Interestingly, it was just a pure mistake. In fact, I thought the move applies to a non-emergency *Fix Clue* in the first place, and which is the reason I wrote the following statement to my 2p document. Just realized that it doesn't apply to a *Fix Clue* today.
> If the teammate has an unknown trash which has been clued earlier, the player is allowed to give a Fix Clue on the trash and it signals a Transfer Chop Move.
Note that the players can also perform this move by touching a Chop Moved card.
- The h-group document states that undoing a *Chop Moved* is unnecessary and it signals a *Chop Move*, which is reasonable. But why is it not also unnecessary to a *Fix Clue* in a non-emergency situation? Sometimes, a *Fix Clue* is necessary which prevents a bomb. However in most circumstances, a *Fix Clue* is unnecessary and it's being weird to do so.
- For example, in a muddy rainbow game:
  - Red 1 is played on the stack.
  - Bob's hand: `x r3 r1 m5`.
  - It is unavoidable to save the muddy rainbow 5 with a red clue which also touches a trash (duped) red 1.
  - Alice gives a red clue to Bob.
- Question: Is it necessary to fix the red 1 later of the game in the example above?
  - I believe the answer is no since Bob will never try to play (bomb) it without a *Prompt*.
  - Unless the red 3 in slot 2 has been played somehow and the team knows that Bob is gonna bomb it if he sees a red 5.
- In conclusion, if a non-emergency *Fix Clue* is given on a duped trash *Clued* card, it should signal a *Chop Move*.
- It simply looks like "*Chop* is being **transferred** to the fixed duped trash", i.e., the clue receiver is supposed to discard the trash rather than the *Chop* card (rightmost unclued card). I don't see the problem calling it a *Chop Transfer* or a *Transfer Chop Move*.

### Transfer Chop Move (Changed from [Chop Transfer](https://hanabi.github.io/docs/extras/chop-moves/#the-chop-transfer))
- First, see the section on [blind playing *Chop Moved cards](https://hanabi.github.io/docs/level-6#blind-playing-chop-moved-cards).
- Sometimes, duplicated cards are accidentally *Chop Moved* or *Clued* through a mistake or through a complicated situation. When this happens, it is pointless to use a clue to "undo" the *Chop Move* or "fix" the duped *Clued* card if the player is not going to play it - the team can just continue to allow the player to discard normally. 
- Subsequently, if someone does use a clue to undo the *Chop Move* or fix the *Clued* card, there must be a good reason. This means that the card they were about to discard is important, so the player should discard the now-known useless card and then permanently *Chop Move* their new chop.
- Note that sometimes a *Fix Clue* is necessary and it doesn't signal a *Chop Move*.

**Comment by EhDrone** [comment]
I am not convinced taking away fix clues at any time is always a good outcome. Especially as we (I would argue) move more and more towards a state of play where discarding ANY good card is desired to be avoided to eliminate any risk of bottom decking, it can be very valuable as a player concerned about their OWN chop to be able to 'stall' in away for a turn by fixing someone else's hand that needs fixing. 

I would not like to be in a situation where I am concerned about my own chop being a good card when Bob has trash on chop, and so I fix Cathy's bad touched red 1 instead of discarding myself. Do you think that the restriction of fixing cards to always cause a chop move if its 'early' will be a net benefit as opposed to being able to delay discarding yourself to fix a hand?

We have so many ways to chop move that I think expanding fix clues to chop move will be a narrow field of use when compared to alternatives, and therefore am leaning towards being able to protect my own chop by fixing as opposed to now being forced to discard if the player has trash on chop that needs to be fixed - but I am open to the idea if anyone enough people think it would be a net benefit.

**Comment by iamwhoiamhahaha** [comment]
I'm afraid of discarding my *Chop*. Hey! Bob has an unknown playable card (on the left) which has been clued earlier. He has trash on *Chop* and I know it's a 0-for-1 clue, but why not giving a *Tempo Clue* in this situation to protect my *Chop*?
Similarly, Bob has a trash which has been *Chop Moved* earlier. In order to prevent a future potentially bomb (people usually bomb a chop moved card in a max level game from my experience) and I also wanna undo the *Chop Move* to protect my own *Chop*. Does it sound good?

Fixing a duped card in a non-emergency situation doesn't meet *Minimum Clue Value Principle*. It prevents a potential bomb, but usually it prevents nothing (like my example above) and it's a waste of clue (which is 0-for1).

**Comment by EhDrone** [comment]
A distinct difference is that touched cards can be tempo with high frequency by cluing the following card to get it for free. Because of all the ways to get touched cards to play for free that don't require tempo clues (including good touch itself), tempo clues don't benefit the game because the card will play on its own anyway. Bad touched cards however can bomb based on non-global info at an any time that you can't predict, and so fix clues are not valuable in MVCP, but instead a weight of: Bomb = +1 bomb and +0 clues = 0 clues / 1 bomb whereas a Fix = -1 clue and + 1 clue discard = 0 clues / 0 bombs. 

The two aren't exact corollaries so I don't personally buy the value of a non-value of a tempo clue being translated to the non-value of a fix clue

**Comment by Zamiell** [comment]
> In Score Hunting Guide (2-player), I've renamed it as a [Transfer Chop Move](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Chop_Move_Guide.md#transfer-chop-move) since Chop Transfer is basically a type of Chop Moves. Then, why not call it a Chop Move?

I'm fine with a simple renaming of *Chop Transfer* --> *Transfer Chop Move*

> But why is it not also unnecessary to a Fix Clue in a non-emergency situation

i'll copy paste from the "/undefined" bot, since this is such a common question:

**Why isn't [situation X] defined in the conventions document?**

Not everything has to have a meaning. We intentionally want to have some situations be undefined so that we have some wiggle room to handle a wide variety of game states: https://github.com/hanabi/hanabi.github.io/blob/main/misc/convention-goals.md

**Comment by argothiel** [comment]
Although early fixing has always looked weird to me, even in your example Bob might play his red 1 unprompted, from the context. Assuming good touch, and knowing that e.g. red 3 is not red 2, because it's not been used to finesse red 1, he might deduce later that the only good red card left is red 2 and might play it.

**Comment by pianoblook** [comment]
I'm strongly against this, at least for non-HVR. It's probably good in Clue Starved etc though.

Going off what ADrone brought up, I don't think our conventions do a great job of "protecting Alice's chop" (s/o to piper).

These days I'll sometimes even look for kinda weird clues that call for a fix, assuming the game has been going smoothly.

**Comment by J-Fricke** [comment]
I definitely see ADrone's point and at the same time have found myself wanting this Transfer. Have even tried getting buy-in for it in some games as I have found a lot more cases where it's useful to CM via the early fix than simply fix to delay myself discarding. I trust my team to have properly protected my chop via actions they have taken and the vision the table has.

**Comment by Zamiell** [comment]
i renamed this in the doc now
